### ISSUE TITLE
Question: Why is token refreshing for the (javascript) implicit flow so complex in Open ID Connect?

### ISSUE THREAD

**Issue by ambvdijk** [IdentityServer/IdentityServer3#1086]
Hi @brockallen,

I hope you don't mind me asking a more general question in your issue list. I have been wondering the following: Why is the whole token refreshing so complex (iframe's, redirects, etc) in OIDC for javascript apps?

Isn't it possible to create a json endpoint that will provide you with a new token as long as the issued cookie is still valid? What are the security issues that arise if you do this?

I could imagine an endpoint that accepts for example a POST to:

https://www.idsrv.com/token/refresh With form data:
client_id=1111
access_token=2222
scope=openid profile

This could then do the following:
- Check if the idsrv cookie is still valid (User.Identity.IsAuthenticated)
- Check if the access_token is still valid
- Check if no additional scopes are requested
- Return a "fresh" access token:

````
{
    access_token:3333,
    expiration: 3600
}
````
I'm probably missing an import security issue here, but I'm not able to find the reason for the complex iframe refresh cycle in the open id specs.

Could you elaborate on this? I'm trying to understand.

Kind regards,
Mathijs van Dijk

**Comment by brockallen** [comment]
Tricky to answer since the spec doesn't allow for that scenario and they don't explicitly say why.

But from my reading and understanding (and assuming), it's because the spec makes a distinction between the client and the user. They want to ensure that tokens that are being returned are to the proper client. For confidential clients they can use a token endpoint because those calls can be authenticated, but for a JS app it can't keep secrets (thus it's considered public). So this then means they need some other way to guarantee that tokens are being sent only to the right client, and using redirects to pre-registered callback URIs is the way to do that for these browser based clients.

Also, that endpoint you describe would suffer from XSRF attacks.

**Comment by ambvdijk** [comment]
Thank you for taking the time and the explanation!
