### ISSUE TITLE
Is it possible to keep SignInMessage cookies after login so Back button don't show an error ?

### ISSUE THREAD

**Issue by fbeauche** [IdentityServer/IdentityServer3#1117]
The POST on to login form clear the SignInMessage Cookie before redirecting the user to the application ( i've got RequireConsent=false). 
So if the user do "Back" it show the error "There is an error determining which application you are signing into. Return to the application and try again.".

I've tried playing around with SignInMessageThreshold but it does not seems to change anithing.

**Comment by brockallen** [comment]
We've discussed this elsewhere in another issue. The problem is that what do you expect IdSvr to do when the user hits the back button? IdSvr no longer knows what app was requesting the login.

**Comment by fbeauche** [comment]
Does the SignInMessage cookie have this info?

**Comment by brockallen** [comment]
It's removed once the user has logged in.

The problem is that the browser is not really honoring the back button to the correct URL. The flow is:

GET app 302 -> GET authorize 302 -> GET login 200 -> POST login 302 -> GET authorize 302 -> POST app 200

So when the user hits back, Chrome seems to return the user to the "GET login" page (which was the last page that issued a 200 I guess). It seems to be browser specific as well: FF seems to work differently. I don't know what IE does. 

So, you arrive on the login page without a signin message, you're already logged in, and I guess the best IdSvr could do would be to redirect you to the IdSvr home page... but that might be disabled.

So it's complicated and I don't know what the best approach is.

**Comment by fbeauche** [comment]
I've tested with IE 11 and Firefox 36. They all have the same behaviour. 

Here is some ideas (maybe not all good/possible, just trying to help find a solution :)  )  : 

- Don't rely on Cookies between authorize endPoint and Login/Consent pages but use queryString. This way the login page in browser history will have all the information needed redirect the use back to the application. 

- Before redirect the user to the app, the authorize endpoint could respond an http 200 with a "meta" refresh or a JavaScript redirect so the http 200 is in browser history.

- Maybe don't remove signInMessage cookie once user is logged in?

If nothing else is it currently possible to customize the message so it make more sense for our users?

**Comment by jageall** [comment]
this is our number 1 production error in our logs by some way.  We believe
this is primarily caused by the sign in page being bookmarked rather than
the back button given our analysis.  This is not helped by password
managers auto bookmarking the sign in page.

At the moment, we are looking at putting in some middle ware upstream to do
a redirect that makes sense for us, but an extension point here where we
could decide whether to redirect or log an error would be helpful.

**Comment by johnkors** [comment]
Yep, the browser remembering a ?signin=asdasdasdadasd is an issue. We're thinking of handling the "signinmessage missing" error by redirecting to a new signin session for a common client (the users edit profile client) when that occurs.

**Comment by brockallen** [comment]
Ok, we'll discuss and see if we can come up with something (for 2.0.0).

**Comment by brockallen** [comment]
Ok, what about a URL to redirect the user to when they arrive on the login page without a sign-in message?

**Comment by jageall** [comment]
that would work for us (that is what we are doing in the pipeline in front
of identityserver)

**Comment by fbeauche** [comment]
That would work for us too.

Thanks for the great support :)

**Comment by brockallen** [comment]
So... should this URL be followed if there's no valid signin cookie, or do we display the login page and if they login we then follow the URL?

**Comment by brockallen** [comment]
Ok, I added a new property called `InvalidSignInRedirectUrl` on the `AuthenticationOptions` on the dev branch (for the next 1.x release).

**Comment by easygoingalex** [comment]
So, could this not be a client based parameter and also when using the oidc javascript library, I'm struggling to see how we could suppress this error in that situation.
