### ISSUE TITLE
SignInMessage and nonce can be created multiple times; Request Too Long

### ISSUE THREAD

**Issue by AdamDotNet** [IdentityServer/IdentityServer3#1124]
It appears that for every authentication challenge, SignInMessage.base64String and OpenIdConnect.nonce.base64String are continually added, and seemingly only one is removed on a successful login. This problem is exacerbated by browsers that don't seem to remove session cookies correctly (Chrome) or if the user times out and a new challenge occurs. Session Management also triggers a challenge at times. Eventually they get an HTTP error "Request Too Long" and it is impossible to move forward unless the user closes the browser and logs in again (except in Chrome because it doesn't clear session cookies upon closing the browser), or the user manually clears cookies.

**What can I do to tell Identity Server to clear ANY SignInMessage and nonce on a successful sign in?** Or perhaps clearing the old ones immediately upon finding extras in the request header, that seems even better if possible.

Simple reproduce steps, go to your sign in page and continually create sign in requests. For my app, I have a link to the "default/home" page of an app, which default page requires authentication. I just keep clicking on that until it blows up.

See fiddler screen capture: https://onedrive.live.com/redir?resid=8478D2C52FB535E0!174177&authkey=!AKxd9UFxQ_T4ouI&v=3&ithint=photo%2cPNG

**Comment by johnkors** [comment]
@loctanvo added a feature where you may set the amount of signinmessage cookies before they are recycled. The default is 5, at which point IIS often begins to complain about "Request Too Long" (at about 15kB of siginmessage cookies).

https://github.com/IdentityServer/IdentityServer3/blob/master/source/Core/Configuration/AuthenticationOptions.cs#L135

**Comment by loctanvo** [comment]
@AdamDotNet Like @johnkors mentioned, there is an option to set the overflow limit for SIgnInMessage cookies. Keep in mind that at least `1` will be kept (handled for you, so defining a negative number or 0 will result in one SignInMessage).

Regarding the `OpenIdConnect.nonce.base64string`, this has nothing to do with the IdServer-part. It's caused by the middleware you are using to integrate your your client/RP with IdServer. I have previously [registered an issue at the Katana project](http://katanaproject.codeplex.com/workitem/402),  and it has later been moved to the [aspnet/security repo](https://github.com/aspnet/Security/issues/179). Feel free to add your comment or opinion in the issue.

A *temporary* fix is to downgrade your OIDC middleware to v.3.0.0. In that version, only one nonce is created and re-written for new login sessions.

A last comment on Chrome and session cookies: they do get cleared, but you need to exclude all chrome processes running in the background. Otherwise the session cookie is kept. At least that's our experience.

**Comment by AdamDotNet** [comment]
Absolutely wonderful responses! Thank you. I'm going to dig around a bit to see how I can best work with the Nonce problem, which might be just to use 3.0.0 like you said, but apparently 3.0.1 fixed  a different nonce issue.

I'll close the issue hopefully by the end of the day, or comment if something else goes awry.

**Comment by AdamDotNet** [comment]
The `SignInMessageThreshold ` worked like a charm! The Middleware took a little work, but I'll provide what I did below.

My ultimate solution was to delete all nonce cookies that weren't the current one upon calling RememberNonce.

Here's the handler code:

```C#
public class SawtoothOpenIdConnectAuthenticationHandler : OpenIdConnectAuthenticationHandler
{
	public SawtoothOpenIdConnectAuthenticationHandler(ILogger logger)
		: base(logger) { }

	protected override void RememberNonce(OpenIdConnectMessage message, string nonce)
	{
		var oldNonces = Request.Cookies.Where(kvp => kvp.Key.StartsWith(OpenIdConnectAuthenticationDefaults.CookiePrefix + "nonce"));
		if (oldNonces.Any())
		{
			CookieOptions cookieOptions = new CookieOptions
			{
				HttpOnly = true,
				Secure = Request.IsSecure
			};
			foreach (KeyValuePair<string, string> oldNonce in oldNonces)
			{
				Response.Cookies.Delete(oldNonce.Key, cookieOptions);
			}
		}
		base.RememberNonce(message, nonce);
	}
}
```
Note that `OpenIdConnectAuthenticationDefaults.Nonce` is an internal constant or I would have used that in my linq query.

**Comment by Erwinvandervalk** [comment]
I also ran into this issue. Thanks for the solution. However.. I'm wondering why the old nonces and signin messages are being kept at all? any thoughts on that?

**Comment by loctanvo** [comment]
@Erwinvandervalk Short answer: To support multiple login sessions, eg. the user opens two tabs and starts a login attempt in both.

**Comment by Erwinvandervalk** [comment]
@loctanvo Thanks, that's clear.

**Comment by leastprivilege** [comment]
Nonce does not come from idsrv - that’s MS’ middleware.

We also try to do our best to cleanup signing messages - are you on the latest 1.x version?

— 
cheers
Dominick Baier


On 23 Jun 2015 at 11:25:23, Erwin van der Valk (notifications@github.com) wrote:

@loctanvo Thanks, that's clear.

**Comment by Erwinvandervalk** [comment]
we're on 1.6.1.. 

Our problem (and some confusion) came from using Nowin as a server. When the request headers became too big (9000 bytes), it returned a 500 error. Microsoft.owin.selfhost returned a clearer error (400 bad request). We reached that limit with about 5 signin cookies and 5 nonce cookies and an asp.net authentication cookie. 

Using the solutions specified above seems to keep the number of cookies down.

**Comment by skoub** [comment]
What's the solution exactly? Use the `SignInMessageThreshold` or use the ; `OpenIdConnectAuthenticationHandler`? And if it's `OpenIdConnectAuthenticationHandler`, where should i implement it? I searched a way to attach the code somewhere but didn't find anything.

**Comment by promontis** [comment]
If you are using vNext, set options.CacheNonces = true in UseOpenIdConnectAuthentication... it will use the default IDistributedCache from ASPNET. Don't forgot to AddCaching() to the services collection (which will register LocalCache for IDistributedCache.. you could override it for say a RedisCache later on).

**Comment by AdamDotNet** [comment]
@skoub Sorry I didn't reply to this sooner, but if you want to use the `OpenIdConnectAuthenticationHandler` I posted, you have to make your own middleware, extending `OpenIdConnectAuthenticationMiddleware` and override 

`protected override AuthenticationHandler<OpenIdConnectAuthenticationOptions> CreateHandler()`

returning a new instance of your `OpenIdConnectAuthenticationHandler`. Then in Startup.cs, `app.Use<CustomOpenIdConnectAuthenticationMiddleware>(...)` or create an extension method like most middleware does.

**Comment by mmihaylov** [comment]
Which package should be downgraded to v.3.0.0? I am using Microsoft.Owin. There are several packages like
- Microsoft.Owin
- Microsoft.Owin.Host.SystemWeb
- Microsoft.Owin.Security
- Microsoft.Owin.Security.Cookies
- Microsoft.Owin.Security.OpenIdConnect

All of them now are version 3.0.1. Should I make them all 3.0.0? 

I have separate IdentityServer web app and Public website app using it to authenticate. Should I update in both apps these packages?

**Comment by loctanvo** [comment]
@mmihaylov You only need to downgrade Microsoft.Owin.Security.OpenIdConnect.

**Comment by c0bra99** [comment]
I keep running into this issue on my development and test severs because I use Chrome's "Continue where you left off" feature in conjunction to leaving multiple tabs open, closing my browser at end of the day and when I open the browser the next day my login has expired and I get the login screen open in many tabs.

It seems the issue has been fixed for the asp.net v5/v.next/asp.net core release, and won't be fixed in the existing Microsoft.Owin packages according to the latest comment on: https://github.com/aspnet/Security/issues/390

@skoub I know this is old and you've probably fixed it by now, but here is my full implementation of @AdamDotNet 's SawtoothOpenIdConnectAuthenticationHandler fix (including extension method) for anyone who stumbles across this in the future and wants a quicker implementation. 
Just add these 2 classes to your project and replace your 
app.UseOpenIdConnectAuthentication(new OpenIdConnectAuthenticationOptions

with 
app.UseOpenIdConnectAuthentication**Patched**(new OpenIdConnectAuthenticationOptions

```
public static class OpenIdConnectAuthenticationPatchedMiddlewareExtension
    {
        public static Owin.IAppBuilder UseOpenIdConnectAuthenticationPatched(this Owin.IAppBuilder app, Microsoft.Owin.Security.OpenIdConnect.OpenIdConnectAuthenticationOptions openIdConnectOptions)
        {
            if (app == null)
            {
                throw new System.ArgumentNullException("app");
            }
            if (openIdConnectOptions == null)
            {
                throw new System.ArgumentNullException("openIdConnectOptions");
            }
            System.Type type = typeof(OpenIdConnectAuthenticationPatchedMiddleware);
            object[] objArray = new object[] { app, openIdConnectOptions };
            return app.Use(type, objArray);
        }
    }

    /// <summary>
    /// Patched to fix the issue with too many nonce cookies described here: https://github.com/IdentityServer/IdentityServer3/issues/1124
    /// Deletes all nonce cookies that weren't the current one
    /// </summary>
    public class OpenIdConnectAuthenticationPatchedMiddleware  : OpenIdConnectAuthenticationMiddleware
    {
        private readonly Microsoft.Owin.Logging.ILogger _logger;

        public OpenIdConnectAuthenticationPatchedMiddleware(Microsoft.Owin.OwinMiddleware next, Owin.IAppBuilder app, Microsoft.Owin.Security.OpenIdConnect.OpenIdConnectAuthenticationOptions options) 
                : base(next, app, options)
        {
            this._logger = Microsoft.Owin.Logging.AppBuilderLoggerExtensions.CreateLogger<OpenIdConnectAuthenticationPatchedMiddleware>(app);
        }

        protected override Microsoft.Owin.Security.Infrastructure.AuthenticationHandler<OpenIdConnectAuthenticationOptions> CreateHandler()
        {
            return new SawtoothOpenIdConnectAuthenticationHandler(_logger);
        }

        public class SawtoothOpenIdConnectAuthenticationHandler : OpenIdConnectAuthenticationHandler
        {
            public SawtoothOpenIdConnectAuthenticationHandler(Microsoft.Owin.Logging.ILogger logger)
                : base(logger) { }

            protected override void RememberNonce(OpenIdConnectMessage message, string nonce)
            {
                var oldNonces = Request.Cookies.Where(kvp => kvp.Key.StartsWith(OpenIdConnectAuthenticationDefaults.CookiePrefix + "nonce"));
                if (oldNonces.Any())
                {
                    Microsoft.Owin.CookieOptions cookieOptions = new Microsoft.Owin.CookieOptions
                    {
                        HttpOnly = true,
                        Secure = Request.IsSecure
                    };
                    foreach (KeyValuePair<string, string> oldNonce in oldNonces)
                    {
                        Response.Cookies.Delete(oldNonce.Key, cookieOptions);
                    }
                }
                base.RememberNonce(message, nonce);
            }
        }
    }

```
Another alternative server side registry workaround (with some security concerns you must take into consideration) The issue would only be delayed until the new max request size is reached.
https://support.microsoft.com/en-us/kb/2020943
http://www.grouppolicy.biz/2013/06/how-to-configure-iis-to-support-large-ad-token-with-group-policy/

```
Windows Registry Editor Version 5.00

[HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\HTTP\Parameters]
"MaxRequestBytes"=dword:01000000
"MaxFieldLength"=dword:0000fffe
```

**Comment by abhijitpattanayak** [comment]
@AdamDotNet  i don't get where to post your code what you have given to delete all the Nonce cookies . please let me know.

**Comment by abhijitpattanayak** [comment]
@AdamDotNet i don't get where to post your code what you have given in "SawtoothOpenIdConnectAuthenticationHandler "  to delete all the Nonce cookies . please let me know.

**Comment by doublej42** [comment]
Thank you @AdamDotNet  and @c0bra99 for pointing me in the right direction.

I've tweaked it a bit to add a limit of 5 or configurable nonce per app . I also added some experimental support for paths incase someone opens /app1 and /app2 and so on in various tabs on your domain.

https://gitlab.com/snippets/21487

**Comment by avmp2208** [comment]
Hello, I ran into the same problem, I realized that when the same user start login in a computer then start another sesion in another computer but the firt computer delete its cookies and try to login with the same user again the page throws this error "Bad Request - Invalid Header" and falls in a endless loop. So, on solution is restart the applicationpool and the user can login again,

How to fix that problem? is it necesary to add the OpenIdConnectAuthentication Middleware? because I tried to set SignInMessageThreshold = 0 and the same error was threw.

Where do I have to use OpenIdConnectAuthenticationPatchedMiddleware  ?? 
Client or IdentityServer Service?

thank you for your help.

**Comment by eclipsed82** [comment]
So do we add this middleware extension to the IdentityServer project or to each client app?

**Comment by doublej42** [comment]
My code was a patch to the openIDConnect code from microsoft. The bug for me was at the client side. If that is your question @eclipsed82

**Comment by eclipsed82** [comment]
Thanks so much, @doublej42 . Do you know how to replicate the Bad Request / cookie issue? It happens to me by "accident" and then I try to replicate it and I don't come across it. I'd like to test the fix by first replicating the issue before the code fix, then replicating after to see if it's fixed. Make sense?

**Comment by doublej42** [comment]
@eclipsed82 for me and what my code patches is that there are too many cookies and it's exceeding the max cookie length. When you start a login then go back and start a new login it creates a new cookie. So you can test with just hitting a page that forces login but not login in and going have to the url.

**Comment by RossLieberman** [comment]
I also found the supplied code incredibly useful, but I've made one adjustment. Instead of deleting all non-current cookies, I just set all nonce cookies to have an expiration of 30 minutes. This way  the user can have multiple tabs / windows without compromising those logins. I made an update to the RememberNonce override method, instead of deleting all other cookies before calling base I just completely replaced the method:

```c#
protected override void RememberNonce(OpenIdConnectMessage message, string nonce)
{
    if (message == null)
        throw new ArgumentNullException(nameof(message));
    if (nonce == null)
        throw new ArgumentNullException(nameof(nonce));

    Response.Cookies.Append(
                    GetNonceKey(nonce), 
                        Convert.ToBase64String(
                            Encoding.UTF8.GetBytes(Options.StateDataFormat.Protect(
                                new AuthenticationProperties
                                    {
                                        Dictionary = { { "N", nonce } }
                                    }
                                )
                            )
                        ), 
                        new CookieOptions
                        {
                            HttpOnly = true,
                            Secure = Request.IsSecure,
                            Expires = DateTime.UtcNow.AddMinutes(30)
                        }
                    );
}
```

Not directly related to this ticket, but an issue I was encountering was with redirect loops because the Owin Authentication Ticket Session Cookie not get removed when it expires, it existed in session before logging in and then after logging in I would return right back to IdentityServer. I added the following code in my RedirectToIdentityProvider Notification to delete the local cookie before going to IdentityServer:

```c#
return new OpenIdConnectAuthenticationNotifications
{
    RedirectToIdentityProvider = async n =>
    {
        switch (n.ProtocolMessage.RequestType)
        {
            case OpenIdConnectRequestType.AuthenticationRequest:
                // hack to work around session cookie not being removed when expires. this is preventing owin from accepting an open id response
                n.OwinContext.Authentication.SignOut("Cookies");
                break;
        }
    }
};
```

**Comment by eclipsed82** [comment]
Thanks so much @doublej42 and @RossLieberman !

**Comment by laksh-parab** [comment]
i am still having issue even if downgraded 

> Microsoft.Owin.Security.OpenIdConnect

 i have created [SO post](http://stackoverflow.com/questions/42729875/too-many-openid-nonce-cookies-cause-bad-request)

**Comment by sudipster** [comment]
Here is an update to @AdamDotNet 's SawtoothOpenIdConnectAuthenticationHandler which will preserve the last/latest 5 Nonce cookies and will delete any that are older that those.  In order for this to work, ProtocolValidator.RequireTimeStampInNonce must be set to true in OpenIdConnectAuthenticationOptions. 

private readonly int MaxNumberOfNonceCookies = 4;
            public CustomOpenIdConnectAuthenticationHandler(Microsoft.Owin.Logging.ILogger logger)
                : base(logger) { }

            protected override void RememberNonce(OpenIdConnectMessage message, string nonce)
            {
                var oldNonces = Request.Cookies
                                    .Where(kvp => kvp.Key.StartsWith(OpenIdConnectAuthenticationDefaults.CookiePrefix + "nonce"))
                                    .ToList();

                //My Update to this solution in katana forum, remove all older cookies exept the last few.
                //TODO: Only preserve last MaxNumberOfNonceCookies Nonces, remove older ones if they exist.
                oldNonces = GetListOlderCookiesToRemove(oldNonces);

                if (oldNonces != null && oldNonces.Any())
                {
                    Microsoft.Owin.CookieOptions cookieOptions = new Microsoft.Owin.CookieOptions
                    {
                        HttpOnly = true,
                        Secure = Request.IsSecure
                    };
                    foreach (KeyValuePair<string, string> oldNonce in oldNonces)
                    {
                        Response.Cookies.Delete(oldNonce.Key, cookieOptions);
                    }
                }

                base.RememberNonce(message, nonce);
            }

            private string GetUnprotectedNonce(string val)
            {
                var bytes = Convert.FromBase64String(val);
                var str = Encoding.UTF8.GetString(bytes);
                var authProps = this.Options.StateDataFormat.Unprotect(str);
                return authProps.Dictionary["N"];
            }

            private List<KeyValuePair<string, string>> GetListOlderCookiesToRemove(List<KeyValuePair<string, string>> oldNonces)
            {
                if (oldNonces == null || oldNonces.Count < MaxNumberOfNonceCookies)
                {
                    return null;
                }

                var cookieTimestampMap = new Dictionary<string, DateTime>();
                if (oldNonces.Any())
                {
                    foreach (KeyValuePair<string, string> oldNonce in oldNonces)
                    {
                        var nonceVal = oldNonce.Value;

                        var unprotectedVal = GetUnprotectedNonce(nonceVal);

                        var nonceValTs = unprotectedVal.Split('.');
                        if (nonceValTs.Length > 1)
                        {
                            cookieTimestampMap.Add(oldNonce.Key, new DateTime(long.Parse(nonceValTs[0]), DateTimeKind.Utc));
                        }
                    }

                    if (cookieTimestampMap.Any())
                    {
                        var listOfCookieKeys = cookieTimestampMap.OrderByDescending(x => x.Value)
                            .Take(MaxNumberOfNonceCookies)
                            .Select(x => x.Key)
                            .ToList();
                        if (listOfCookieKeys.Any())
                        {
                            oldNonces = oldNonces.Where(x => listOfCookieKeys.Contains(x.Key) == false).ToList();
                        }
                    }
                }

                return oldNonces;
            }

**Comment by rizamarhaban** [comment]
Okay, this is apparently an old issue. I have try all solution in here but still got the "```Bad Request - Request too long```" error. After doing some investigation, here is how to repeat this:

- [x] If in IIS I deploy to "**Default Web Site**" or I use "**Add Websites**" menu or using different binding Port on Default Web Site, then the issue is not exist, even using ```Microsoft.Owin.Security.OpenIdConnect v3.1.0``` which I use.

- [X] Now if, in IIS I created a **Virtual Directory** first pointing to a physical folder, copy the application to that folder, **Convert to Application**, than the issue appear. Here is the virtual path that I have tested to reproduce the issue:

        // Identity Server (Authority):
        http://localhost/STAGING/myids3

        // Web MVC client:
        http://localhost/STAGING/myapp

    Physical folder:

        // Identity Server:
        C:\Projects\STAGING\identityservice\

        // Web MVC:
        C:\Projects\STAGING\mywebapp\

Running '**myapp**' will redirect me to the '**myids3**'. Do Login and the error will appear.

If we use Port instead of Virtual Directory, will not generate the error:

        // Identity Server (Authority):
        http://localhost:5000/

        // Web MVC client:
        http://localhost:6000/

Anyway, this is my case and what happen to me. I experience this while trying to deploy the application to client machine and it starts showing that request too long error. When I deploy to IIS (_similar environment as my client_) the issue also appears. Been downgrading the ```Microsoft.Owin.Security.OpenIdConnect``` to 3.0.0, the issue also the same and it loop with the title "Submit this form" on browser.

All of my deployment test is using "**Add Websites**" in IIS and nothing wrong. However the problem is, my client server environment not allowing me to use "**Add Websites**", instead, they just give the Virtual Directory physical folder.

Anyone can help on this...?

**Comment by fiantsev** [comment]
@sudipster @c0bra99 guys, do you know how to use that in case of IApplicationBuilder.
I don't have IAppBuilder, my service startup code looks like:

`protected override void AdditionalConfigure(IApplicationBuilder app)`

**Comment by rizamarhaban** [comment]
@leastprivilege

For my issue, I found out that the Path which suppose to be '**/**' but because I use virtual directory (_I explain the issue previously above_), it shows like this:

![image](https://user-images.githubusercontent.com/1063940/29468580-6dfd030c-8477-11e7-8f8b-bf0bae884995.png)

Once the login authorized, it loops non-stop and I had to stop the browser. And the cookies shows like this:

![image](https://user-images.githubusercontent.com/1063940/29468692-e88027a8-8477-11e7-9ad3-7b0f8a0aeff7.png)

If I did not use the ```SawtoothOpenIdConnectAuthenticationHandler``` by @c0bra99 solution above, this nonce list would be long and it shows the message ```Bad Request - Request too long```.

I compare this with the normal ```localhost``` deployment with different port which shows the Path is '**/**' only. How to make this relative path gone?

**Comment by c0bra99** [comment]
@rizamarhaban I think the reason it is working on a different port instead of the virtual directory is you have too many cookies for the one url, and all of the root:port + root:port/folder cookies are included. If you change the port your cookies start fresh, until the issue occurs again if you'r not using one of the workarounds to clear the cookies. If you clear your cookies manually it should work again, and once you have one of the workarounds in place it should prevent it from happening again.

**Comment by rizamarhaban** [comment]
@c0bra99 well, is not just using port. If I deploy directly to **Default Web Site**, the issue not appear and it works normally. I have clear all the cookies every tesing on the browser as well.

This issue will appear if we deploy on a virtual directory in IIS as shown on the image of my testing above. Other than this, the issue not exist and works normally.

**Comment by rizamarhaban** [comment]
@leastprivilege @c0bra99

Damn! I hate to say this. I miss the '/' on the **RedirectUrl** again. Okay, it solves my looping issue now. Oh my... not colon, semicolon, slash and backslashes can took hours of debugging.
