### ISSUE TITLE
Suitable production configuration for IdentityServer

### ISSUE THREAD

**Issue by skuvnar** [IdentityServer/IdentityServer3#1129]
Hi, I have been playing around with IdentityServer which uses ADFS as the identity provider. In terms of deploying it to production, do I need 2 certificates - eg one for the SSL and one for the signing certificate (do I even need the signing cert)? 

Many thanks for any help.

**Comment by brockallen** [comment]
Yep -- those need to be two different certs.

**Comment by roryprimrose** [comment]
Is a signing certificate required to use an access token for a Resource flow? 

This is my understanding of our usage: 

- The browser gets the token from the signin redirect querystring (a reference access token on an implicit flow) and provides it to the API as a bearer token. We are using ADFS with wsFed behind ID3. 
- The API (ID3 OWIN bits) then communicates with ID3 over HTTPS. The result is presumably the claim set for the user. 

I'm guessing that the part of the process that uses a singing certificate is the second step where the claims are returned to the API from ID3 for the bearer token. Is that correct? Is it required?

**Comment by johnkors** [comment]
If you don't want to ask idsrv for validation at each request to your API (idsrv then needs to be scaled towards the sum of all your APIs traffic) , you can use signed JWTs instead of reference tokens. Less traffic, but involves crypto validation instead. At that point, you would need signing.

Also, id tokens only come as signed jwts - and you would need to verify by crypto (or also here ask idsrv for validity at the identitytoken validation endpoint => more traffic towards idsrv).

I prefer to have less traffic and do the validation at the clients. Libs are available to do this.

**Comment by jbrittan** [comment]
Could someone clarify the security implications or reasons of why you should have 2 different certificates 1 for SSL and one for signing (the tokens from IdenityServer)?

Thanks in advance.

**Comment by johnkors** [comment]
@jbrittan imo: Seperation of concerns / Single point of failure? Do you use the same password for your Google and Facebook accounts, as well as your internet banking accounts? SSL has to do with not being able to eavesdrop traffic, the other has to do with verifying the sender of information. Do you want both to fail, if there's a issue with one of the features, or do you prefer only the one to fail? It's up to you to decide (cost/benefit (security)).

**Comment by leastprivilege** [comment]
..in addition - if you would ask a cryptographer - he would say: "never use the same key for two different purposes".

**Comment by jbrittan** [comment]
That is kind of what I thought I just wanted to make sure I wasn't missing anything else.  

Thank you.
