### ISSUE TITLE
IdentityServer with webforms

### ISSUE THREAD

**Issue by henninga** [IdentityServer/IdentityServer3#1171]
Hi

Is webforms supported in identityserver/owin/katana? One of our applications is still in webforms (but under migration to mvc) and we'd like to have single sign-in there as well.

**Comment by loctanvo** [comment]
IdServer doesn't care about what client technology you are using. As long as the client can make HTTP requests, IdServer is fine. I guess it's possible to use OpenIdConnect middleware in a webform project, but I've never tried. Otherwise, you could always handroll your own HttpHandler and do token validation etc there. It's actually not very difficult.
