### ISSUE TITLE
Multiple sites and web api

### ISSUE THREAD

**Issue by henninga** [IdentityServer/IdentityServer3#1212]
Hi

I've set up idsrv and got it working perfectly with all our sites. Now I need to add web api to the mix. After hours and hours of trying different configurations, I cannot get it to work. Either I get an unauthorized response, or I get it partly working but when I log into site A I get logged out of site B. If I then go to site B, I get logged out of site A. I've tried both implicit and hybrid flows with different access token types

I'm using bearer tokens to authenticate with the web api.
All sites need to be able to communicate with the web api.

I've made a repro at https://github.com/henninga/IdentityServerSample. It is based on the MVC Authentication sample but I added another mvc site to simulate our set up.

Any help would be greatly appreciated as I am truly stuck now

**Comment by loctanvo** [comment]
1. Does it work with only one mvc and one api? Just to eliminate any client/scope/claim setup errors.
2. Keep in mind that cookies are per domain. If you have multiple sites running on localhost, chances are there that they may overwrite each other (if them have the same name).

**Comment by henninga** [comment]
1. If I only log into site A and use the web api there is no problem. The problem with staying signed in starts when I sign in into site B.
2. I don't have this issue in my current setup where web api support is not yet added. I have 3-4 sites running on different localhost ports and once I log into one site I'm automatically logged into all.

I believe the issue is a combination of wrong scopes and responsetypes in the client setup, and AuthorizationCodeReceived and SecurityTokenValidated. One theory is that the access token is overwritten somehow.

**Comment by loctanvo** [comment]
Do you get the error both for `/CallApi/ClientCredentials` and `/CallApi/UserCredentials`?

>I don't have this issue in my current setup where web api support is not yet added. I have 3-4 sites running on different localhost ports and once I log into one site I'm automatically logged into all.

Are you sure everything works properly, and not just that it *seems* to work correctly? Assuming A and B are writing to the same cookie due to both being on localhost and having the same name. It could still be that for the user, everything appears to be fine. App A requires authentication, which sends the user to IdServer. She logs in, and an `idserver` cookie is issued, get redirected back to A, and an A cookie is issued. She then logs in to B, get redirected to IdServer where the `idserver` cookie is still present and she does not need to provide credentials. She gets redirected back to B, and B issues a cookie, *overwriting* A cookie. Then she goes to A, *is logged out*, and get redirected to IdServer. There the IdServer cookie is still present, hence, no credentials. In this case, from the user perspective, everything works as expected.

In theory, unless you have cookies messed up, there's no automatic logic for logging one user out of one application when she logs into another. Just my 2 cents.

**Comment by henninga** [comment]
The calls to /CallApi/ClientCredentials and /CallApi/UserCredentials work fine as far as I can see.

Your description seems to be what is happening. But that is not what I expect to be happening. I never had this problem before I tried to add support for web api (bearer tokens). When using an implicit client I would never get redirected to idserver when flipping between sites.

The example solution in the repository pretty much replicates the "error" I'm having.

**Comment by loctanvo** [comment]
To avoid the possibility of cookie mismatch (on localhost), I would simply start off by specifying a unique cookie name for both A and B. This way, the two applications will not get in the way of each other. Then do some further testing.

I have a theory why "everything worked fine" before you added WebApi. I guess that A and B were overwriting the same cookie. However, since they use the same data protector for encrypting/decrypting the content (since you are not specifying anything). The two apps actually successfully share the cookie. With WebApi, when you try to look for the `access_token` in the cookie, it may be missing if it has been overwritten. Just wild guessing.

**Comment by henninga** [comment]
Thank you for your help. 

I've been able to fix it and it was as you said a problem with cookie names. I'm still having some small issues with regards to how I expect it to work but that is something I can live with for now.

**Comment by skoub** [comment]
can you update your github demo with the solution? It may help other people like me :)
