### ISSUE TITLE
How to obtain an identity token from an access token?

### ISSUE THREAD

**Issue by feina** [IdentityServer/IdentityServer3#1237]
Is it possible to get an identity token from an access token?
Which endpoint should I use?
Thanks

**Comment by leastprivilege** [comment]
no. why?

**Comment by brentschmaltz** [comment]
@feina if you have obtained the AccessToken from a Code granting access to the UserInfo endpoint, then use the value of 'userinfo_endpoint' obtained from the discovery endpoint.
see: http://openid.net/specs/openid-connect-discovery-1_0.html#IssuerDiscovery

**Comment by feina** [comment]
@leastprivilege: I obtained an access token using the resource owner password credentials flow from an application. The access token is sent to a webserver which serves the identity token to a user's browser in order to have the user logged in directly into Identity Server using a custom endpoint.
I know this is a weird case. :(

**Comment by jawadatgithub** [comment]
in order to help:

1. can you explain what is custom endpoint? both OAuth2 & OIDC specs define endpoints as predetermined/fixed set without custom extensions.

2. In any Identity flow in general, entity must be authenticated before its authorized. so how come your case violate the basic concepts of security? in other words, its total disaster to agree upon the concept of using access token to obtain Id_token.

3. fixing typos and understanding basics: `I obtained` should be client obtained, `from an application` should mean STS/IdS3 as tokens can only be obtained from such softwares. `webserver which serves the identity token` should be STS issued...webserver can't issue tokens. even STS can't do what you asking for even after fixing all typos....

hope this give you brief insight.

**Comment by leastprivilege** [comment]
Does not make sense to me. closing.
