### ISSUE TITLE
Questions to satisfy company security review

### ISSUE THREAD

**Issue by richRubie** [IdentityServer/IdentityServer3#1254]
I would really appreciate your help. I’m looking for information regarding Identity server. I wish to use Identity Server in a project but the business wants some assurances on the security of the product.

Can you answer or point me in the direction of existing information to the below questions?
•         Have there been any security vulnerabilities ? How many and over what period? ( I haven’t found any on github)
•         How long did it take to fix any vulnerabilities?
•         What will the product lifetime be i.e. how long expect to be actively working on it? (I can see the milestones are you planning anything past 2.1?)
•         How long do you expect to be supporting any issues found?

Thanks

**Comment by leastprivilege** [comment]
These questions have already been answered privately.

**Comment by leastprivilege** [comment]
to summarize:

We had one minor redirect issue, which we fixed within a week. I forget the issue number, but it’s recorded upon github.
 
As far as lifetime, not sure. It’s our livelihood and passion, so I suspect a while. But we also have a community around IdentityServer, and it’s growing. If vulnerabilities are discovered, we will certainly get them fixed.
 
As for being certified, yes – we’re listed on the OpenID Connect website already and we worked with them on some of the conformance tests. We’ve just not had time to do the formal certification since they released them officially last week.
