### ISSUE TITLE
Question: I need a bit of info on EF and IIS Hosting please

### ISSUE THREAD

**Issue by Grandizer** [IdentityServer/IdentityServer3#1287]
Over the last 3 days I have viewed and read a ton of this IdentityServer3. I have So much information overload here with all of the samples and such that I am not sure what to do anymore.  Sadly none of the samples are telling me exactly what I really need.  I think what I want is rather typical?  I am trying to create a Sing-Sign-On site for our internet and intranet sites.  Seems like IdentityServer3 is ideal.  We want to use EF (Entity Framework.)  May change User entity properties, perhaps even Client properties (maybe.)

All of the samples here suggest to "not combine into single project" and I agree, but I am not 100% sure what to put where.  Is there a sample out there that has an EF (with modifications to perhaps User and/or Client entities) identity service that is only the IIS (or self hosted if only that exists) portion.  Perhaps even the ideal way to load (lazy or otherwise) Clients from the DB.  I think I can figure out how to connect to it via Web API as well as standard MVC and/or WebForms.

I noticed the DB created with the EF sample has no Users in it.  Is there a different location/DB where the Users are stored?

Hope this is the right place to ask questions.

Thanks in advance

**Comment by jawadatgithub** [comment]
> Over the last 3 days I have viewed and read a ton of this IdentityServer3

I think most people here invested much more time to understand OIDC, OAuth2 specs and IdentityServer3. Personally I being spidering around for over 2 months, I am not trying to pull you down. if you want short path then consult Thinktecture, otherwise read and watch videos again, also reading alone not useful alot, download samples now and start experimenting on your machine.

To have quick idea about user stores, take look at @brockallen [IdentityManager](https://github.com/IdentityManager/IdentityManager) videos and [blog materials](http://brockallen.com/) then try to read IdentityServer3 Docs again.

also Issues contain tones of knowledge and most being resolved.

**Comment by loctanvo** [comment]
@Grandizer The EF sample is [using the InMemoryUserService](https://github.com/IdentityServer/IdentityServer3.Samples/blob/master/source/EntityFramework/SelfHost/Config/Factory.cs#L33). If you want to load users from the DB, you need to implement `IUserInterface` and swap out the InMemoryUserService. Look at [this sample](https://github.com/IdentityServer/IdentityServer3.Samples/tree/master/source/CustomUserService) for some custom `UserService` implementations.

In general, IdentityServer does not have a specified concept of registering new users; it's up to you to tell IdentityServer where to look for users by implementing `IUserService`. After running the migrations, you can add some users to the DB (mangement studio or however you want), then quickly implement a UserService to retrieve from DB using EF.

**Comment by Grandizer** [comment]
@loctanvo Thank you for the help and links.  I will continue down the rabbit hole.
