### ISSUE TITLE
No cookie matching signin id found

### ISSUE THREAD

**Issue by imperugo** [IdentityServer/IdentityServer3#1299]
Hi, 
I checked on previous issues for that and the problem seems closed on your repo, but I still having this.

```json
{
  "_index": "logstash-2015.05.04",
  "_type": "logevent",
  "_id": "rFL7_-UqRbG7HjT42yq25Q",
  "_score": null,
  "_source": {
    "@timestamp": "2015-05-04T08:45:37.3654249+00:00",
    "level": "Error",
    "messageTemplate": "No cookie matching signin id found",
    "message": "No cookie matching signin id found",
    "fields": {
      "Name": "Thinktecture.IdentityServer.Core.Endpoints.AuthenticationController",
      "MachineName": "RD0003FF430D95",
      "HttpRequestClientHostIP": "-.-.-.-",
      "HttpRequestRawUrl": "https://auth.mywebsite.it/core/login?signin=fbbf16a673f42b5e3a394b6ac08f31cd",
      "ThreadId": 18,
      "EnvironmentId": "Production",
      "ApplicationId": "MyWebSite-Identity"
    }
  },
  "sort": [
    1430729137365
  ]
}
```
(I removed the ip address of the customer)

Any hint about that?

**Comment by brockallen** [comment]
Somehow the user arrived at the login page when they did not travel thru the authorization endpoint first, *or* they did and the cookie was not issued due to this: https://katanaproject.codeplex.com/workitem/197

**Comment by imperugo** [comment]
Is there a way to manage that?
I mean if the user comes to the login page without travel thru the authorization endpoint I could redirect him to the authorization endpoint.

Does it make sense?

**Comment by johnkors** [comment]
I believe that feature was added recently in the latest nugets, but has not made it to the docs :) 

https://github.com/IdentityServer/IdentityServer3/blob/master/source/Core/Configuration/AuthenticationOptions.cs#L145

**Comment by imperugo** [comment]
Cool!
Just updated the packaged and added InvalidSignInRedirectUrl property.
Let's see if it's better.

Thanks
.u

**Comment by imperugo** [comment]
Ok, I've added and deployed, but still have the problem :S

**Comment by imperugo** [comment]
I think the problem is the wrong url. The users go to the login pages using the history, so they call
this:

https://auth.mywebsite.it/core/login?signin=409d76bf5701bd9b03b00d6ba5683636

I've the correct redirect thanks to InvalidSignInRedirectUrl property but the error is still present into the log.

Is it normal?

**Comment by brockallen** [comment]
Yes, and the logging was changed as well. That might have been done on 2.0.0 dev branch.

**Comment by imperugo** [comment]
Ok. Cool I'll wait the new version.

Thanks

**Comment by briandonahue** [comment]
What URL would you need to set `InvalidSignInRedirectUrl` to to fix this?  I am getting sporadic reports of users seeing:
> Error: There is an error determining which application you are signing into. Return to the application and try again.

I see a lot of the "no cookie matching signin id" errors in the logs, but am unsure if the two are related.

**Comment by brockallen** [comment]
Set it to any URL you can handle. The idea is that your code at this endpoint would do "something" that's appropriate for your use of IdSvr.

**Comment by briandonahue** [comment]
Ah, I thought it was saying we should redirect them back to the authorization endpoint, which I assumed was an IdSrv url.  Wouldn't I need to know which client they came from, etc, to set this to something useful?  I guess I just am not understanding the use case.

**Comment by brockallen** [comment]
Well, that's the problem -- we don't know what it means. This is why you're expected to provide the endpoint to do the best you can. IdentityServer certainly can't know how you want to handle this scenario.

**Comment by briandonahue** [comment]
OK.  I am just trying to process of elimination figure out where the missing cookie error is coming from.  Thought maybe there was an easy way to exclude the scenario above where he mentioned users were including a signin id in the url rather than getting a new one.  I have a feeling that's not our issue, but I also wasn't sure if the katana cookie issue would be affecting me either (see above) since we don't have that DLL referenced in our self-hosted version, but maybe I'm missing something there.

**Comment by brockallen** [comment]
Well, the underlying issue is that a user can't just come directly to the login page (presumably via a bookmark). They have to be brought there due to a login request from a client. So as a way to tell the user to not do that, this redirect was added. Maybe you give them a message saying "hey we have 12 apps -- go to the one you want to use to get logged in". Or, OTOH, maybe your scenario you only have one client -- so then make this redirect go back to that client to initiate the login process. Like I said, IdentityServer itself can't know which of these you want.

**Comment by briandonahue** [comment]
AH, thanks!  I understand now.
