### ISSUE TITLE
Question about logging out in a native app after authenticating using the resource owner credential flow

### ISSUE THREAD

**Issue by martin-evans** [IdentityServer/IdentityServer3#1337]
I'm prototyping a native app which will authenticate against my own IdentityServer instance using the resource owner credential flow. Given only a bearer token is sent back to the client (and no identity token), is there a best practice way of logging out feature in my app? 
	
The reason I'm asking is because the logout endpoint seems to be for other auth flows where an identity token is held on the client then passed in the query string.
	
Many thanks.

**Comment by leastprivilege** [comment]
Strictly speaking - the resource owner flow is not part of OIDC. There is no logout. 

Delete the access token (and optionally revoke it using the revocation endpoint).

**Comment by martin-evans** [comment]
Thanks for the advice. 

Great product btw!

**Comment by eskitek** [comment]
Sorry to dig this one back up again, but I've got a related question.

We have an AngularJS client that is using the Resource Owner flow to authenticate against our own Identity Server. When the user logs out of the app, we'd like to revoke the access token (we are using reference tokens). Reading your advice above, and the Revocation endpoint documentation, it seems like this should be possible.

The issue we're running into is that the browser is pre-flighting the POST request to the Revocation endpoint with an OPTIONS request, but it doesn't seem like the Revocation endpoint allows the OPTIONS method (We get a 405 response with the message - The requested resource does not support http method 'OPTIONS'). Pre-flights to the UserInfo and Token endpoints work as expected, so it doesn't seem like we have a general OPTIONS or CORS problem. 

Digging into the code a bit, it looks like only certain endpoints have CORS enabled via the CorsPaths constant, and the Revocation endpoint isn't one of them. Is this by design? If so, is it possible for a Javascript client using the Resource Owner flow to somehow revoke an access token on logout?

Many thanks in advance.

**Comment by brockallen** [comment]
Mind opening a new issue (since it feels like one) since this might be a fix need to track. Thx.
