### ISSUE TITLE
LoginPageLinks on a per Client basis

### ISSUE THREAD

**Issue by AnEmptyReece** [IdentityServer/IdentityServer3#1367]
I spoke to you at the SDD on Friday regarding the possibility of being able to have different login page links depending on the current client. For example, I have two client applications, but a registration link is only relevant to one.

Brock, you mentioned that something you have in the pipeline should make this possible, but to create a new issue as a reminder..... so here it is. Thanks!

**Comment by rdzidziguri** [comment]
I managed to implement exactly what you wrote using Custom view service and inside Login virtual method you can extract ClientId property from message parameter which is passed to this method. after you get client do what ever you want. particularly  model parameter has a property AdditionalLinks which you can populate based on client. that's all. It is very simple and because of perfect extensibility of Thinktecture Identity Server you can customize it in a lots of ways.

**Comment by AnEmptyReece** [comment]
Thanks. I have actually implemented it pretty much exactly as you describe. I just feel it would be quite a common scenario and was worth asking the question about it being made possible in a future release to configure them per-client out-of-the-box.

**Comment by JPBridges** [comment]
We have similar use cases and they are not restricted to login.  The ability to provide client specific content onto any view seems useful.
In our case we are required to present specific terms and conditions to a particular client on the consent page.

Ideally we'd be able to compose client specific pages from the view loader and cache them but that seems rather difficult at the moment.

**Comment by brockallen** [comment]
Yep, loud and clear.

**Comment by brockallen** [comment]
Ok, so I looked at how I'd do this and it basically means augmenting the DefaultViewService to do so. For now, I don't have a great motivation for this, given that it's easy enough for you to derive from the `DefaultViewService` (or create a custom view service) and modify the view model's links collection for rendering in the views. You can determine the client id via the `SignInMessage` param.

**Comment by AnEmptyReece** [comment]
Not a problem at all - I have a working solution and it seems others have done the same thing. Thanks for taking the time to look into it.

**Comment by iangriffin** [comment]
Old issue, but just to add my two cents, since I'm going through this now. I'm only looking at additional links based on the client - which is what two have commented they were attempting to do. The more advanced scenario of specific language per client seems like the case where a new IViewService needs to be created.

I agree that it's simple enough to handle the additional links manually via a custom ViewService, but I don't like the implementation. I need someplace to stick the "additional links per client", but since this is not part of the Clients, it is not part of the EF implementation of accessing Clients. Yes, I can roll my own, but I have to be mindful of not stepping on what the IdentityServer and EF extnsion projects are doing. I think having a list of "Additional Login Links" as a property of the Client would make sense - these things go together and changes to clients may require a change in the additional links per client.

Just throwing this out there to see what others thing about making "AdditionalLoginPageLinks" (or some name) a property of Client.

**Comment by AnEmptyReece** [comment]
I've found that as well as additional links I've had other things that I want to add/set on a per client basis, for example being able to disable (my own implementation of) 2FA in the IUserService. 

So I've created an ExtendedClientSettings model and associated EF entity/store etc to handle that. 

Then, as per Brock's suggestion above, I've derived from DefaultViewService in order to implement my custom functionality for the login page links.
