### ISSUE TITLE
Expose client properties to login view

### ISSUE THREAD

**Issue by gavinharriss** [IdentityServer/IdentityServer3#1385]
It would be handy to expose the client properties to the login screen as well as the consents view to identify the client being logged in to.

Particularly useful when Client.RequireConsent is set to false.

At least having these client properties available the pages modelJson will allow developers to utilize these if they need to.

**Comment by rdzidziguri** [comment]
Exposing Those properties is already possible if using IVIewService because in virtual Login method you can access client ID. after that just do whatever you want. query clientstore for additional info or modify model values which are passed to NG application on client side. We managed to get as far as we needed (showing custom Logo images for each client, displaying application title, showing custom user agreement etc ...)

**Comment by gavinharriss** [comment]
Thanks for that - still learning the product so was unaware that functionality could expose the client ID.

**Comment by leastprivilege** [comment]
close?
