### ISSUE TITLE
Too many OpenID.nonce cookies cause "Bad Request - Request Too Long" to appear after a while

### ISSUE THREAD

**Issue by hanswolff** [IdentityServer/IdentityServer3#1407]
![request_too_long](https://cloud.githubusercontent.com/assets/1478348/7859622/eb0e7e72-0542-11e5-93dc-efa61995e3de.png)

Steps to reproduce:

1.) 
Go to some page that has authorization required (get redirected to IdenityServer login screen)
Notice that an OpenId.nonce cookie ending with some random suffix is created in browser (so far so good)

2.) Use the browser button to go back

3.) Click again on a link that requires authorization (get redirected to login screen again)
Now an additional OpenId.nonce cookie is being created with different random suffix

4.) Do that 20-30 times until there are too many cookies for the domain and the request is being rejected with "Bad Request - Request Too Long"

The issue is not limited to the steps above. It is sufficient to abort the login process. The browser keeps collecting the OpenId.nonce cookies until it breaks at some point (see screenshot below)

![login_screen](https://cloud.githubusercontent.com/assets/1478348/7859621/e653bf50-0542-11e5-9ad9-20175c618618.png)

We are using the following setup:

- Thinktecture IdenityServer3 Version 1.6.1
- Internet Information Server 8.5
- tested with latest Firefox, latest Chrome and IE 11

IdentityServer somehow should check for old unused OpenID.nonce cookies and remove them when you get redirected to the login page. Of course I could implement some workaround myself but I think this should be fixed in IdentityServer since it is unexpected behavior and I am sure that other people are going to hit that issue as well.

**Comment by johnkors** [comment]
That's a Katana issue (especially the OIDC MW), I believe. Nothing to do with idsrv.

See also this : https://github.com/IdentityServer/IdentityServer3/issues/1124 for a purposed solution

**Comment by hanswolff** [comment]
Thanks for the quick reply!

**Comment by vladimirlapacek** [comment]
And https://github.com/aspnet/Security/issues/390

**Comment by rizamarhaban** [comment]
Okay, this is apparently an old issue. I have try all solution in here but still got the "```Bad Request - Request too long```" error. After doing some investigation, here is how to repeat this:

- [X] If in IIS I deploy to "**Default Web Site**" or I use "**Add Websites**" menu or using different binding Port on Default Web Site, then the issue is not exist, even using ```Microsoft.Owin.Security.OpenIdConnect v3.1.0``` which I use.

- [X] Now if, in IIS I created a **Virtual Directory** first pointing to a physical folder, copy the application to that folder, **Convert to Application**, than the issue appear. Here is the virtual path that I have tested to reproduce the issue:

        // Identity Server (Authority):
        http://localhost/STAGING/myids3

        // Web MVC client:
        http://localhost/STAGING/myapp

    Physical folder:

        // Identity Server:
        C:\Projects\STAGING\identityservice\

        // Web MVC:
        C:\Projects\STAGING\mywebapp\

Running '**myapp**' will redirect me to the '**myids3**'. Do Login and the error will appear.

If we use Port instead of Virtual Directory, will not generate the error:

        // Identity Server (Authority):
        http://localhost:5000/

        // Web MVC client:
        http://localhost:6000/

Anyway, this is my case and what happen to me. I experience this while trying to deploy the application to client machine and it starts showing that request too long error. When I deploy to IIS (_similar environment as my client_) the issue also appears. Been downgrading the ```Microsoft.Owin.Security.OpenIdConnect``` to 3.0.0, the issue also the same and it loop with the title "Submit this form" on browser.

All of my deployment test is using "**Add Websites**" in IIS and nothing wrong. However the problem is, my client server environment not allowing me to use "**Add Websites**", instead, they just give the Virtual Directory physical folder.

Anyone can help on this...?
