### ISSUE TITLE
Usage in NodeJS applications?

### ISSUE THREAD

**Issue by danielbsig** [IdentityServer/IdentityServer3#1424]
Hi,

I'm aware that both this community is more .NET oriented, but does anyone know of an example how to validate JWT tokens issued by IdentityServer in a Node.js Web API? Using Express and Passport seems to be what people are using in general, but any help with the configuration would be highly appreciated.

Regards,
Daníel

**Comment by johnkors** [comment]
http://jwt.io (from Auth0) lists this npm module at least. https://github.com/auth0/node-jsonwebtoken

I haven't found a passport module that even uses googles openid connect provider, only OAuth2 plugins. Do tell about it if you find one - it's been a while since I checked.

Also, imo passport is more of an attempt to normalize all things that are wrong with using OAuth2 as a authentication mechanism.

**Comment by brockallen** [comment]
I have been working on this library: https://github.com/IdentityModel/oidc-client

I just opened an issue yesterday to re-write it in TS so I can try to provide both nmp and require modules.

**Comment by danielbsig** [comment]
I stumbled upon this: https://github.com/anvilresearch/connect-nodejs - haven't tried it myself. Seems to be written with another identity provider in mind, but I'm hoping it shouldn't be too much of an issue (assuming standards are being followed!)

**Comment by trbngr** [comment]
Hey all. I've solved this with a few packages.

1. express-session
2. passport-openidconnect

you'll need to clone passport-openidconnect and update the dependencies to use it with newer versions of passport.

Other than that, this works perfectly (for me)

https://gist.github.com/anonymous/28d85997342c2894d647
