### ISSUE TITLE
External Provider registration per tenant

### ISSUE THREAD

**Issue by paddyhamilton** [IdentityServer/IdentityServer3#1439]
I am currently looking at configuring IDS so that when a user logs in from the client application the login page on IDS shows only the providers that are configured in a database for that tenant.

The approach that I can see working is to register all providers for all clients in the StartUp of IDS and then create a customView Service that will filter out the ones I need to show for that tenant on the Login method.
Is there a better approach than this as this seems a bit of a hack?
Cheers

**Comment by depl0y** [comment]
Such a coincidence, I am currently looking for the same thing.

I want to exclude certain external login providers for users coming with a certain client ID.

I was looking around and maybe the `IUserService.PreAuthenticateAsync` method could do anything here?

**Comment by paddyhamilton** [comment]
I think that may be too late in the pipeline but I may be wrong.  You don't have access to the providers at that stage where as in the customView Login you know at that point which providers are registered and you can filter them.

**Comment by brockallen** [comment]
The `Client` configuration has a `IdentityProviderRestrictions` collection where you can indicate which of those providers are allowed.

https://identityserver.github.io/Documentation/docs/configuration/clients.html

**Comment by paddyhamilton** [comment]
Thanks Brock, I should have explained the scenario in more detail.  We have a multi tenanted site so therefore there is 1 client so I cant restrict the identity providers there as they are restricted by tenant and not client.  
Is this possible to do?

**Comment by brockallen** [comment]
You'd have to create a custom view service (or derive from the `DefaultViewService`) and override `Login` and filter the allowed IdPs. See the `DefaultViewService` implementation.

**Comment by paddyhamilton** [comment]
Thanks Brock, that's what I thought.  The only issue that leaves me is that when a new provider is registered I would need to restart the IDS.  I ideally want tenants to be able to register their own ADFS instances and the IDS automatically get them from a database.
Again, are there any hooks we can leverage to register new providers without having to restart the IDS instance?

**Comment by brockallen** [comment]
You'd need to "reboot" the OWIN pipeline. It's not hard, you just need to code for it -- @damianh has some approaches, but I don't have the links offhand.

**Comment by damianh** [comment]
Yeah I do this. Just rebuild the appfunc/middleware on configuration change and swap it out. I'll blog about it coming weeks. Hint, you can instantiate your own AppBuilder instance.

**Comment by paddyhamilton** [comment]
Guys, thanks for the info.  @damianh I will give it a go and see how I get on.
Again, Brock, Damian, thanks for the help.

**Comment by marc-mueller** [comment]
Hi @paddyhamilton 

We are currently working on a very similar solution, to have a per tenant configuration which is stored in the database and can be altered at runtime. Is there any sample available for rebuilding the middleware during runtime?

Thanks!
Marc

**Comment by paddyhamilton** [comment]
Hi @marc-mueller , 

I have written code which does this, but I haven't had chance to test it properly yet.
Once I have tested it and make sure it works ill send you over the code.

Cheers

**Comment by powelmaja** [comment]
Hi!
We are having a similar problem at the moment. We are using the IdSrv3 as an STS gateway for multiple tenants. Each tenant has it's own WsFederation Identity Provider. Configurations for Identiy Providers are stored in the database, and they are fetched during application Startup, to build the middleware pipeline. But there are going to be new configurations added for upcoming tenants. And we wouldn't like to restart the application each time - especially when the IdSrv3 is hosted on Azure where the restarting process takes some significant time.
My thought was to create a handler (OWIN Map), which would be called after the configuration has been changed. This handler would then rebuild the pipeline and swap the previous one with it. But I must say I'm stuck now. I instantiated new AppBuilder object, ran the Startup.Configuration against it, built the AppFunc object, but I don't know how to put it in the OwinContext.
@damianh - is my way of thinking correct?

Thank you in advance!

**Comment by damianh** [comment]
@paddyhamilton @marc-mueller @powelmaja [Here is an example of a pipeline dynamically rebuilds it's self based on configuration change](https://github.com/damianh/DynamicKatanaPipeline). It's important to remember that you are [in charge of the path a request travels along](https://github.com/damianh/DynamicKatanaPipeline/blob/master/src/DynamicKatanaPipeline/DynamicKatanaMiddleware.cs#L34). That is, you control the middleware, what is inside it. [You can rebuild what paths can be taken](https://github.com/damianh/DynamicKatanaPipeline/blob/master/src/DynamicKatanaPipeline/DynamicKatanaMiddleware.cs#L37). Here, I am adding multiple 'UseDirectoryBrowser' based on lines in a config file.

We do similar with IdSrv, though there are more settings, it's pretty much the same thing.

**Comment by powelmaja** [comment]
Thanks a lot @damianh - great example! I haven't thought about making a self-rebuilding middleware. I will give it a try!

**Comment by Peperud** [comment]
@damianh What happens with the requests already in the pipeline while it is getting rebuilt?

**Comment by brockallen** [comment]
They'd finish normally.

**Comment by damianh** [comment]
Yes, under vast majority of conditions they will finish normally.

The only thing to perhaps be wary of is:
 A) If you need to dispose of anything that exists in the 'old' pipeline
 B) If you can't have a rebuilt pipeline using resources the first pipeline may be holding on to (a shared resource, such as a file)

If you just have to deal with A) and it's not frequent, then occasionally a user will get a 500 when you dispose of something mid-request. If this is ok, then just dispose and swap the internal appfunc (`_dynamicAppFunc` in my example) as usual.

If this is not suitable a possible clean way of handling is to:
1. Reference count the requests for pipeline P0
2. Rebuild pipeline, P1 so subsequent requests go down it. There is a window here where requests are being handled by pipeline P0 and P1
3. When request count hits zero for P0 (aka "drained"), dispose resources related to it.
4. Repeat for P2, P3 etc.

If you need to deal with B), that is you can't never two or more pipelines handling requests _concurrently_ due to a shared resource. Then:
1. Reference count the requests for pipeline P0
2. Start returning `503 Service Unavailable`
3. When request count hits zero for P0 (aka "drained"), dispose resources related to it. 
4. Rebuild pipeline, P1 so subsequent requests go down it. There is a window here where requests are being handled by pipeline P0 and P1
5. Stop returning 503.
6. Repeat for P2, P3 etc.

I'll expand my example to include these.

Personally, I'd avoid getting into a situation where B) could occur if at all possible.
