### ISSUE TITLE
Browser hangs on redirecting to external identity provider

### ISSUE THREAD

**Issue by hmaland** [IdentityServer/IdentityServer3#1466]
Our IdentityServer3 host is working as an OIDC STS gateway for multiple tenants. Each tenant has its own OIDC Implicit Flow client and its own Azure AD configured as a WsFederation external Identity Provider. Local login is disabled, so during login process, the user is immediately redirected to the Azure AD. 

We have been struggling for quite some time with a hang situation that happens occasionally: 
When users in "Tenant 1" navigates to the main page of the app, e.g. https://mysite.net/tenant1, the browser is not redirected to the configured external idp login page (Azure AD / https://login.microsoftonline.com). The browser just hangs for several minutes. While the hang situation occurs, users in "Tenant 2" is still promptly being redirected to the Azure AD login page.
The only way we have found to get rid of the hang situation is to restart the IdentityServer3 host. 

We have enabled diagnostic logs to try and see where the server hangs. The last log statement from Thinktecture.IdentityServer.Core.Endpoints.AuthenticationController is “Triggering challenge for external identity provider” 

```c#
Logger.Info("Triggering challenge for external identity provider"); 

// add the id to the dictionary so we can recall the cookie id on the callback 
authProp.Dictionary.Add(Constants.Authentication.SigninId, signin); 
authProp.Dictionary.Add(Constants.Authentication.KatanaAuthenticationType, provider); 
context.Authentication.Challenge(authProp, provider); 

return Unauthorized(); 
} 
```

We are using the latest stable nuget packages Thinktecture.IdentityServer3 1.6.1 and Microsoft.Owin.* 3.0.1

Any ideas on what could cause the hang?

**Comment by brockallen** [comment]
Possibly related? https://katanaproject.codeplex.com/workitem/409

**Comment by hmaland** [comment]
That could related. We will try to the approach of creating ConfigurationManager manually and see if it helps.

**Comment by cbomkamp** [comment]
Sorry, I know this is closed, but I thought I'd add my experience to this and a possible solution for anyone else having a similar problem.

On my local dev machine, if I restarted IIS Express after logging in with an external provider (ADFS), then it would hang when logging out.  After updating Microsoft.IdentityModel.Protocol.Extensions to 1.0.2.202250711 (released 6/23/2015), that problem disappeared.

**Comment by philpowers** [comment]
I encountered this as well, and FYI in my case the problem SEEMS to have been related to the fact that the external provider (ADFS in my case) wasn't resolving correctly on the IdSrv SERVER machine, even though the ADFS server was resolving correctly on the client/browser side. Something to check out in case someone else runs into this.

**Comment by johanfeuk** [comment]
We had problems just as described in the title. After IIS application pool had shutdown due to inactivity or recycle, IdSrv had no information about the IdP (ADFS 3 in this case) and at the same time a logged in user made an Sign-out. The redirection and the fetching of Federation metadata document hang/deadlocked. @brockallen mentioned this https://katanaproject.codeplex.com/workitem/409 as the underlying problem  earlier and @leastprivilege informed us about an extension for IdSrv addressing this problem here: 

Extension:
https://github.com/IdentityServer/IdentityServer3/blob/master/source/Host.Configuration/Extensions/SyncConfigurationManager.cs
 
Usage:
https://github.com/IdentityServer/IdentityServer3/blob/master/source/Host.Configuration/IdentityServerExtension.cs#L128
