### ISSUE TITLE
"sub" claim doesn't match what external identity provider supplies

### ISSUE THREAD

**Issue by ravisakaria** [IdentityServer/IdentityServer3#1477]
I followed the guide located at http://identityserver.github.io/Documentation/docs/overview/mvcGettingStarted.html and login is working properly.  When I login using Google, however, I don't understand why the `sub` claim doesn't match the one provided by Google.  Also, every time I restart my project, I get a different `sub`.  I suspect this is because I'm using the in-memory factory, but I'm not clear on why that matters.  I expected the `sub` claim to be passed through from the IdP.  

Hopefully someone can help clarify what I'm missing here.  Thanks in advance.

**Comment by leastprivilege** [comment]
Typically your apps don’t want to directly rely on external subs - that’s why the in-mem implementation translates the external sub to an internal one. If you don’t like that - you can implement it differently in your user service.

— 
cheers
Dominick Baier


On 11 Jun 2015 at 07:32:29, Ravi Sakaria (notifications@github.com) wrote:

I followed the guide located at http://identityserver.github.io/Documentation/docs/overview/mvcGettingStarted.html and login is working properly. When I login using Google, however, I don't understand why the sub claim doesn't match the one provided by Google. Also, every time I restart my project, I get a different sub. I suspect this is because I'm using the in-memory factory, but I'm not clear on why that matters. I expected the sub claim to be passed through from the IdP.

Hopefully someone can help clarify what I'm missing here. Thanks in advance.

**Comment by ravisakaria** [comment]
Thanks for clarifying that Dominick.
