### ISSUE TITLE
URL Rewrite for subdomain fails

### ISSUE THREAD

**Issue by anthonyresq** [IdentityServer/IdentityServer3#1531]
We have a wild card domain hosted on azure. I've setup up subdomain.domain.com to rewrite to domain.com/subdomain. It all works fine.

However when I login to our identity server, once the login process is completed and I am redirected back to subdomain.domain.com it seems like the authentication token is lost.
i.e. subdomain.domain.com thinks that I'm logged out, but when I click on the login link, I am taken to the IdentityServer3 site, which sees that I'm logged in, and redirects me back to subdomain.domain.com which still thinks I'm not logged in.

I can't see how this can be possible. This issue happens with all our identity providers (google, Facebook, Microsoft live)

If I change the setup to redirect to domain.com/subdomain then everything works as expected

**Comment by loctanvo** [comment]
A typical login flow is like the following:

1. The user accesses `subdomain.domain.com`
2. He/she then is redirected to `idserver` and logs in
3. He/she then gets redirected back to `subdomain.domain.com` with an **id token**
4. `subdomain.domain.com` accepts the **id token**, transforms the claims and issues a cookie. From now on, the user is authenticated on `subdomain.domain.com` as long as the cookie is still valid.

In your case, I think step 4 is changed. Instead of processing the **id token** right away, the user is redirected to `domain.com/subdomain`. In this redirect, the **id token** is not preserved, and does not get submitted to `domain.com/subdomain`. Hence, no cookie is issued. Just wild guessing.

**Comment by brockallen** [comment]
Monitor the HTTP traffic to ensure the expected cookies are being sent to the right place.

**Comment by brockallen** [comment]
Any update?
