### ISSUE TITLE
How to call webapi that are there in the Idsrv3

### ISSUE THREAD

**Issue by RajMondaz** [IdentityServer/IdentityServer3#1544]
i have created some web api in Idrsrv3 , i have to acces that api from webclient from other application normally it is working but i have to call using idsrv tokens

**Comment by loctanvo** [comment]
Sorry, but you need to elaborate more on your setup and what your issue is. What exactly do you need help with? Securing or calling the API?

**Comment by RajMondaz** [comment]
Need a help on Securing  Api ?

**Comment by loctanvo** [comment]
Have you read **Part 2** from [the getting started guide](http://identityserver.github.io/Documentation/docs/overview/mvcGettingStarted.html)? Otherwise, there is also a [web api sample](https://github.com/IdentityServer/IdentityServer3.Samples/tree/master/source/Clients/SampleAspNetWebApi) in case you haven't seen it.
