### ISSUE TITLE
Exception Handling scenario 

### ISSUE THREAD

**Issue by TD49** [IdentityServer/IdentityServer3#1601]
In reference to https://github.com/IdentityServer/IdentityServer3/issues/355, here's  an example scenario we're dealing with in our IdSvr3 implementation:

Using a loose Circuit Breaker pattern, when certain SQLExceptions or NetworkExceptions exceed a  tolerance level  (e.g. ```IUserService``` can't hit an auth source or ```IClientStore``` can't connect to its SQL repository due to unepxected downtime), we block further attempts to connect to those resources for a period of time.   In that scenario, with the Token endpoint, we'd like to respond to the client with a "503 Retry-After" and possibly change the response body to something static or descriptive.   

So, having a way to implement a custom ```IExceptionHandler``` would be helpful.

(This would also apply to any unhandled exceptions, since IdSvr doesn't appear implement its own ```IExceptionHandler```?)

**Comment by TD49** [comment]
Alternatively, if we can't implement a custom ```IExceptionHandler``` at your web api layer, what about the IdSvr3 OWIN component signaling its CancellationToken and sending a true exception instead of a completed Task?   That way we could intercept and change the response body with a custom OWIN component that precedes IdSvr3 in the pipeline...

**Comment by TD49** [comment]
In considering a PR, I looked at two ways to do this:  

1.  Exposing an ```IExceptionHandler``` property as an option in ```IdentityServerOptions```, then having IdSvr3 add the type to the internalized HttpConfiguration services 
2.  Finding a way to register the ```IExceptionHandler``` type and have IdSvr3 resolve it internally by adding it to the internalized ```HttpConfiguration``` service container.

With the first way, I had problems with accessibility issues with this interface between the host and the IdSvr middleware.  Also, I prefer DI instead of explicitly instantiating a specific ```IExceptionHandler``` type into the options.  

The second way can't be done with IdSvr's internalized AutoFac... unless you can register the ```IExceptionHandler``` as an "additional dependency" through the ```IdentityServerServiceFactory```  and find a way to have IdSvr3 to resolve the type and add it to ```HttpConfiguration``` service container internally.  This seemed more like a workaround to me, if I could get it to work.

Any other ideas?

**Comment by brockallen** [comment]
We'll discuss this week. // @leastprivilege

**Comment by brockallen** [comment]
Oh question tho -- You'd want to issue a 503 on the token endpoint, of course, but also the authorize endpoint (and other UI endpoints)?

**Comment by TD49** [comment]
Potentially, yes.

**Comment by leastprivilege** [comment]
We will have a look for 2.1 - 2.0 is locked down now.

**Comment by leastprivilege** [comment]
we should discuss.

**Comment by TD49** [comment]
Sounds good.   I'll be out of pocket for a few days, back by Monday morning (US time).

**Comment by TD49** [comment]
To continue using IdSvr3 and handle exceptions requiring a specific response code, we modified IdSvr3 2.0's source code locally by registering a custom ```ExceptionFilterAttribute``` in the internalized WebApi.  This filter forces a 503 response depending on the exception type and certain event identifiers captured by our implementation (e.g. loss of network or sql exceptions to our SQL persistence store).   Otherwise, for all other exceptions and errors, it passes through the default WebApi response (e.g. "error has occurred").

I have no plans to push or merge those changes to github or even my own fork... it's a temporary workaround to meet our specific implementation's requirements for now.

The 503-response is just an example.  We'd like a more open architecture to override the default responses for endpoints.   Depends on if you're continuing with full ASP.NET Web API internalized model, or if there will be a way to intercept a response within an OWIN pipeline in the future?

**Comment by leastprivilege** [comment]
So even if you could plugin your own exception filter (let’s say this would work somehow) - you’d need much more insight into various places in the pipeline to come to the conclusion of emitting a 503…?

— 
cheers
Dominick Baier


On 14 Sep 2015 at 17:00:36, Toby Davis (notifications@github.com) wrote:

To continue using IdSvr3 and handle exceptions requiring a specific response code, we modified IdSvr3 2.0's source code locally by registering a custom ExceptionFilterAttribute in the internalized WebApi. This filter forces a 503 response depending on the exception type and certain event identifiers captured by our implementation (e.g. loss of network or sql exceptions to our SQL persistence store). Otherwise, for all other exceptions and errors, it passes through the default WebApi response (e.g. "error has occurred").

I have no plans to push or merge those changes to github or even my own fork... it's a temporary workaround to meet our specific implementation's requirements for now.

The 503-response is just an example. We'd like a more open architecture to override the default responses for endpoints. Depends on if you're continuing with full ASP.NET Web API internalized model, or if there will be a way to intercept a response within an OWIN pipeline in the future?

**Comment by TD49** [comment]
Support for plugging in a custom exception filter should work, in the interest of making the 2.1 deadline.   If it can be done, would you register the filter globally for all controllers?   Or allow a custom implementation to choose specific endpoints (more complicated, unsure how to simplify that)?

**Comment by leastprivilege** [comment]
Well - maybe it is easier you send me a PR - that discusses the implementation and needed features.

**Comment by TD49** [comment]
My current workaround is a hardcoded exception filter (containing our product-specific logic) added directly into your source code... it's not the solution we'd want for IdSvr3 in general.   

I had a potential PR that "injected" the custom filter through IdentityServerOptions, but it failed at runtime for the same reasons that the global exception handler failed per my earlier comments on July 10.   That's where I got stuck.

**Comment by leastprivilege** [comment]
Since we would have to wrap the exception filter - I am trying to understand what kind of functionality you would need inside of it.

**Comment by leastprivilege** [comment]
If you don't more info for me - I will close this.

**Comment by TD49** [comment]
Apologies, I've been delayed working on a separate issue.

The point of my original request was an ability to allow an implementer such as ourselves to customize an error response, not to add our business-case-specific 503 logic directly into IdSvr3 base code.  We were hoping to find a way to plug in an exception filter or some other means to do this.   Are you asking for a PR that executes our specific 503 logic/business case inside your base code?

**Comment by pbartos** [comment]
Hi, I have simmilar scenario.

We have a too many clients with different styles and languages so I'm not able to create custom error page for each client on IdS. Idea is show error page on client when IdS returns error. 
So I would like to use TD49 idea with IExceptionHandler or is there any option to send error (500) result to the client instead of show Error page on Identity server?

**Comment by leastprivilege** [comment]
Would that be sufficient:

* on unhandled exceptions we hand you the exception
* you can set the response status code, content (if any) and content type

??

**Comment by pbartos** [comment]
Sound good for me.

**Comment by TD49** [comment]
Yes, that can work

**Comment by leastprivilege** [comment]
please review the feature set - and comment on it here:

#2012

closing this one.
