### ISSUE TITLE
Missing "no" answer on the logout prompt page.

### ISSUE THREAD

**Issue by vladimirlapacek** [IdentityServer/IdentityServer3#1650]
There is currently no "no" answer on the default logout prompt page. I wonder if that is by design or just incomplete implementation. I realise that the prompt is mitigating "logout spam". My concern is that users might get find it funny that they only have one option.

I can clearly create a partial _logout.html view with the "no" button, but than it's little tricky to do something about it. Has anyone been through this already?

**Comment by brockallen** [comment]
The "no" option is to close the browser or hit the back button. It's a browser, not a desktop app.

**Comment by vladimirlapacek** [comment]
I see what you are saying and understand it from the technical perspective. Still, I suppose that some users may not like the only visible choice to be "yes". This question was reported to me by our QA, which represents the users to me.

In any case, thanks for your prompt response!

**Comment by brockallen** [comment]
You realize that If the client passes a id_token and post_logout_redirect_uri then there is no prompt? This might be your answer. But if it's not, some more thoughts:

If the client has not passed an id_token then there is a prompt. Since there's no id_token, there's no real guarantee of who made the request. So a "no" button should not redirect back to the client as that's potentially an open redirect attack. There's nothing in the OIDC spec that provides guidance here and perhaps because it's a hard problem to solve.

You can always customize the views and add one. I just would be unclear as a user what it means. Does it means end there, or go back? What would you expect to happen? Again, I'd be careful of redirecting back to a client that's not verified in some way.

**Comment by vladimirlapacek** [comment]
I actually did not realise the no prompt option. It now makes perfect sense. Thanks again for the explanation.
