### ISSUE TITLE
Silent Sign-In - Signing in without the user knowing

### ISSUE THREAD

**Issue by BroccoliProducts** [IdentityServer/IdentityServer3#1693]
When we were using .Net Identity, every user on our MVC website was signed in.  We did this by creating a user account for them with a random username, and then signing them in with a call to AuthenticationManager.SignIn(user).  The user never knew any of this.

Now we have an IS3 server in Azure.  We can create random user accounts by calling a WebApi function on our IS3 server.  This returns the details of the new user account.  We know the user’s username and password.

But how do we sign the new user account in without the user knowing?

**Comment by brockallen** [comment]
Have your API return the info for the user and use that to issue your cookie. IdentityServer implements the OIDC protocol and the protocol isn't designed for logging a user in without credentials and without them knowing. Hopefully you have a good reason to do what you're doing, because it makes little sense to me. Perhaps I'm missing some larger context.
