### ISSUE TITLE
[Question] How to generate token responses without calling the connect API

### ISSUE THREAD

**Issue by neilcrowther** [IdentityServer/IdentityServer3#1700]
As part of a partial login flow, I need to call an external API that is secured by identity server (to get "extra" information on the user that the UserService does not have access to).  I could call the identity server connect endpoint using client credentials to generate a token to pass to the external API, but that seems a messy/terrible/hacky idea.  Is there any clean way to generate a response token from within the identity server site without calling the endpoints?  My partial login flow is all hosted in the same site as identity server, so I have access to all the identity server classes/stores etc.

**Comment by brockallen** [comment]
So you should be able to inject the classes that create the token into your user service ctor.

**Comment by neilcrowther** [comment]
If I inject that into the user service I get IOC errors with it failing due to circular dependencies.  I'll have another attempt tomorrow to try moving the code to the controller I'm using for the partial login process instead (and make sure all the child dependencies are registered there as well).  Thanks for the prompt response.

**Comment by brockallen** [comment]
Oh, it might need the user service.... ick.

**Comment by ayoung** [comment]
I did this once as an exercise to prove that it was possible. Unfortunately, its not that easy because some of the classes/dependencies are marked `internal` and not able to be registered with your own DI container.

The following are internal classes to IDS that you'll need to pull into your project (copied from source).

* `StringExtensions`
* `AuthorizeRequestValidator`
* `AuthorizeRequestValidationResult`
* `ValidationResultBase`

You essentially need to inject the following into wherever your external API's controller: `ITokenService`, `IUserService`, `AuthorizeRequestValidator`. You need `ITokenService` to create the id_token and access_token. You need `AuthorizeRequestValidator` to validate the user as well as to get the requested scopes to include in the tokens. You'll need `IUserService` to authenticate the user to pass to `AuthorizeRequestValidator.ValidateAsync()`. I guess you don't really need that last bit if you just assume the user is validated.

If you want the code that pulls all this together, let me know.

**Comment by neilcrowther** [comment]
Ok, "ick", as Brock says...  I'd prefer not to do this using copies of internal classes (in case they change).  I'm going to step back and see if there is another way to accomplish what I need to do without calling the API before taking this any further.  I don't suppose its any different creating a token for a client credential flow?  I don't need to be using the signed in user in the API call, so client credentials would be fine.

**Comment by brockallen** [comment]
So yea, maybe the ick approach is to make http requests to yourself. That'd be unfortunate, but might just be the first stab at doing this. :/

**Comment by shahzadfaisal** [comment]
@ayoung  i realy need your code you that have for creating id_toke and access_token.
