### ISSUE TITLE
CookieOptions - ExpireTimeSpan and RememberMeDuration

### ISSUE THREAD

**Issue by vladimirlapacek** [IdentityServer/IdentityServer3#1770]
Hi,

Can you please confirm whether these two settings have an overlapping semantics? Essentially, if only IsPersistent is active, ExpireTimeSpan drives the cookie expiration, while if Remember Me is enabled, the value gets overridden by RememberMeDuration?

There may be a bug in the later case if you enable SlidingExpiration as well. I have seen the idsrv cookie expiration extended based on the sliding rules, but the idsrv.session cookie stayed unchanged (used original expiration time). What is the purpose of the idsrv.session cookie anyway? Cannot IS3 use just idsrv?

Finally, is there a way to use SlidingExpiration, but define a hard limit beyond which the sliding cannot go?

Thanks,
Vlad

**Comment by brockallen** [comment]
> Essentially, if only IsPersistent is active, ExpireTimeSpan drives the cookie expiration, while if Remember Me is enabled, the value gets overridden by RememberMeDuration?

Yes, that seems right. Since the user can click the "remember me" we needed a different configuration value for when the cookie was persistent.

> What is the purpose of the idsrv.session cookie anyway?

The idsrv.session is for the OIDC session management spec. It changes if the user changes their login state (logout or user changes).

> Finally, is there a way to use SlidingExpiration, but define a hard limit beyond which the sliding cannot go?

No -- we essentially rely upon the Microsoft cookie authentication middleware and they don't support that.
