### ISSUE TITLE
Encode User Claims in Access Token

### ISSUE THREAD

**Issue by tjoudeh** [IdentityServer/IdentityServer3#1804]
I'm trying to include custom claims for an authenticated user, what I'm trying to achieve is the following: 
I have created a custom user service which implements **IUserService** as the code below:
```
public Task<AuthenticateResult> AuthenticateLocalAsync(string username, string password, SignInMessage message)
        {
            using (var client = new Corp.Core.CoreClient<Corp.DotCom.Contracts.IPortalService>(typeof(Corp.DotCom.Contracts.IPortalService).FullName))
            {
                UserClass userClass = client.Instance.Login(username, password, "");

                if (userClass == null)
                {
                    return Task.FromResult<AuthenticateResult>(null);
                }

                List<Claim> claims = new List<Claim>();
                claims.Add(new Claim("userId", userClass.GUID.ToString()));
                claims.Add(new Claim("country_code", userClass.CountryCode));

                return Task.FromResult<AuthenticateResult>(new AuthenticateResult(userClass.Email, userClass.FirstName, claims));
            }

        }

        public Task<IEnumerable<System.Security.Claims.Claim>> GetProfileDataAsync(ClaimsPrincipal subject, IEnumerable<string> requestedClaimTypes = null)
        {
            using (var client = new Corp.Core.CoreClient<Corp.DotCom.Contracts.IPortalService>(typeof(Corp.DotCom.Contracts.IPortalService).FullName))
            {
                UserClass userClass = client.Instance.GetUserClass(subject.GetSubjectId());
              
                if (userClass == null)
                    return Task.FromResult<IEnumerable<Claim>>(null);

                List<Claim> claims = new List<Claim>();
                claims.Add(new Claim("userId", userClass.GUID.ToString()));
                claims.Add(new Claim("country_code", userClass.CountryCode));
                claims.Add(new Claim("sub", userClass.Email));

                if (requestedClaimTypes == null)
                {
                    return Task.FromResult(claims.AsEnumerable());
                }

                return Task.FromResult(claims.Where(o => requestedClaimTypes.Contains(o.Type)));
            }
          
        }
```
Now the scopes I request in my test client as the following: **"openid profile read write offline_access"**

The database changes I have made as the following:

* Added 2 new ScopeClaims named "userId" and "country_code" under the scope "profile" and set the  value for "AlwaysIncludeInIdToken" to "true". *This helped in having those claims in the Identity Token not Access Token*
* In table "Scopes", I have set the value for "IncludeAllClaimsForUser" to "true", this has no affect in sending new claims in the access token. (*I thought this will solve the issue :(*)

I'm not sure If I'm missing something here, I though this would be a very straight forward to implement, 

Any suggestions will be appreciated.

**Comment by leastprivilege** [comment]
..and what's the issue?

Have you set a breakpoint to see which claims are actually requested (and if they are returned) ?

**Comment by tjoudeh** [comment]
Hi Dom
Once I set break point in method "GetProfileDataAsync", the parameter "requestedClaimTypes" is set to 3 claims "sub, country_code, userId", and those claims are returned in the Identity Token, not the access token.
Once I set the flag "IncludeAllClaimsForUser" for the scope "profile", the value of the "requestedClaimTypes" is set to null, but as you noticed in my implementation I'm returning all the claims if the requestedClaimTypes is null. (Not sure if this is a bug)

Below is and example for an Identity Token and Access Token, sorry for pasting those large tokens here, but it might help:
**Identity Token**
```
eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsIng1dCI6ImEzck1VZ01Gdjl0UGNsTGE2eUYzekFrZnF1RSIsImtpZCI6ImEzck1VZ01Gdjl0UGNsTGE2eUYzekFrZnF1RSJ9.eyJub25jZSI6ImFkOWVjMDA1ZDBhMDRjODhiYTZkNDI4NjdjYzdiM2Q5IiwiaWF0IjoxNDQxMDEwNDUwLCJzdWIiOiJUYWlzZWVyLkpvdWRlaEBhcmFtZXguY29tIiwiYW1yIjoicGFzc3dvcmQiLCJhdXRoX3RpbWUiOjE0NDEwMTA0MzcsImlkcCI6Imlkc3J2IiwidXNlcklkIjoiNDhlMzIxNDQtODllOS00YmE1LWJjZWItNGNkYjkxYzRlZjgyIiwiY291bnRyeV9jb2RlIjoiSk8iLCJpc3MiOiJodHRwczovL2xvY2FsaG9zdDo0NDMwMy9jb3JlIiwiYXVkIjoiY29kZWNsaWVudCIsImV4cCI6MTQ0MTAxMjI1OCwibmJmIjoxNDQxMDEwNDU4fQ.ltbz_CYRV0axNOtp33T62PytysW3sD3Cc96kg1Qq_6_22r4NWvoch4_K7_EEev6cymsfxC2hwGdHW8nplxObMIJGKzEdD3Tp5N0wpNS0BiVI7Ez_lLOx_YXisIVgDTG7QG4RBi7um9qR1sCi39iHt0dAw6uWIZTjcDF_0Bs_85DRXwM0RvIjOFNTFfB5wQ4vpCE-o9pRtfyAI4kIeKfCP-uc9oXOX0UIHiRl6t1FeOHZPpgcT8qhw1rq3f6RuycFhLRADvd-7YUdadLd_j3wR8obRlkXWI3L-IUFoUwXxxxY7kz9hTJqrGizW8hsYXyRP_lwkwfN0-pH-NvjsS5WTA
```
**Access Token**
```
eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsIng1dCI6ImEzck1VZ01Gdjl0UGNsTGE2eUYzekFrZnF1RSIsImtpZCI6ImEzck1VZ01Gdjl0UGNsTGE2eUYzekFrZnF1RSJ9.eyJjbGllbnRfaWQiOiJjb2RlY2xpZW50Iiwic2NvcGUiOlsib3BlbmlkIiwicHJvZmlsZSIsInJlYWQiLCJ3cml0ZSIsIm9mZmxpbmVfYWNjZXNzIl0sInN1YiI6IlRhaXNlZXIuSm91ZGVoQGFyYW1leC5jb20iLCJhbXIiOiJwYXNzd29yZCIsImF1dGhfdGltZSI6MTQ0MTAxMDQzNywiaWRwIjoiaWRzcnYiLCJpc3MiOiJodHRwczovL2xvY2FsaG9zdDo0NDMwMy9jb3JlIiwiYXVkIjoiaHR0cHM6Ly9sb2NhbGhvc3Q6NDQzMDMvY29yZS9yZXNvdXJjZXMiLCJleHAiOjE0NDEwMTIyNTAsIm5iZiI6MTQ0MTAxMDQ1MH0.JvvJ64AI3QkzT7u2Ts4Hdzz7q04euOAFYGGO_RH7M04CpBxSJVEGAqUaxb7qKHhXFZ-Z4-5Q6VHe0WFDZgLJ_-fYEZ0zMnI1zDchao2wENPcx_KdWL2d89PyMqzeNfwt5p_Jd2qzbTaDNhHYAzD2YZ8rytw8_QKECuuIxIpogC_8XjSA9oSrCoSLIlosqvPXN5nLQdn37EHWN3OnKkxnruxzV6iBgN5SfJnKAgCV1WLW6qL8FHYeJ1DGfogPYuVzHrylTTIru_XJaamvg-6tTTx33KHLJqjHZWUdqxFYNl9L_hy0HP_w1X-6j3ml6WMEJNC1IZUOe_K6lakh3VqwOg
```

**Comment by leastprivilege** [comment]
there are no bugs ;)

so I still don’t get what your issue is? do you also want to return the claims in the access token (in addition to the identity token) ?

— 
cheers
Dominick Baier


On 31 Aug 2015 at 11:35:38, Taiseer Joudeh (notifications@github.com) wrote:

Hi Dom
Once I set break point in method "GetProfileDataAsync", the parameter "requestedClaimTypes" is set to 3 claims "sub, country_code, userId", and those claims are returned in the Identity Token, not the access token.
Once I set the flag "IncludeAllClaimsForUser" for the scope "profile", the value of the "requestedClaimTypes" is set to null, but as you noticed in my implementation I'm returning all the claims if the requestedClaimTypes is null. (Not sure if this is a bug)

Below is and example for an Identity Token and Access Token, sorry for pasting those large tokens here, but it might help:
Identity Token

eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsIng1dCI6ImEzck1VZ01Gdjl0UGNsTGE2eUYzekFrZnF1RSIsImtpZCI6ImEzck1VZ01Gdjl0UGNsTGE2eUYzekFrZnF1RSJ9.eyJub25jZSI6ImFkOWVjMDA1ZDBhMDRjODhiYTZkNDI4NjdjYzdiM2Q5IiwiaWF0IjoxNDQxMDEwNDUwLCJzdWIiOiJUYWlzZWVyLkpvdWRlaEBhcmFtZXguY29tIiwiYW1yIjoicGFzc3dvcmQiLCJhdXRoX3RpbWUiOjE0NDEwMTA0MzcsImlkcCI6Imlkc3J2IiwidXNlcklkIjoiNDhlMzIxNDQtODllOS00YmE1LWJjZWItNGNkYjkxYzRlZjgyIiwiY291bnRyeV9jb2RlIjoiSk8iLCJpc3MiOiJodHRwczovL2xvY2FsaG9zdDo0NDMwMy9jb3JlIiwiYXVkIjoiY29kZWNsaWVudCIsImV4cCI6MTQ0MTAxMjI1OCwibmJmIjoxNDQxMDEwNDU4fQ.ltbz_CYRV0axNOtp33T62PytysW3sD3Cc96kg1Qq_6_22r4NWvoch4_K7_EEev6cymsfxC2hwGdHW8nplxObMIJGKzEdD3Tp5N0wpNS0BiVI7Ez_lLOx_YXisIVgDTG7QG4RBi7um9qR1sCi39iHt0dAw6uWIZTjcDF_0Bs_85DRXwM0RvIjOFNTFfB5wQ4vpCE-o9pRtfyAI4kIeKfCP-uc9oXOX0UIHiRl6t1FeOHZPpgcT8qhw1rq3f6RuycFhLRADvd-7YUdadLd_j3wR8obRlkXWI3L-IUFoUwXxxxY7kz9hTJqrGizW8hsYXyRP_lwkwfN0-pH-NvjsS5WTA

Access Token

eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsIng1dCI6ImEzck1VZ01Gdjl0UGNsTGE2eUYzekFrZnF1RSIsImtpZCI6ImEzck1VZ01Gdjl0UGNsTGE2eUYzekFrZnF1RSJ9.eyJjbGllbnRfaWQiOiJjb2RlY2xpZW50Iiwic2NvcGUiOlsib3BlbmlkIiwicHJvZmlsZSIsInJlYWQiLCJ3cml0ZSIsIm9mZmxpbmVfYWNjZXNzIl0sInN1YiI6IlRhaXNlZXIuSm91ZGVoQGFyYW1leC5jb20iLCJhbXIiOiJwYXNzd29yZCIsImF1dGhfdGltZSI6MTQ0MTAxMDQzNywiaWRwIjoiaWRzcnYiLCJpc3MiOiJodHRwczovL2xvY2FsaG9zdDo0NDMwMy9jb3JlIiwiYXVkIjoiaHR0cHM6Ly9sb2NhbGhvc3Q6NDQzMDMvY29yZS9yZXNvdXJjZXMiLCJleHAiOjE0NDEwMTIyNTAsIm5iZiI6MTQ0MTAxMDQ1MH0.JvvJ64AI3QkzT7u2Ts4Hdzz7q04euOAFYGGO_RH7M04CpBxSJVEGAqUaxb7qKHhXFZ-Z4-5Q6VHe0WFDZgLJ_-fYEZ0zMnI1zDchao2wENPcx_KdWL2d89PyMqzeNfwt5p_Jd2qzbTaDNhHYAzD2YZ8rytw8_QKECuuIxIpogC_8XjSA9oSrCoSLIlosqvPXN5nLQdn37EHWN3OnKkxnruxzV6iBgN5SfJnKAgCV1WLW6qL8FHYeJ1DGfogPYuVzHrylTTIru_XJaamvg-6tTTx33KHLJqjHZWUdqxFYNl9L_hy0HP_w1X-6j3ml6WMEJNC1IZUOe_K6lakh3VqwOg

**Comment by tjoudeh** [comment]
Hi Dom, yes exactly I want those claims in the access token so I will be able to use those claims in my recourse Web API.

**Comment by leastprivilege** [comment]
The you need to add the scope claim to a resource scope (e.g. read).

**Comment by tjoudeh** [comment]
Perfect man, thanks for your help :)
