### ISSUE TITLE
"SSL is Required" message when connecting over HTTPS to IdentityServer hosted on AWS

### ISSUE THREAD

**Issue by narciero** [IdentityServer/IdentityServer3#1820]
I have deployed a web-hosted IdentityServer3 application to AWS (ElasticBeanstalk) running on an IIS server. Everything works however now I am trying to setup SSL. I generated a self-signed SSL cert using OpenSSL and configured my load balancer to use it. I have a secure connection to my identity server site ( https://identityserverurl...) and have verified the secure connection using Fiddler (as well as viewing certificate/connection info in Chrome) however whenever I try to access any part of the IdentityServer application I get the "SSL is Required" message. In my IdentityServerOptions I have SslRequired = true and I have a valid signing certificate. Am I missing a key part of configuring SSL with IdentityServer? Thanks for the help.

**Comment by senseicz** [comment]
Hi, if you are using ELB in front your instance, usually this is set up in  way that HTTPS traffic is terminated on ELB and traffic between ELB and your instance http only. As a normal end user, you only see your traffic up to ELB, not all the way down to your instance.

ELB then uses specific request header to indicate whether incoming request was http or https. Usually this is named "X-Forwarded-Proto" but Amazon might be using different name. See this thread https://github.com/IdentityServer/IdentityServer3/pull/1158  as similar issue was already discussed here. You might need to change Core\Configuration\Hosting\RequireSslMiddleware.cs file.

**Comment by leastprivilege** [comment]
No need to change source code - if a load balancer is enforcing SSL - you can set RequireSsl to false in IdentityServer. Also check the docs on deployment.

It was also discussed that a separate middleware before IdSrv could inspect the custom header and change the request url on the fly - but not sure if this is even necessary.

**Comment by narciero** [comment]
Ok thanks, so HTTPS is terminated on the ELB and communication with my instance is always HTTP, the problem arises when I'm navigating between pages within IdentityServer (login, registration, permissions, etc) as the requests always use an HTTP base url, I'm assuming the  middleware would take care of this by inspecting the requests and then changing the uri scheme to https?

**Comment by narciero** [comment]
I took a look at #1158 , I am wondering if maybe there should be an optional flag during IdentityServer configuration where RequireSsl can be false, but you could set something like RedirectUrlScheme so that all redirects within IdentityServer could use a specified url scheme because there might not always be a consistent header like "X-Forwarded-Proto" to indicate a change to https is required. AWS does not use that header when forwarding requests from the ELB to app instance.

**Comment by narciero** [comment]
I know public origin is used to force a base url for redirects/links however maybe a simpler flag is needed that just switches the protocol from http to https, rather than defining the entire base url

**Comment by kylegalbraith** [comment]
I believe I have a similar issue as this one. I have a static JS client that has HTTPS. I also deploy IdSvr via elastic beanstalk and have HTTPS on there as well. Additionally, I am using the token manager JS that @brockallen has put together.

The problem is as follows:
1. HTTPS client requests over to IdSvr
2. Users signs in on IdSvr also over HTTPS
3. This then redirects back to the JS client callback.html (that is again on HTTPS)
4. However the token manager is then calling over to /.well-known/jwks. But this call goes over HTTP and is thus blocked because of mixed content.

Is there something in the configuration of IdSvr that I am missing?

**Comment by brockallen** [comment]
The metadata should all be sent over SSL -- what am I misunderstanding?

**Comment by kylegalbraith** [comment]
IdSvr sits in elastic beanstalk with SSL so therefore as mentioned above I do not need RequireSsl as beanstalk will handle that. However, the metadata url for /jwks must be coming back HTTP because in the callback that is called with HTTP instead of HTTPS. Does this suggest that IdSvr must still set the RequireSsl to true?

**Comment by brockallen** [comment]
Do you have PublicOrigin set?

**Comment by kylegalbraith** [comment]
I do not have PublicOrigin set, should it be set to the url of IdSvr behind the ssl in elastic beanstalk?

**Comment by brockallen** [comment]
Yea, that setting tells IdSvr what to use when it needs to emit URLs (like redirects for login, metadata, etc).

**Comment by kylegalbraith** [comment]
@brockallen that is exactly what I was missing, thank you.
