### ISSUE TITLE
Q: AccessToken still valid after logout

### ISSUE THREAD

**Issue by danielwertheim** [IdentityServer/IdentityServer3#1882]
If I validated using `implicit flow` and then grab the `access token` and then **sign out** and then uses that token in another client e.g. in Postman to do a `GET` against an API that validates that access token against the same OP, it works. But why? Why does it work after logging out? Thought the logout process would remove all tokens associated with the subject.

**Comment by brockallen** [comment]
If it's a JWT then it's not revocable. To make a token a revocable it needs to be a reference token. We don't automatically revoke them at logout time. And even then, sometime you want it to be used after the user is no using the app.

**Comment by kylegalbraith** [comment]
@brockallen how should we handle this? It seems bad that a user logs out but if they captured the access token then they can hit one of our API's with that still valid access token.

**Comment by brockallen** [comment]
Use reference tokens and when the user logs out revoke it with the token revocation endpoint.

**Comment by kylegalbraith** [comment]
Are access tokens in the ```implicit flow``` not reference tokens by default? Is there a certain configuration setting I need to use that says these are reference tokens. 

When I am calling the revocation endpoint from my implicit client per this [documentation] (https://identityserver.github.io/Documentation/docsv2/endpoints/revocation.html) what would my client need to pass to be authenticated?

**Comment by kylegalbraith** [comment]
Ok I see in the docs that access tokens can be configured to be of type reference. Is this allowable for implicit clients? Still a tad unclear on what I should hand to the revocation endpoint besides the access token.

**Comment by brockallen** [comment]
Yes, token types are configurable. To authenticate you need client credentials.

**Comment by kylegalbraith** [comment]
So my implicit client cannot call over to the revoke endpoint to revoke the access token it seems because it follows the implicit flow and has no client credentials. Is possible to do this in the SignOutAsync method in the user service on IdSvr?

It seems like that is likely the place where I will need to do it given the implicit flow and no client credentials, but what needs to be done in the IdSvr user service to revoke the access token?

**Comment by brockallen** [comment]
Actually, yes, that'd be another place to do it - at signout in the user service. You'd inject the client permissions service (I forget right now the full interface name).

**Comment by kylegalbraith** [comment]
I think this is the more preferable place to do it since you are already in identity server correct? So my custom user service just needs to inject this other interface and call a method on that? 

-----Original Message-----

**Comment by kylegalbraith** [comment]
What I went ahead and did is add a register method in configure custom user service to grab the DefaultClientPermissionsService.
```
factory.Register(new Registration<DefaultClientPermissionsService>());
```

Then I modified my CustomUserService to inject the DefaultClientPermissionsService which then provided me the service to use in SignOutAsync to remove the users tokens for the client.
```
public CustomUserService(CustomUserAccountService userSvc, DefaultClientPermissionsService permSvc)
```
```
public override Task SignOutAsync(SignOutContext context)
{
    var subject = context.Subject.GetSubjectId();
    _permissionService.RevokeClientPermissionsAsync(subject, "my-implicit-client");
    return Task.FromResult(0);
}
```

@brockallen does this align fairly well with what you were thinking? It seems to work well for my implicit client. The only other change I had to make was to set the access token type to reference for my implicit client.

**Comment by brockallen** [comment]
The client permission service should already be in DI -- just have your ctor accept it.

**Comment by okutlubay** [comment]
@kylegalbraith Does this compile? DefaultClientPermissionsService does not have parameterless constructor. It requires permissionstore, clientstore etc. How do you successfully inject this?

**Comment by dimsedane** [comment]
This was very helpful for me, just thought I would share the changes I had to make to get the code to work:

1. For the dependency injection to work you should have the IClietPermissionsService in the constructor.
2. SignOutAsync is async and so is RemoveClientPermissionsAsync, so it should be awaited, no need to return a Task.FromResult(0).

Also a note on that last part, if you want to keep this synchronous for some reason, .net 4.6 introduced [Task.CompletedTask](https://msdn.microsoft.com/en-us/library/system.threading.tasks.task.completedtask(v=vs.110).aspx) which just looks nicer, if you are on a new enough version of the framework.

So my code looks something like:

    private readonly IClientPermissionsService _permissionService;
    
    public UserManagementUserService(IClientPermissionsService permSvc)
    {
        _permissionService = permSvc;
    }
    [...]
    public override async Task SignOutAsync(SignOutContext context)
    {
        var subject = context.Subject.GetSubjectId();

        await _permissionService.RevokeClientPermissionsAsync(subject, "client-id");
    }


I do have a followup question for @brockallen on that last part. The context has a ClientId that I would like to use instead of a hardcoded string. But it is null, is that expected or am I doing something wrong?

**Comment by brockallen** [comment]
Open a new issue for new questions, please. But actually you should use stackoverflow for general questions.

**Comment by naveenkumarreddy** [comment]
Hi, even after using the "await _permissionService.RevokeClientPermissionsAsync(subject, "client-id");"
I am able to use the token to call the API.

Did you find any solution for this, please let me know. Thanks in advance :)

**Comment by DureSameen** [comment]
How to register IClientPermissionsService  by using autofac.
