### ISSUE TITLE
IdToken vs AccessToken sent to Resource Server

### ISSUE THREAD

**Issue by danutzplusplus** [IdentityServer/IdentityServer3#2015]
Hello, I've something that I would like to ask someone for some clarification. It's not an issue with IdentityServer V3, but something more general, about the usage of tokens of different types.

Considering we have the two different types of tokens, identity and access, which one is used for what scenario? Would there be any issue with sending an identity token to a resource server, like a WebAPI service.

From what I understood, from all the reading and research I did, the identity token is specifically targeted for the client application (for establishing current user identity in the client application), and the client will then ask a different token/s, an access one, for calling the resource server which will hand over information to the client application. 

And more specifically, the identity token contains certain fields that allows the client application to establish user identity and also establish that the token was indeed intended for itself (by checking the audience on the token; something that the access token does not necesarily have (I'm a bit confused here, since the JWT token issued by the Thinktecture IdServer does populate the audience field with a issuer_uri/resources value))

And the access tokens, which come with requested scopes, offer an authorization mechanism at the client level. So, in the end, for me at least, idtokens are for the client app, and access tokens are for the resource servers (webapis, ...). Is there any reason to send an id token to a resource server, or the other way around? Are there any issues with that? Any security considerations?

Thanks, and kind regards.

**Comment by brockallen** [comment]
Yes, you got it all right. As for access tokens, the scope sort of acts as an audience field. No reason to send an id token to a resource server (since they're different audiences).

**Comment by popcatalin81** [comment]
But what if you want to flow the Identity of the use to the backed, and the API is part of your trusted ecosystem, then you, either:
a. Add User Id, Name, Email, etc. claims to the access token(s)?
or
b. Pass the IdToken (as a bearer) through these layers?

**Comment by brockallen** [comment]
The access token is for the back end and it would contain the claims you need/want (or you could use the access token to call the user profile endpoint to look them up).

**Comment by popcatalin81** [comment]
> or you could use the access token to call the user profile endpoint to look them up

@brockallen I'll try to be more specific.

What I want to say in the above example is the backend is not public.It is a collection of nodes with services, that are called by the frontend in a private network (no public access). 

The frontend is a web server (with public access).

The front-end already has the id_token and needs to flow the identity of the user to one or possibly more nodes in the backend. The backend nodes called are from one or more subsystems, all trusted, that may call each other passing a token along .

1) In this case should you pass an access token to the backend and let each node call the UserInfo end point to obtain user claims? 

2) Or should you pass the id_token? 

3) Alternatively if calling the backend with an access token should you add the user claims to the access token and call the back end using an access token?

Concerns:
1) in this scenario won't there be a huge amount of calls to the user info end point ? (all backend nodes when receiving a token call user info endpoint to get user claims)
2) Is is safe to pass the id_token in the backend and use it as a bearer token? (all back end services validate the token and the audience)
3) if all the user claims are added to the access token, doesn't this mean the access token is somewhat duplicating the id_token role in this scenario?

Thanks

**Comment by brockallen** [comment]
The spec is designed for the id token to be used in the client and the access token to be used at the APIs. I'm sure you can come up with some alternative protocol to re-use the id token, but OAuth2 and OIDC just didn't evolve that way. I'm sure if they were all designed from scratch they'd look different.

In any event... since we've designed around the protocols, we do realize you want more claims in the access token, so we have a facility for doing that via config. Have you seen that? That will avoid making calls to the user profile endpoint. Just depends what you want/need. 

As for "is it safe to pass the id token to the backend" -- not sure. I really haven't scrutinized the attacks against it or how it could be manipulated or fooled. The spec authors do that sort of thing, and that's why we tend to stick with their lead since they've spent many more hours on it then I have.

**Comment by popcatalin81** [comment]
Regarding specs, I think there is lot's of contradictory information out there, for example:

Google Sign-In has an example how to pass the ID Token to a backend and also verify it. I don't know whether this is recommended or not, Google specific or usable with IdentityServer, or just old info: https://developers.google.com/identity/sign-in/web/backend-auth 

Also here for OIDC:
"If your server passes the ID token to other components of your app, it is extremely important that the other components validate the token before using it."
https://developers.google.com/identity/protocols/OpenIDConnect?hl=en

So either the spec authors don't agree, or Google has gone off spec again. 
Anyway for IdentityServer I will take it the recommendation is to use Access Tokens for backend and not use ID Tokens the way Google does it.

Thanks again,

**Comment by brockallen** [comment]
I think google's API is to help client side code validate the id token for the scenarios where they can't do the crypto. We have something similar.

I was thinking more about your questions... the other approach might be to look at the hybrid flow -- it might also be useful for your situation.

Also, it'll be good to see what @leastprivilege has to say.

**Comment by leastprivilege** [comment]
Access tokens are APIs - feel free to send the id_token (or its contents) along - but treat it as payload.

**Comment by Michaelbo** [comment]
@brockallen , i do not want to open a new question, as it is closely related to this one. What is the semantic difference then between a self-contained access token and an identity token? We can put whatever we want in both, so it's not the content that differs. Is it just a different spec then?

**Comment by brockallen** [comment]
id_token is for the client. access_token is for the resource. Check the spec(s) for more info.

**Comment by Michaelbo** [comment]
@brockallen i'm aware, i just wonder if the contents should be different. If im not mistaken, in some of your samples the accesstoken is used to construct claims on the client. But we should use the access token for that then?

**Comment by brockallen** [comment]
The big difference is the scopes -- the access token is intended to be used by a client on behalf of the user. The specs are designed around this concept.

**Comment by Michaelbo** [comment]
And is there a reason why we wouldn't just use the access token directly on the client?

**Comment by brockallen** [comment]
Tokens have audiences and the access token's target is the API (not the client). We don't want to have a situation where a malicious party (weather that be a user, client, or API) gathers tokens and then re-uses them in a context it wasn't intended to be used. This is how some attacks have been carried out on some vendors' implementations. 

If the OAUth2 and OIDC specs were re-designed today, maybe it'll all be different and you could do this. But there's history to how they were developed, and so it's best if we stick to using them how they were designed so as we don't introduce subtle security vulnerabilities into our apps.

**Comment by Michaelbo** [comment]
Hmmm interesting. Thanks!

**Comment by S3KCentrifugal** [comment]
Given that there are situations where we want to access the same information client side and resource side would there be any benefit in allowing a scope type to be both Identity/Resource. 

For example let's say I wanted to secure a WebAPI method with a specific claim, but I also wanted to control the visibility of a button in Javascript that accesses this method. My options currently are 
1) Add a new scope of type Identity and duplicate it's references to available claims
2) Expose a custom WebAPI method for sending back profile information, don't use identity claims. 

Wouldn't it just make sense to have shared scope type? Role/Security information is used for authorization server side, but it is generally required for customizing the presentation as well.

Maybe I am misunderstanding.

**Comment by BrettJaner** [comment]
> In any event... since we've designed around the protocols, we do realize you want more claims in the access token, so we have a facility for doing that via config. Have you seen that?

@brockallen I have not seen that :).  Can you point me to an example?

**Comment by brockallen** [comment]
https://identityserver.github.io/Documentation/docsv2/configuration/scopesAndClaims.html

**Comment by freerider7777** [comment]
Hi @brockallen !
I am a bit confused - you say id_token is for the client, but many popular cloud services use it to access api. Are they doing it wrong? :)
Examples: Auth0, Azure:
https://auth0.com/docs/architecture-scenarios/application/spa-api
https://azure.microsoft.com/en-us/documentation/articles/active-directory-authentication-scenarios/

**Comment by brockallen** [comment]
Well, what they are proposing is not something the specs suggest.

**Comment by pi3k14** [comment]
This http://connect2id.com/learn/openid-connect#cool-id-token-uses has a list of uses for id_token - might be interesting.

**Comment by leastprivilege** [comment]
@freerider7777 IMO - yes they are doing it wrong. All specs and threat models are clear on this. id_token is for the client, access token for the resource server.

Now you might come up with a very specific scenario where using the tokens differently might be OK - but you are basically in uncharted territory (at least from a spec point of view).

**Comment by woloski** [comment]
> All specs and threat models are clear on this. id_token is for the client, access token for the resource server.
Yes, that's the right way. As we (Auth0) introduce API authorization, we are in the process of moving all our docs to remove any reference to use id_token when speaking to an API.

**Comment by freerider7777** [comment]
@woloski Cool :) I've already noticed the pictures have changed in your docs. The difference in tokens usage was confusing me :))

**Comment by AGenchev** [comment]
I have the same problem: I pass the "id token" obtained @ frontend as per Google's example to the backend. 
Then I verify it on the backend, but then I can not call API, because it is not "access token". 
I spent 8 hours hitting my head in the wall and reading various examples provided by Google and did not find how to convert this verified "id token" to an access token. 
If it's impossible, then I wonder why the Google's examples sent me there ?!

**Comment by mangelino** [comment]
I am new to OpenId Connect and would like to understand how the Resource Server (say the API server), validates the access token in an private Security Provider scenario, like in an enterprise. Say I want to implement OpenId Connect for all my enterprise application: today, I hold authentication and authorisation information in an LDAP server. The application client asks the user for the credentials and the [resource] server then interacts with the LDAP server to authenticate the user and retrieve the authorisation information (eg the groups/roles of the user). 
With OpenId Connect, the application client identifies the user via the OP, and obtains an access token for the resource. How does the resource extract the data from the token to authorise the user, that is determining which roles this user has? Does the identity token need to be transmitted from the native application client to the server, for example to log audit information?

**Comment by AlexVPopov** [comment]
I think a lot of the confusion in the discussion comes from the fact, that when different people use the same terms, they mean different things. And also, the same person using the same term, could mean a different thing in different contexts. So I'll try to clarify this. 

@brockallen and @leastprivilege have iterated many times the following statement: 

> id_token is for the client and is always a JWT. access_token is for the resource/API and can be any type of token.

So `id_token` for the *client*, `access_token` for the *API*. OK - what is the client and what is the API? In any given architecture, the node that is requesting something from another node (be it an internal node or an external one to the system) might act as a client. So in order to prevent further confusion, let's take a concrete example.

On the one hand we have Google. We have an auth endpoint (component G1) and we have the Google APIs (component G2).

On the other hand we have our system, which consists of a mobile application (component A1) and a back-end API (component A2).

So in the context of our system the mobile application is a client to our back-end API. If the mobile application makes a call to Google's auth endpoint (G1), it is also a client. But if our back-end (A2) makes a call either to Google's auth endpoint (G1) or the Google APIs (G2) it is also a *client*.

Now, according to [Google's documentation](https://developers.google.com/identity/sign-in/android/backend-auth) the mobile application makes a call to Google's auth endpoint and receives an `id_token`. 

So the question, most of us are struggling with (I think @AGenchev has described this most accurately), is - how do we get an `access_token` in order to be able to make requests to the Google's APIs (component G2). What's more, we want to be able to make requests both from the mobile application (A1) and from the back-end API (A2).

So, back to [Google's documentation](https://developers.google.com/identity/sign-in/android/backend-auth), after the *client* (in our case, our mobile application, A1) sends the token to the back-end (A2), the back-end is supposed to verify the token in various way (do-it-yourself / Google's client libraries / calling the `tokeninfo`). OK, good, the back-end verifies the token, now what? How do we get an `access_token`, so that, for example, the back-end (A2) can hit the user profile endpoint of Google APIs (G2)?

Also, @brockallen and @leastprivilege, please clarify what you mean exactly by client and API, when you say that `id_token` is for client and `access_token` is for API. Thank you.

**Comment by aggieben** [comment]
@AlexVPopov the _client_ is the application that is requesting access to a resource (an _API_) controlled by the resource server, typically with delegated authorization by the user (excpetions would be `client_credentials` flow, etc, where the client application has its own authority).

Which apps are clients and which are resource servers depends on what the interaction is (I have apps that behave both ways, depending on the interaction).

**Comment by brockallen** [comment]
We use the terms from the specs, and where we say API we mean the resource server (but nobody doing .NET development these days would understand what that meant).

**Comment by lgleim** [comment]
@AlexVPopov A1 can send the (long lived) id_token to any resource/backend IN ORDER TO AUTHENTICATE on behalf of a user. There the id_token is verified and then should be exchanged for either a (short lived) session token or even just a session cookie, which is then used in the subsequent requests to that resource/backend as authentication. Think of sending the oidc id_token as a replacement of username and password (you wouldnt want to include that in each request), whereas the access token is the equivalent of a session cookie.

**Comment by trustedjohn** [comment]
I'm also having the same problem trying to convert id_token to access_token for API access (in my case, using firebase & gapi APIs). Just wondering if @brockallen or @leastprivilege has any insight into @AlexVPopov 's question about that?  I have only an id_token from Firebase but need to access gmail API from a mobile client app.

**Comment by AlexVPopov** [comment]
@trustedjohn and all other people - I think a great resource on the subject is [Google Identity Platform](https://developers.google.com/identity/). I'd like to point to two particular pages:
* [Using OAuth 2.0 to Access Google APIs](https://developers.google.com/identity/protocols/OAuth2) - this is an explanation how Google has implemented OAuth2;
* [Using OAuth 2.0 for Web Server Applications](https://developers.google.com/identity/protocols/OAuth2WebServer) - this is a guide on the concrete requests that must be made in order to obtain the different types of tokens. The cool thing about it is that along with the code examples in different languages, there is also information about the http/rest request, that must be made (the last tab of the code examples paragraphs), so that these requests can be implemented in any language (they can even be executed with curl or postman).

**Comment by stg609** [comment]
I'm still confused about the statement, "id_token is for client and access_token is for api". If the client only pass the access token to the API, how can the api tell whether the access token is stole or not?

Just as @brockallen  said in his comments:
> Tokens have audiences and the access token's target is the API (not the client). We don't want to have a situation where a malicious party (whether that be a user, client, or API) gathers tokens and then re-uses them in a context it wasn't intended to be used. This is how some attacks have been carried out on some vendors' implementations.

Say, I have a SPA using AngularJS + WebAPI. I think the AngularJS is the "client" and the WebAPI is the "api“. Now the client has obtained both Id token and access token via openid connect implict flow, and will then request to the WebAPI with access token in the http authorization header only.
As the client (angularJS) and the user agent are all in the end user's environment, there might be a malicious party steal the access token and then access to the WebAPI using that access token.

Isn't the oidc used to solve this problem by providing the id token to the api?

**Comment by pi3k14** [comment]
> If the client only pass the access token to the API, how can the api tell whether the access token is stole or not?

Well, in short, it can't.
But by using https and short lived access tokens you can reduce the possibility. To make it even more robust you could use Proof of Possession tokens and/or allow a token to be used just one time.

**Comment by stg609** [comment]
@pi3k14 thanks, I asked the previous question because I didn't get why OIDC is only for client, why not used for resource server (i.e. api) too. After reading the OIDC spec again, especially the section 16 which is all about the security consideration, together with your answers, now I think I get it. 

In short, OIDC is designed based on the secure environment (i.e. no malicious party). That is to say, in the secure environment, the only way to communicate with the resource server is using client. End-user can't communicate with the resource server directly. So, once the client has the ability to identity the end-user, it'll be enough for the resource server to know the access token is belong to the end-user too.

So I think that's why OIDC is not for resource server, as there's no need. And for other environment which is not secure, we need to provide additional security mechanism together with OIDC, e.g.

> 16.8.  Access Token Redirect
An Attacker uses the Access Token generated for one resource to obtain access to a second resource.
>
> To mitigate this threat, the Access Token SHOULD be audience and scope restricted. One way of implementing it is to include the identifier of the resource for whom it was generated as audience. The resource verifies that incoming tokens include its identifier as the audience of the token.

Please correct me if my understanding is wrong.

**Comment by pi3k14** [comment]
@stg609, for more info about security considerations [OAuth 2.0 Threat Model and Security Considerations](https://tools.ietf.org/html/rfc6819) might be an interesting read. 
I think you get the gist of OIDC, but your statement 

> OIDC is not for resource server

is a bit strange. The resource server will consume the access_token from the OIDC server, and it might use the OIDC server to get user information (UserInfo endpoint) with the access_token.

**Comment by stg609** [comment]
@pi3k14 yes, exactly. OIDC can be helpful for those scenarios,.

**Comment by bkwdesign** [comment]
As an OAuth newbie (and .NET developer) my Visual Studio Enterprise license gave me quick access to PluralSight content.. so, my introduction to modern web security was via @leastprivilege 's [courseware there](https://app.pluralsight.com/library/courses/oauth2-json-web-tokens-openid-connect-introduction/table-of-contents). 

As I get into building my first SPA using Microsoft's ADAL.js, it seems to contact the azure authorization endpoint with a request for an *id_token*, and then that very same token is used to interact with an API. That's what I'm seeing in [this sample azure app](https://github.com/Azure-Samples/active-directory-javascript-singlepageapp-dotnet-webapi). 

Very frustrating that this doesn't align with the OAuth 2.0 "spec".

As I follow the above conversation between @freerider7777 and @brockallen - it seems that ADAL.js should be passing an *access_token* to the API when it interacts there.

**Comment by dieseldjango** [comment]
If I'm following this thread correctly the point made is that it's wrong to misuse the ID token to authorize API access against a resource server, which completely makes sense. That's the purpose of the access token. However, there is a case where sending the ID token to a server, which I would not classify as a resource server, seems to make sense. This is when the ID token is used to authenticate and identify the user to another system. In this case the server, after verifying the token, would perform some action such as create an authenticated session or issue its own access token to provide API access against its resource server.

Here are some examples of this:

https://firebase.google.com/docs/auth/admin/verify-id-tokens
https://developers.google.com/identity/sign-in/web/backend-auth#verify-the-integrity-of-the-id-token
https://aws.amazon.com/blogs/security/building-an-app-using-amazon-cognito-and-an-openid-connect-identity-provider/

Am I correct that this is a valid use case for the ID token? If not then some big players have gotten it wrong.

**Comment by peymanebrahimi** [comment]
@brockallen , @leastprivilege 
Would you please answer S3KCentrifugal commented on Feb 23, 2016 question?

**Comment by albert130180** [comment]
hi! i have read across all these comments (and so in different articles, rfc, etc) and it's still not clear to me how to handle this scenario (at some point it was introduced in this conversation):
* 'client A' requests a 'resource server A' resource, providing an access token (let's suppose that with an authorization code grant)
* in order to provide that resource, the 'resource server A' needs to request another resource 'resource server B'. so 'resource server A' acts as a 'client B' also as part of that flow.

From my understanding, 'resource server A' should not forward access token received from 'client A' to 'resource server B', since it's another client. So, it seems 'client B' should use a 'client credentials grant' to access 'resource server B'. But then, does this mean 'client B' must act as 'resource owner' of 'resource server B' resources? From oauth2 rfc it seems that this is not required, but cannot find any specific example on how to accomplish this while ensuring 'client B' only has permissions to access to the original 'resource owner' resources (and that 'resource owner' should grant specifically). From my undertanding, there must be a way to connect that client B to the resource owner. Then there is the concern regarding identity, but i believe if previous stuff is clarified, this gets answered alone.

Anyone with some insights on this? any documentation to read about that specifically handles this scenario with concrete examples?

**Comment by Janidbest** [comment]
If I'm not wrong

Let's say Client A(Angular), Resource A(Backend Api) with implicit grant assigned the same scope in both configuration 
 Client A - Scope 1, Scope 2
Resource A - Scope 3, Scope 4

When the user logs into Client A, receives id_token, access_token.

Then whenever Client A needs access to  Resource A it will be granted with the access token because it is sharing the same scope.

Lets make it complex, introduce Resource B. If Resource A wants to make a call to Resource B then access_token is required which can be obtained by client credentials or if we have the same scope shared then the same access token can be used.

in this case if Resource B wants to know who the user is calling ( though it is server to server call) , I'm sure Resource B needs user activity. means access token should include at least sub.

I believe this is basic and oAuth should have covered already. 

 I'm going to give a try by sharing the scope and including the sub into access token claims by customising the access token while issuing. then access it wherever we want on the resource side.

**Comment by smoms** [comment]
I think id_token and access_token can be used interchangeable. One of the interesting use cases behind id_token is federation. A resource server can receive an id_token from a trusted IdP, validate the signature before granting access to its resources. This is a clear case where an id_token accesses a resource server.

**Comment by brockallen** [comment]
> I think in practice id_token and access_token can be used interchangeable.

I don't know what led you to this conclusion, but it's not right.

**Comment by smoms** [comment]
@brockallen  an id_token is used in important implementations (e.g. active directory) as mean to authorize access to resources. Furthermore to me makes lot of sense in federation cases. How would you federate with access_token? So i think id_token can well be presented to a resource server.

**Comment by brockallen** [comment]
> So i think id_token can well be presented to a resource server.

Not if it's a different audience.

**Comment by smoms** [comment]
> Not if it's a different audience
of course. id_token case described by me above is supposed to be sent to right audience. Anyway this is not the point of my comment.

**Comment by brockallen** [comment]
I just wanted to speak up so that people didn't incorrectly think you can use an id_token where an access_token should be used instead.

**Comment by tony-kerz** [comment]
the oidc spec doesn't mandate that access-tokens are jwt, but sometimes back-end services need info about the user to perform their function. 

i feel like it would be reasonable to pass the id-token to the back-end for this purpose (in addition to the access-token in the `authorization` header, perhaps in a header called something like `x-authentication`)...

**Comment by tliebe** [comment]
For me it is not clear to what resource the OIDC access token provides access to.
In OpenID connect isn't the OP also the resource server and the resource is the Identity profile?
Simple spoken the ID Token is just a document containing some identity information and the the access token is just the key to access the identity profile at the OP (resource server).
The access token in OIDC is not meant for any Resource Server other the OP hosting the resource "identity profile", isn't it?

So when calling an API of any other resource server I need another access token and not the OIDC access token, right?

If I now want to flow the identity to the other resource server I hesitate to pass around the access token to my identity profile. Since access tokens are bearer tokens and any entity I pass this token now has access to my identity profile even when I am not logged in. It's like giving my friend A the key to my flat and friend A passes my key further to his friend B whom I might not know or trust.

The information I want to pass to the other resource server is that the user has authenticated and proofed his identity to the client which is calling the API.
So as a client I call the other resource servers API and provide for example the username (or subject name) in the call so the other resource server returns the right resource belonging to the username (e.g. mailbox, insurance contract, pictures, etc..)
How can the other resource server proof that the client provides the correct username and not a fake one? If the client did provide the ID Token the other resource server would be able to verify the token and I don't see any reason to give the other resource server access to my identity profile.

What other options I see:
I may have the option to request another access token to access the API of the other resource server but than I still have no Identity Information but only delegated the access to the client.
I may have the option to treat the other resource server as another OIDC client but then the user needs to re-authenticate and give consent again unless the same user agent is used the OP has a session with. 

So I still don't see a best or at least good practice how to pass around an identity according the specs.

**Comment by pi3k14** [comment]
The access_token is intended for its audience (whatever that is defined to be)

**Comment by leastprivilege** [comment]
> The access_token is intended for its audience (whatever that is defined to be)

Amen. I'm gonna lock this now before more bad advice is given. Check the spec for more info.
