### ISSUE TITLE
Provide key-handling implementations for Azure Key Vault/AWS CloudHSM/OpenStack Barbican

### ISSUE THREAD

**Issue by MattCotterellNZ** [IdentityServer/IdentityServer3#2052]
OAuth/OpenID Connect key material is extremely sensitive. Compromise of such key material will not only potentially compromise all of your resources, but also on all other associated third parties who depend on that instance of IdentityServer for authentication. While this is not exactly old news, it would be nice if there was some out-of-the-box solution for defering to a cloud-based HSM for those projects hosted in Azure/AWS/Rackspace/etc.

Would it be a useful offering if we had some alternative concrete implementation to the necessary interfaces involved in managing and performing operations with this key material that defers it to a service such as Azure Key Vault, AWS CloudHSM and/or the OpenStack "Barbican" API?

**Comment by leastprivilege** [comment]
Absolutely - feel free to start a contrib project and let us know so we can link to it!

**Comment by MattCotterellNZ** [comment]
Awesome! My web application is built in ASP.NET 5 and hosted in Azure, so I won't be able to tackle this until the ASP.NET 5 compatibility pops up and even then I'll likely only be providing the Azure Key Vault implementation, but I'd be very excited to assist in this regards!

**Comment by leastprivilege** [comment]
Well - then feel free to create a repo. You'd need an Azure Key Vault specific ITokenSigningService.

**Comment by omerlh** [comment]
Hey
I am also facing the same problem - the biggest issue I saw right now is that the discovery endpoint is highly dependent on `X509Certificate`, and it is not an easy task to create one from what returned from CloudHSM/Azure KeyVault. I think that `ISigningKeyService` methods should use `JsonWebKey` instead of `X509Certificate2`. Then it would be a lot easier to create such an implementation. What do you think?
