### ISSUE TITLE
Hybrid Flow Doesn't Remember AllowRememberConsent

### ISSUE THREAD

**Issue by Grassycup** [IdentityServer/IdentityServer3#2057]
I am attempting Silent Renew with Hybrid Flow.
It works when I set AllowRememberConsent = false in the Clients config, but when it is set to true, I get back interaction_required error.
I also checked off the "Remember My Decision" in the consent page.
When I call mgr.redirectForToken(), it always takes me to the consent screen. 
Could someone point me in the right direction?

**Comment by AnEmptyReece** [comment]
This might not be the same thing, but I was puzzled recently that I was getting the consent screen on every login, even when checking to remember. I could see that it was being stored in the database.

However, upon examining the idsrv code, I found the following snippet:

```
            // we always require consent for offline access if
            // the client has not disabled RequireConsent 
            if (scopes.Contains(Constants.StandardScopes.OfflineAccess))
            {
                return true;
            }
```

So it turned out because in my client I was requesting the "offline" scope, I was then receiving the consent screen every time. Perhaps it's similar for you?

**Comment by Grassycup** [comment]
That fixed my problem.
I did not realize consent screen was required for offline_access.
Thank you!

**Comment by NetChris** [comment]
@brockallen, I see that this was specifically added to the functionality in d520312cc9de180c1c213f9441b51459c6e3b621.  What was the impetus here?  Is this an OAuth standard requirement?  If not, it seems that there would be valid scenarios for this.  The resource owner _did_ give consent for offline access and _did_ tick "Remember My Decision."  As a user, I would be frustrated having to give consent every time, even though I specifically stated to remember my decision.

At the very least, it seems like this should be a flag on the Client to permit it, e.g. `Client.AllowRememberConsentToOfflineAccess`.  Especially if the design allows skirting consent completely through the `Client.RequireConsent` flag.

Am I missing something?  I'm happy to submit a PR if this is a use case that fits.

**Comment by sudipster** [comment]
@brockallen, I have the same view as @NetChris on this topic. From the users standpoint, it does not make any sense to have them accept the consent, and remember, and then ask them every time to accept the consent.  Could you shed some light on this please?.

**Comment by brockallen** [comment]
IIRC we added this because there was some guidance that came out from the OIDC or OAuth2 committee that you must prompt for consent every time offline_access is requested.

**Comment by sudipster** [comment]
Ok.. This what I came to conclusion with in this situation.. For our intranet/in-house apps we are going to set RequireConsent to false. This way it won't bother our users that much, however if there is a third party app try to use our ids as an idp, then we will turn this value on.

**Comment by brockallen** [comment]
Yep, @sudipster, and that's exactly the right thing to do for those different types of clients.

**Comment by NetChris** [comment]
For the intranet/in-house applications I support, I totally agree with toggling RequireConsent off.  That's the best solution for a number of reasons.  However, for public applications, I can't do this and I still assert that this behavior is, at best, confusing.  To address @brockallen on the OIDC/Oauth2 guidance, the best Google-fu I could conjure gave me really only one result: [OIDC standard, section 11](http://openid.net/specs/openid-connect-core-1_0.html#OfflineAccess) on Offline Access.  It states that "The OP MUST always obtain consent to returning a Refresh Token that enables offline access to the requested resources. **A previously saved user consent is not always sufficient to grant offline access.**" (emphasis mine)

If this was the prompt to make this change, I think it was a mistake.  I think "previously saved user consent" is being misunderstood to mean a previously saved consent to offline access.  I believe it means previously saved user consent in general.  i.e. just because a user previously consented to having access to `profile` and elected to save their consent doesn't _infer_ offline access.  However, an explicit offline access consent and an explicit selection of "Remember my decision" would tell me pretty clearly that the user is saying, "I'm granting you access to these scopes, even when I'm not online and directly in the loop.  I trust you.  Please don't bother me again about it!"  And then we go and bother them again about it.

**Comment by brockallen** [comment]
What does google do? I don't really know.

Anyway, we should ask @leastprivilege since he was involved.

**Comment by sudipster** [comment]
Google does the same thing ids does. It asks for consent every time..

**Comment by brockallen** [comment]
Well then, I think we did the right thing :)

**Comment by NetChris** [comment]
Alas, I must relent then. ;)

Thanks for the comments, all.

**Comment by jeremycook** [comment]
I just ran into this behavior while changing implicit flows to hybrid. I would like to chime in that a middle ground would still be nice under certain circumstances. I appreciate that IdSrv matches Google's behavior, but being able to opt a Client into remembering offline_access consent could make a better user experience for the following reason:

I prefer the consent screen, even for internal applications I control, because single sign on can be confusing. By presenting the user the consent screen, it helps users understand that "oh, I am logging into website XYZ with my 'Yadda Yadda Account.'" As opposed to clicking a Login link, and suddenly being logged in and having no idea what just happened.

It would be one thing if OIDC could behave like Kerboros in all situations and automatically log me into every OIDC protected website I make, but that just isn't possible. Most of my sites need to permit anonymous access to at least the home page. So yeah, the consent screen just helps users better understand what's happening when they click Login or hit a protected page, particularly when their already authenticated at the IDP.

**Comment by siddharthashw** [comment]
@ReeceWilliams7 , Where do I should keep this code ??
`            // we always require consent for offline access if
            // the client has not disabled RequireConsent 
            if (scopes.Contains(Constants.StandardScopes.OfflineAccess))
            {
                return true;
            }`

**Comment by ReeceWilliams7** [comment]
@siddharthashw  You don't need to put that code anywhere, it's a code snippet from IdentityServer3 itself. The reason I posted it was to show that when you are requesting the offline_access scope and you have consent enabled for your client application, then your user will always be prompted for consent.

**Comment by siddharthashw** [comment]
@ReeceWilliams7 , So its fixed that, whenever will set RequiredConsent = true. We have to allow consent page for every login.

Thanks in advance.
