### ISSUE TITLE
Intercepting User-Agent on login event

### ISSUE THREAD

**Issue by skivsoft** [IdentityServer/IdentityServer3#2113]
Hello,

could you please advice which is the best way to intercept and associate User-Agent with login/logout event?

I have implemented IEventService but not sure about how effectively associate User-Agent with an event without any additional performance costs.

**Comment by leastprivilege** [comment]
what do you mean with performance costs?

**Comment by skivsoft** [comment]
As I understand logging options EnableWebApiDiagnostics and WebApiDiagnosticsIsVerbose should be always true for puprose of intercepting User-Agent, I feel it will be little bit slower than without enabling logging but I didn't measure difference yet.

Much important question for me is how to associate User-Agent with a login event.

**Comment by mderriey** [comment]
Hi,

I don't think the diagnotics-related options have a lot to do with what you're trying to achieve.  
My go-to solution would be to implement a custom `IEventService` so that you know how to raise events. Please note that `IEventService` is responsible for *raising* the events, not *consume* them. It's basically a publisher, and you need a subscriber to do it properly. A mediator could do the trick, but it could be too heavy for what you're trying to achieve.

I made a very quick implementation and didn't bother about the responsibility of `IEventService`, I just wanted to make sure you could access the OWIN context in there.

```csharp
public class UserAgentEventService : IEventService
{
    public Task RaiseAsync<T>(Event<T> evt)
    {
        var localLoginDetails = evt.Details as LocalLoginDetails;
        if (localLoginDetails != null && evt.EventType == EventTypes.Success)
        {
            var login = localLoginDetails.LoginUserName;
            var userAgent = HttpContext
                .Current
                .GetOwinContext()
                .Request
                .Headers
                .Get("User-Agent");

            // Insert into DB
        }

        return Task.FromResult(0);
    }
}
```

`LocalLoginDetails` is the type of event raised when either a successful or failed login occurs.  
Also make sure to enable success events in `IdentityServerOptions.EventsOptions` since by default, all the properties are set to `false` so no event whatsoever will be raised.

This is because no matter what implementation of `IEventService` you pass to the `IdentityServerServiceFactory`, a [decorator](https://github.com/IdentityServer/IdentityServer3/blob/a6e2b6bdfd1516af6cd9fdc9f46a08bb23bb553e/source/Core/Services/Default/EventServiceDecorator.cs) is applied on top of it, and this decorator selectively raises the events based on the `EventsOptions` that are passed in the configuration.

Hope this helps.

**Comment by skivsoft** [comment]
Hi @mderriey,
unfortunatelly this code not works for me `HttpContext.Current is null`.

When diagnotics-related options are enabled, I can intercept User-Agent with corresponding ActivityId. And then associate it with login event using ActivityId and SubjectId.

**Comment by leastprivilege** [comment]
Don't use HttpContext. Inject the owin environment

**Comment by mderriey** [comment]
Oops, my bad. My sample was in an MVC application, that's why it worked.

Thank you for the clarification.

**Comment by skivsoft** [comment]
It works with OwinEnvironmentService injection in CustomEventService's constuctor.
Many thanks.
