### ISSUE TITLE
'Submit this form' page customization

### ISSUE THREAD

**Issue by mirkolugano** [IdentityServer/IdentityServer3#2124]
I would like to change the 'Submit this form' document.title property of the temporary response page (and maybe add a loading gif) I get after the authentication but if I got it right that's not possible with the usual templates/page.html overwrite feature. It's not a real problem, since the page disappears very quickly, it would just be a nice-to-have feature. Is it possible? Thanx.

**Comment by brockallen** [comment]
Hmm, ok... I guess we can think about how to make that configurable.

**Comment by mikeandersun** [comment]
:+1:

**Comment by dcinzona** [comment]
:+1:

**Comment by scottbrady91** [comment]
:+1:

**Comment by cbomkamp** [comment]
:+1: 

This page doesn't always disappear quickly.  For example, if the client application was just deployed/updated, it can take several seconds for it to "spin up" so any user who happens to login at that time are stuck on this completely blank page for several seconds.

**Comment by streicherm** [comment]
:+1:

**Comment by davebown** [comment]
+1

**Comment by lyntondicks** [comment]
+1

**Comment by JesseKlaasse** [comment]
+1

**Comment by somak12** [comment]
:+1:

**Comment by brockallen** [comment]
So should this be a new service, an addition to the current view service (breaking change), just a string somewhere in the config system for the name of the custom file, or a file in the ~/templates discovered by convention?

**Comment by davebown** [comment]
For me either a string in the config system or a custom template discovered by convention would suffice. Obviously the latter would allow more flexibility and snazzy animations as suggested at the start of the thread. ;-)

**Comment by dcinzona** [comment]
Config string or file in Templates works for me.

**Comment by mirkolugano** [comment]
I would also prefer a file in the Templates folder for more flexibility as davebown suggests

**Comment by brockallen** [comment]
Ok, I've done something towards this request. 

If you're using the `DefaultViewService` (or a derived class) then there's a new view that can be used called "authorizeresponse" and it works like all the other views (in terms of customization, partial vs. full, and the "templates" folder). I did it this way since it seemed to make sense to try to re-use as much of the existing logic to locate the template view folder, and re-use as much of the layout customization that people might have already built.

This new view is used from some special casing code in the authorization response logic and was done this way as to not introduce breaking changes in this release. In the 3.0 time frame a more formal API will be added to the view service interface so people not using the `DefaultViewService` will also be able to replace it.

Please have a look on the myget feed/dev branch and provide feedback. I'll also add a new sample to show how to use it. 

Thanks.

**Comment by dcinzona** [comment]
This is great! Thanks!

**Comment by somak12** [comment]
Hi @brockallen  when can we expect this feature in case of Custom ViewService? I guess you mentioned 3.0 release. Can you give an estimate of 3.0 release? For now is there any way to do this?

**Comment by brockallen** [comment]
In 2.4 in theory you could derive from the DefaultViewService to get this behavior.

**Comment by ManojShenoy25** [comment]
@brockallen : Is there any documentation or sample to configure the document title for the "Submit this  form" page?

**Comment by brockallen** [comment]
Only what you see above.
