### ISSUE TITLE
Support different templates based on client_id 

### ISSUE THREAD

**Issue by dapug** [IdentityServer/IdentityServer3#2132]
The DefaultViewService is pretty handy, especially the ability to replace entire views in a Templates folder. This gets you pretty far without needing to build custom IViewService.

It would be great to be able to render different login and other screens based on the client making the request.  

Business case:

We have a consumer facing service that has domain owned web, mobile and desktop apps, as well as 3rd party partner owned apps (clients).  The brand we reflect is the same in all scenarios, but we'd like slightly different sub-branding on the sign-in screen depending on which client you are using (i.e. mobile app, website, desktop app, partner app, etc).

**Comment by brockallen** [comment]
This has been discussed before, but the gist of my opinion is that it's disingenuous to the user to change the login experience too much since they user is logging into the centralized SSO provider, not the app. I get that the business side has certain requirements, so of course do what they ask. But this is the logic I use when explaining to the business what they're asking.

When a user logs into gmail or google calendar, does it look different? No. They're logging into google. Gmail or calendar is just an app.

Anyway, I don't see us adding that as a built-in feature anytime soon. I do know we have lots of people that ask for it, so maybe this would be a good candidate for a contrib project.

**Comment by dapug** [comment]
I definitely agree on consistency for the user.  The differences I am thinking of would be minor.  In any case, no argument here.  Yes, possible contrib project for special cases.  I'm going to try and stick with a single page as designed, but if I end up building this capability, I'll post it.

**Comment by dapug** [comment]
Actually, have a look at facebook login on the PC, and then from your phone.  Very different layout, though still a consistent experience. Not just responsive html differences either.  

It is not disingenuous to users, they expect a different experience depending on context, they just need consistency and reassurance.  And I'm super picky about UX, and am ever-careful about situations that would be disingenuous, and mostly agree with your point, with these exceptions.

**Comment by brockallen** [comment]
I wasn't talking about changing the UI for form factor. For facebook, you still know you're logging into facebook. They're a example anyway since they don't really have more than one app.

**Comment by nukec** [comment]
I clicked this with high enthusiasm, then got disappointed by comments haha
