### ISSUE TITLE
RESTful Service with Identity Server 3 authentication

### ISSUE THREAD

**Issue by pushpindersingh** [IdentityServer/IdentityServer3#2197]
I would like to use the Identity Server with the RESTful webapi's on the same server ( basically as a reference assembly), do we have any sample project with configurations for redirect url etc and adding multiple Identity provider through configuration file. 

I assume IS3 ( Idenity Server 3) can be installed as nu-get package. so if the code level the only Core project need to included, where we can add the configuration file for customization changes, without adding another sample configuration project?

**Comment by mderriey** [comment]
Hi,

I'm not too sure I understand what you're trying to achieve.
Do you want the same web application to host IdentityServer and a Web API that is protected by IdentityServer?

If this is the case, I'd say this is possible.
You might be on the wrong track, though, since IdentityServer is not customised by a configuration file, at least not out of the box, but with code.

I'd suggest you have a look at the [samples](https://github.com/IdentityServer/IdentityServer3.Samples), identify clearly the different parts - IdentityServer on one side, a protected Web API on the other - then try to combine them in one project.

**Comment by pushpindersingh** [comment]
Thanks for answer, yes i want keep web api and Identiy Server in same Solution.

Do we have some road map defined for Identity server, what enhancements most likely coming in near future?

**Comment by leastprivilege** [comment]
Are you missing a feature?

You can always have a look into our issue and milestone planning on github and

https://huboard.com/IdentityServer/IdentityServer3

**Comment by pushpindersingh** [comment]
Thanks, I would like to become the part of contribution team as developer. Specially for Identity Server 4, please suggest do you guys meet on daily / weekly?
