### ISSUE TITLE
Identity Server 3 and Multi tenant

### ISSUE THREAD

**Issue by tutkoo** [IdentityServer/IdentityServer3#2239]
Hi,

I have seen questions from last year about multi-tenancy and I was wondering is there support available already or is it on the roadmap?

**Comment by brockallen** [comment]
Nothing built-in. Multi-tenancy is very often very application specific, so you need to coordinate what it means for you with IdSvr.

**Comment by tutkoo** [comment]
Thank you

**Comment by LinqBeast** [comment]
I was able to establish a multi-tenant STS by setting the tenant (Acr value I believe) in the middleware and URL at the client, when necessary.  From there, I check the tenant value off the SignInMessage when authenticating in my User Service and create a claim out of it.  Don't forget to add the necessary allowed scope settings and then actually request that scope from the client.  This allowed me to authenticate against the correct user store and then get profile data and confirm the user was active against the correct user store as well.

This all works fine until you need to call the UserInfo service with an Auth token to pull User claims.  This fails on a call to get the profile data because the tenant claim is missing.  From here, you can either modify IdentityServer code (UserInfo control et. al) to add the tenant claim, so that it is available to the User Service call to get the profile data or easier to do what Brock suggested and let off the subject you set.  Remember, the subject for the user should be unique for the STS instance (cross-tenant).  So, I set my sub to something like username:[store id].  When/if the tenant claim is missing, I grab it from the subject.  Works well enough, albeit a little hackish.
