### ISSUE TITLE
Reset password link

### ISSUE THREAD

**Issue by snothub** [IdentityServer/IdentityServer3#2280]
I'd like a password reset page to ask user for username and send email with the link to reset password to whatever email address is in the system, that would lead to a page with fields for new password and confirm password. How could this be done and does IUserService support this at all? Obviously, the link would have to contain some encrypted parameter and not give away anything and nothing would happen to the user until the link is used

Thanks

**Comment by mderriey** [comment]
Hi,
[`IUserService`](https://github.com/IdentityServer/IdentityServer3/blob/65d23271fd1d46f9a7ac2a463767d664682ab3dc/source/Core/Services/IUserService.cs) itself doesn't support that since its only responsibility is to login users.

If you use ASP.NET Identity or MembershipReboot as you users store, they both support this feature.  
My experience with ASP.NET Identity was nice. The [`UserManager`](https://aspnetidentity.codeplex.com/SourceControl/latest#src/Microsoft.AspNet.Identity.Core/UserManager.cs) class has 2 methods related to this feature, `GeneratePasswordResetTokenAsync` and `ResetPasswordAsync`.
The first one returns a token associated to a user.
The second one takes the token and a new password as a parameter.

The flow was to send an email to the user with a link containing the token and the email address.
The page the link pointed to then asked the user for his new password and invoked the second method.

Hope it's clear.

**Comment by snothub** [comment]
Thanks, but we're using a custom implemented User Store because we're migrating this from a legacy system. But that is going to be solved. My concern is how to best preserve the context if user is redirected to authorize endpoint and has to go through the password reset at the end of which should be redirected back to the original login page. I assume the "signin" value should be sent all the way, but how can this value be verified to be valid in the password reset controller?

**Comment by brockallen** [comment]
Since it sounds like you're doing a lot of work in your own custom pages that need to interact with IdSvr, then  you should be familiar with our various OWIN environment extensions: https://identityserver.github.io/Documentation/docsv2/advanced/owin.html

If there's one you need that we don't have, let us know.

**Comment by snothub** [comment]
Awesome, @brockallen. I take it I can use GetSignInMessage to verify the validity of the signin value when user clicks the password reset link, as it would return nothing if value is invalid.

**Comment by brockallen** [comment]
Right. It also contains other info, like the client id and the original return url.
