### ISSUE TITLE
MVC Client Browser Calling Web Api Directly

### ISSUE THREAD

**Issue by farzad99** [IdentityServer/IdentityServer3#2284]
I need to set up an Identity Server to provide security for an MVC application and a Web Api service. HTML pages that are created by the MVC application make ajax calls to the MVC server and also the Web Api service directly (browser makes ajax call directly to the Web Api). Also the MVC server needs to call the Web Api service too. I can authenticate the user for the MVC application easily. But how do I go about authenticating the user for the Web Api Service? Do I need to use something similar to the "Javascript Implicit Client - Simple" project that's part of the Clients sample?

**Comment by dturska** [comment]
Would this work? 

 For example say you have one solution with two projects (a mvc project and a web api project)  

 The Mvc project would be protected with OpenIdConnect Middleware using the Hybrid flow asking for an api scope. 

 The Api project would be protected with the IdentityServerBearerTokenAuthentication Middleware.  

Then instead of the javascript directly calling the api, you could have the javascript call the mvc controllers directly. The logic in the mvc contoller would call the api by passing an access token in the Header : Authorization  Bearer {accessToken}.

You would have to create controllers in the mvc project to handle the javascript calls that are currently calling the web api directly.  Basically a server side proxy to the web api.   You would also need to update your javascript to call mvc instead of the web api directly.

**Comment by farzad99** [comment]
Thank you for your response. The requirement for the project is that browser pages created by the MVC application need to call the Web Api directly so I wouldn't be able to use what you suggested.

**Comment by brockallen** [comment]
You need to have your server-side MVC code also request a `token` in the `response_type` and then keep that token in your cookie. Render it on each page so the JS can then use it when calling back to your APIs. Validate it on the server with the identity server bearer token authorization middleware. I'm sure our samples have all of this code (albeit not necessarily all in one place).

**Comment by farzad99** [comment]
Brock,

Thank you. I'll go through the samples and see if I can implement that with the information that you provided. I'm keeping the ticket open until I have a working prototype.

**Comment by firez5566** [comment]
Hello, I'm in a similar situation and I'm trying to get it work.
Basically I have 2 controllers in the same MVC application, one for APIs and one for standard Views. I'm using Hybrid Flow and OpenIdConnect Authentication on both. If I correctly understood now I need to map the second controller to use Bearer Authentication using the token I get with OpenIdConnect.

As a temporary workaround I just extended on IdentityServer both AccessTokenLifetime and IdentityTokenLifetime (up to 12 hours). I know it's not the best solution but... at least it works.

P.S.
Maybe it's useful to add a similar example on the Sample repository? I know there are all the resources but it's not so easy to mix everything for someone new to authentication/authorization topics. Almost all web applications are now SPA or anyway have a lot of ajax calls back to server, maybe extending MVC OWIN Hybrid Client with an API controller could help lot of people understanding better how to do it (and avoid lot of questions here)

**Comment by pollax** [comment]
@dturska, I have a late follow up question on your suggested solution.

> Then instead of the javascript directly calling the api, you could have the javascript call the mvc controllers directly. The logic in the mvc contoller would call the api by passing an access token in the Header : Authorization Bearer {accessToken}.

Where does the access_token come from in this case? Should the MVC app authenticate itself and use its own token, or should it somehow "impersonate" the user?
