### ISSUE TITLE
automated (sw) login from a client with no human interaction, using username/pw credentials. 

### ISSUE THREAD

**Issue by pashute** [IdentityServer/IdentityServer3#2319]
It is a business requirement by us that the automated, software controlled  (no human intervention) login is done by passing credentials (username / pw) and authenticating that against the user-store (in our case Active Directory). 

1. Can this be done?
2. Any pointers? 
3. I'm thinking perhaps putting the username pw in the client secret and using regular client flow authentication. Now which class would handle the client flow authentication (a regular IUserService with preauthenticate?)

**Comment by mderriey** [comment]
Hi,

I'm sorry, I don't quite get what you're trying to achieve.
If you already have the login/password pair, you can use the `ResourceOwner` flow. This allows an application to login a user just by calling an endpoint, by providing the user's credentials.

**Comment by leastprivilege** [comment]
If there is no human involved - it is a client. You can implement client authentication by implementing ISecretValidator.

**Comment by urbanhusky** [comment]
I agree that, technically, this is a client and not a user. Beware that you won't be able to use openid scopes if you use client credentials flow (and you won't be able to query the userinfo endpoint)

**Comment by leastprivilege** [comment]
Of course not - no user no userinfo. makes sense.

**Comment by pashute** [comment]
Right, but my management DO want me to give a user / password. 

I was not aware of the ResourceOwner flow. I'll read on it and see if its ok for me. No login screen will be shown? In the ResourceOwner flow do I get the claims?

**Comment by urbanhusky** [comment]
ROPC flow is intended for clients, where the user provides username and password to the client, which then authenticates with the user's and its own credentials. The downside of that is that the user exposes his/her credentials to the client application, which the user would have to trust to not do any bad stuff with (like: sending it to a third party...).
There is no redirect or IdentityServer login-page involved, the actual asking for the credentials has to be handled by the client application. It could be used when migrating from an ASP.NET forms based or Windows Forms based application that has its own login form.

Note that both the client and the user authenticate with username and password (or id and secret) in this scenario.

If you want to have a standalone client which does not rely on a user - where would that client get the user's credentials from? At that point you should stop and take a step back, because storing user credentials (more gravely: storing plaintext/unhashed user credentials) should not be done.

The client can still have its own claims and access scopes (not sure about identity scopes?) in client credentials flow.

**Comment by pashute** [comment]
The requirement is to give different customers external to our company a username and password (pw changes with time) from our Active Directory. They then call our API from their pre-approved client, only by adding this username / password to the call. 

That user, regardless of this particular API call that we are requiring authentication/authorization for,  will have additional permissions only for actions that are used by their company (a directory that stores their files for example).  They will store the pw encrypted, e.g. in an encrypted web.config file. 

This can be in addition to the client/secret permission. Their pre-approved client which is run as an automated job with no human involved, then calls our API (in https) from its known IP, along with their username and encrypted password.  Here's where my question comes in. How should that be done? 

The requirement is that my API authenticates and authorizes according to that AD user. 

If Client authentication cannot give me back "claims" then I cannot use that. 
If Resource Owner authentication can do this without showing a login screen, then that's what I'll use.

**Comment by urbanhusky** [comment]
The independent client without any relation to a human user should use client credentials flow. You do get claims from that, you cannot request the openid scope.

**Comment by pashute** [comment]
If so, - using client credentials, what IDSrv3 component do I override to do something while I'm authenticating the client. Is there an IClientService class that I can override (similar to the IUserService)?

**Comment by urbanhusky** [comment]
I'd guess ISecretValidator as stated in the third answer, haven't done that myself yet though

**Comment by pashute** [comment]
OK for some reason I skipped reading Dominic's answer.  I'll create a Resource type scope with the role claims for authorization, and inside the ISecretValidator authenticate the username password given in the secret against the active directory and at the same time append the role claims according to the AD groups of that authenticated user. 

The API is using a custom authorizing class derived from AuthorizeAttribute which checks the roles, so I'm ok there. 

Reading your answer about the resource owner flow, I thought already that there's an out-of-the-box flow for this. :-(

**Comment by urbanhusky** [comment]
As an advice: you might be more flexible and maintainable if you use resource based authorization instead of roles-based authorization (you could still use role claims to make decisions about the authorization). This decouples the resources you're protecting from the roles and gives you a central way to manage authorization instead of having to go through all the code (plus can avoid the inevitable super* roles)

**Comment by pashute** [comment]
I never really understood that. 

I'll immediately explain what I think I'm missing but first a few things about what I am doing:  

We are not giving any "resources" its just an access to certain APIs or not. Our setup is as follows: 
  - an automated client service (doing its job say once a day, or when some event happens) from outside our company, calling 
  - our api server with a certain api call, which is to be authenticated and authorized so it passes on to
  - our idSrv3 server which redirects back to the api with the results of auth. The API serves the result back to the automated client. 

With resources you typically have a fourth component: a resource giving server, so usually
  - a human user based client calls the API or the UI, which in turn needs resources from a res server, typically an external res server (such as Gmail giving permission to view you contacts), so the API or UI first redirects 
  - to the res server which says it needs user consent, so we are redirected to our IDServ3 which authenticates and shows consent, and then redirects back to the API with a res token so it can talk to the res server directly and get what it needs from it. Is that correct? 

Also, I understand that the resources are typically authorized according to actions requested and permitted about them, so I could have a different type of granularity than roles such as readOnly vs. readAndWrite permissions, But as I explained, in my case I just want to have everything simply done by letting our  admin decide to put the user in an AD group (interpreted as the user's role), which will enable that user's access to the particular API call.   

Now to my questions: 

1. First question: Did I get the res server thing correctly? Is that the typical res flow? The only res flow? (I never went into it because I perceived that we don't need it)  

2. Second question: In my case, am I correct in saying that I'm not serving resources?

3. Third question: How is this "decoupling" the resource from the roles? (And what is the resource in my case, the API call?) In what way are the "resources" now coupled to roles, and why is that bad. 

4. What are the inevitable super roles and how are they avoided by using res based authorization. 

 5. And is there no claims authorization class, only a resource authorization class in which the claims are checked?  If so, why not?

**Comment by mderriey** [comment]
I'll try to answer your questions.

1: You didn't get this quite right. The flow would be the following:

 - The automated client service authenticates itself by calling an API on IdSrv. In return it gets an access token
 - The client service then makes a request to your API, passing along that token
 - The API authorization layer is based on tokens, more precisely on claims that the token contains.
 - If the authorizations succeeds, then the API will serve the requested resource

2: See how I said resource in that last sentence? When we say protected resources, a resource can be anything: an API, a document, whatever.

3: With claims-based authentication/authorization, all the information associated to an entity is defined as claims. This means that we're not limited to a user having a name and some roles, it's all expressed as a list of key/value pairs. That being said, .NET keeps the name and the roles notion. It does so by mapping the name to a specific claim type and the roles to another specific claim type.
Since I feel I'm unable to explain this clearly, I'll give an example:
Say a token has the following claims

Claim type | Claim value
------------- | ---------------
name | Mickael
role | ReadOnly
role | Write
age | 45
position | Developer

When .NET creates a `ClaimsIdentity`, you have the possibility to specify which claim is going to be used for the `Name` property, and which one is going to be used for the `Roles` property. In our case, if we choose respectively `name` and `role`, the resulting `ClaimsIdentity` will have a name of `Mickael` and 2 roles: `ReadOnly` and `Write`.

In the end, it's up to you which claim you choose for the authorization.

4: To me, claims-based authorization doesn't prevent you from using super-roles. It just provides another, more granular way to do authorization. Method `A` could be authorized by claim `a` and method `B` could be authorized by another claim. You have the choice. It's not a roles-only model anymore.

I hope this is not more confusing :+1:

**Comment by pashute** [comment]
It seems from #549 Add claims to Client model, that claims are not created for the client, if I'm using client-credentials flow. 

In the regular (code or implicit) username/pw flows, the IUserService is invoked, there's a 

            public Task<IEnumerable<Claim>> GetProfileDataAsync(ClaimsPrincipal principal,
                                                            IEnumerable<string> requestedClaimTypes = null)

call that can create a list of claims. 

There's nothing like that in the ISecretValidator. How do I add that and get it called?  Is it possible at all?

**Comment by mderriey** [comment]
From navigating through the code, what I see when you ask for an access token with the client credentials flow, you end up [here](https://github.com/IdentityServer/IdentityServer3/blob/4398f56bde322126e1a242efbc57a19c5ba0af8e/source/Core/Services/Default/DefaultClaimsProvider.cs#L138).

Client claims are sent if:

 - the current flow is client credentials - which is checked via the `subject == null`
 - or the `AlwaysSendClientClaims` is `true`

Then, by default, they are prefixed with `client_` because of the `PrefixClientClaims` property default value being `true`.

So you should get your claims, but maybe they are prefixed with `client_` in which case you'll have to set the `PrefixClientClaims` to `false`.
