### ISSUE TITLE
Removing access token from navigation bar

### ISSUE THREAD

**Issue by iLearnIdentityServer** [IdentityServer/IdentityServer3#2343]
Hello,

recently I joined OAuth/OpenID party. 
I did homework, read the spec, read the IdentityServer docs, run IdentityServer3 with custom services and store, build portal for managing users, clients, scope, user permissions.

For implicit flow, how can I hide access token from navigation bar after authentication?

**Comment by mderriey** [comment]
Implicit flow supports 2 response modes: form post and fragment.
The first one posts values back to the redirect URL while the second includes data in the URL fragment, which is what you're experiencing.
You can change that behavior when calling the authorization endpoint by using `response_mode=form_post`.

Since you say you went through the docs, I guess you don't know about that `response_mode` parameter.
You can see which response modes are available for which flows [here](https://github.com/IdentityServer/IdentityServer3/blob/4398f56bde322126e1a242efbc57a19c5ba0af8e/source/Core/Constants.cs#L206).
IdSrv also picks a default `response_mode` if not specified in the request [there](https://github.com/IdentityServer/IdentityServer3/blob/4398f56bde322126e1a242efbc57a19c5ba0af8e/source/Core/Validation/AuthorizeRequestValidator.cs#L222).

This is why the default response mode for the implicit flow is the URL fragment.
Hope it helps.

**Comment by leastprivilege** [comment]
Form post is not an option if you are using JS of course. In that case you might need to do a client redirect to another page after the callback has been validated.

**Comment by iLearnCEF** [comment]
Sounds good, I just need o make sure to disable back button :-), something like $state.go('someware', {}, {location:'replace'}); should do the job.

Thanks Dominick.
Also to mderriey.

**Comment by iLearnIdentityServer** [comment]
Sounds good, I just need o make sure to disable back button :-), something like $state.go('someware', {}, {location:'replace'}); should do the job.

Thanks Dominick.
Also to mderriey.
