### ISSUE TITLE
Impersonation workflow

### ISSUE THREAD

**Issue by ciriarte** [IdentityServer/IdentityServer3#2355]
Please let me know if this is the apropriate channel to ask these kind of questions.

I have an SPA where certain users with the "manager" claim can impersonate their subordinates. My current setup uses implicit flow, which is returning both an id token and an access token. My original idea was to keep the id token as the  and use it to request access tokens based on specific acr_values.

My questions are:

1. Am I reinventing the wheel?
2. Should I use something like custom grants?
3. Is there some prior art or example you guys could point me to?

Thanks!

**Comment by brockallen** [comment]
Either do the impersonation in the app itself, or you'll need a way to go to IdSvr and ask to impersonate a specific user. For the latter, the way we've done this before is to pass a custom acr_value where you pass the user id to impersonate (see the authorization endpoint docs), and in your user service's PreAuthN you can do the check on the current logged in user is allowed to do so, and if so then return a valid Authenticate result (which bypasses the login screen).

This has been asked before, so check the issue tracker history for more discussion on the topic.

**Comment by dandohotaru** [comment]
Hi, 

I've been following the threads concerning impersonation 
  https://github.com/IdentityServer/IdentityServer3/issues/560
  https://github.com/IdentityServer/IdentityServer3/issues/1465
and while it is clear that one could use the acr_value and PreAuthenticateAsync on the UserService to  control the access, i have the feeling that something is still missing in the picture.

Imagine the following scenario:
In my application (spa), I have a certain role (admin) i want to be able to impersonate specific users.
Typically the user logs in to a page, the app will decide if the user is admin, and if this is the case he gets an extra ui artifact where he can chose what user to impersonate.
This means of course that, the PreAuthenticateAsync is triggered on initial login, long before he gets the chance to specify which user needs to be impersonated (eventually via acr_value) 

Unless i am missing something obvious, Is there something flawed in my scenario or is there another approach i can deal with in what concerns impersonation?

Thanks

**Comment by brockallen** [comment]
You can always just do impersonation in the app itself without contacting the token service. So this is one option.

Another option (especially if you need impersonation at the token service) is to have the user somehow click a button or somehow trigger impersonation, which is the custom acr_values scenario back to the token service. To trigger the call to preAuthN the client app would need to pass a promp=login param to the authorization endpoint. Perhaps that's what you were missing?

**Comment by dandohotaru** [comment]
Indeed, passing the prompt login for the authorization endpoint seems to do the trick.
The _PreAuthenticateAsync_ is called upon _create token request_ and i can start making use of the associated _acr_value_
Reading the docs is a good start, but reading the specs, while a lot more tedious, surfaces quite some interesting knowledge...
The problem lies in the fact that specs tend to be intimidating when the time pressure is upon you :)
Thanks for the hint.

For further references:
http://openid.net/specs/openid-connect-implicit-1_0.html
>*prompt* 
OPTIONAL. Space-delimited, case-sensitive list of ASCII string values that specifies whether the Authorization Server prompts the End-User for reauthentication and consent. The defined values are:
* none: The Authorization Server MUST NOT display any authentication or consent user interface pages. An error is returned if an End-User is not already authenticated or the Client does not have pre-configured consent for the requested Claims or does not fulfill other conditions for processing the request. The error code will typically be login_required, interaction_required. This can be used as a method to check for existing authentication and/or consent.
* login: The Authorization Server SHOULD prompt the End-User for reauthentication. If it cannot reauthenticate the End-User, it MUST return an error, typically login_required.
* consent: The Authorization Server SHOULD prompt the End-User for consent before returning information to the Client. If it cannot obtain consent, it MUST return an error, typically consent_required.
* select_account: The Authorization Server SHOULD prompt the End-User to select a user account. This enables an End-User who has multiple accounts at the Authorization Server to select amongst the multiple accounts that they might have current sessions for. If it cannot obtain an account selection choice made by the End-User, it MUST return an error, typically account_selection_required.

>The prompt parameter can be used by the Client to make sure that the End-User is still present for the current session or to bring attention to the request. If this parameter contains none with any other value, an error is returned.
