### ISSUE TITLE
How to refresh client cookie after RequestRefreshTokenAsync

### ISSUE THREAD

**Issue by Vagele** [IdentityServer/IdentityServer3#2379]
I'm trying the following code in order to refresh the access token of the client but the cookie doesn't seem to be refeshed. What I'm doing wrong?

var refreshToken = id.FindFirst(OAuth2Constants.RefreshToken).Value;
                if (!string.IsNullOrEmpty(refreshToken))
                {
                    var tokenEndpointResponse = await tokenClient.RequestRefreshTokenAsync(refreshToken);
                    if (!tokenEndpointResponse.IsError)
                    {
                        var result = from claim in id.Claims
                                     where claim.Type != OAuth2Constants.AccessToken && claim.Type != OAuth2Constants.RefreshToken && claim.Type != "expires_at"
                                     select claim;
                        var claims = result.ToList();
                        claims.Add(new Claim(OAuth2Constants.AccessToken, tokenEndpointResponse.AccessToken));
                        claims.Add(new Claim(OAuth2Constants.RefreshToken, tokenEndpointResponse.RefreshToken));
                        var expiresTicks = DateTime.UtcNow.AddSeconds(tokenEndpointResponse.ExpiresIn).Ticks;
                        claims.Add(new Claim("expires_at", expiresTicks.ToString()));
                        var newIdentity = new ClaimsIdentity(claims, id.AuthenticationType);
                        var wrapper = new HttpRequestWrapper(HttpContext.Current.Request);
                        wrapper.GetOwinContext().Authentication.SignOut(id.AuthenticationType);
                        wrapper.GetOwinContext().Authentication.SignIn(new Microsoft.Owin.Security.AuthenticationProperties { IsPersistent = true }, newIdentity);
                        return newIdentity;
                    }
                    else
                    {
                        Logging.LogError("Access Token request error: "+ tokenEndpointResponse.Error);
                        throw new Exception("Access Token request error");
                    }
                }
                else
                {
                    Logging.LogError("Access Token request error: Refresh token does not exist");
                    throw new Exception("Access Token request error: Refresh token does not exist");
                }

**Comment by mderriey** [comment]
I've never implemented this but I had to think about it, so here's my take.

You'd have to store both the access token and the refresh token in the cookie.
The idea is then to hook in the Cookie middleware so that on each request, you inspect the access token, and if you decide it's time to refresh it, do so, then issue a new cookie which expiration will match the access token one.

The way to hook logic into the Cookie middleware is use the [`CookieAuthenticationOptions.Provider`](https://msdn.microsoft.com/en-us/library/microsoft.owin.security.cookies.cookieauthenticationoptions.provider(v=vs.113).aspx#P:Microsoft.Owin.Security.Cookies.CookieAuthenticationOptions.Provider) property.
It exposes several hooks - which can be seen as events - in the process. The one you'd be interested in is the [`ValidateIdentity`](https://msdn.microsoft.com/en-us/library/microsoft.owin.security.cookies.icookieauthenticationprovider.validateidentity(v=vs.113).aspx#M:Microsoft.Owin.Security.Cookies.ICookieAuthenticationProvider.ValidateIdentity(Microsoft.Owin.Security.Cookies.CookieValidateIdentityContext)). At this point, the session cookie has been verified by the middleware and you're given access to the `ClaimsIdentity` which contains the access token and the refresh token, allowing you to check the expiration time of the former.

Where I got stuck when I tried to implement that is how to issue a new cookie after refreshing the access token.
I tried several things, but none worked as intended. I'd be keen to get some guidance on that if somebody knows how to do it.

Cheers

**Comment by Vagele** [comment]
Well, that is what we are doing. We inspect the expiration time in every request and we issue a new accesstoken if we need to. The problem is that after we get the new accesstoken we do a signout and signin. From the documetation the signout clears the cookie and the signin creates a new one. This does not happen (at least in our case), beacause in every call the cookie contains the old accesstoken.

Do we have to do something more instead of just signout and signin?

**Comment by leastprivilege** [comment]
which cookie are you talking about? IdSrv only takes care of its own cookies. everything else is up to .

**Comment by leastprivilege** [comment]
Are you talking about updating the cookie in your client application? Well - issue a new one.

**Comment by Vagele** [comment]
Yes in client application. So sign in and sign out only updates the cookies on IdSrv. And I need to update the client cookie after the new sign in. Is there an example on how to do this? Also at the first login how is the cookie created in the client application?

**Comment by leastprivilege** [comment]
Sorry - this is not a general Katana support forum. Check their docs.

You need to create a claims identity and call SignIn on the AuthenticationManager.
