### ISSUE TITLE
User consent/authorization for periodic access

### ISSUE THREAD

**Issue by snothub** [IdentityServer/IdentityServer3#2462]
I hope I can get this clearly enough

Is it possible for a user to give consent to a client to perform actions on his/her behalf in the future without further user intervention? By that I mean if an application needs to create a task that is to be performed a month (or a year) from now, could that task be run in the context of the user logged in today? I don't want to have endless refresh tokens for that, but is there other ways of achieving that? Assume of course user is still valid, disregard the scenario of user becoming invalid / deleted / locked out for now.

Thanks

**Comment by brockallen** [comment]
That's what the offline_access scope and refresh tokens are for.

**Comment by snothub** [comment]
I thought so, that's why I mentioned I didn't want endless refresh tokens. I was hoping there was something else, better. Not sure what I expected myself... ;)

**Comment by solidstore** [comment]
I have a similar requirement, to run a task in the context of a user whilst they are offline. Is it acceptable to be continually renewing a users Refresh token so that it never expires? The tasks may be run months apart with the user never logging in again.

I'm confused with this approach and the ActAs concept - were a service user could act as the other user and perform the task in their behalf?

**Comment by brockallen** [comment]
> Is it acceptable to be continually renewing a users Refresh token so that it never expires

Yep, that's how that works. ActAs is something else.
