### ISSUE TITLE
How to protect a web page controller similar to protecting a webapi controller?

### ISSUE THREAD

**Issue by elevin9926** [IdentityServer/IdentityServer3#2498]
When consuming a WebApi I can use httpclient.SetBearerToken(), and call that webapi.
if the client consuming the webapi doesn't have the required scope, accessing that webapi method will be denied (as it should).

I want to do something similar with a web page.
here is the use case:
three web apps. all integrated with identityserver (using hybrid flow) for user authentication.
App1 is client1
App2 is client2
App3 is client3
App1 has a certain page that it allows for other apps to "consume" based on access token (protected by scope "canusewebpagex"  (or whatever)
client2 has the scope "canusewebpagex", therefore App2 is allowed to redirect to that certain web page controller in app1.
client3 does not have the scope "canusewebpagex", therefore App3 is not allowed to redirect to that certain web page controller in app1. Or if someone logs into app3, and tries to navigate directly from the browser to that web page - it will be denied.

What is the right way to achieve this?

**Comment by brockallen** [comment]
Identity tokens don't have scopes (since they're for identifying the user), so this doesn't really match what you're looking to do. Also, in web apps, you normally show the user an error page if they aren't allowed to do what they're trying to do. This is a different type of response from a programmatic client using an access token.
