### ISSUE TITLE
Cascade logout to external providers

### ISSUE THREAD

**Issue by Steve887** [IdentityServer/IdentityServer3#2582]
I have an Identity Server setup that uses Google as an external identity provider that works correctly for both login and logout.

However, if I log out of my application, then go to a Google site (www.gmail.com for example) I am still signed in with the account I used for the external login.

Is there a way to configure Identity Server to also log out of the external provider, or failing that, what is the best practice recommendation for this? Currently it makes it look like you're logged out when in reality you are only logged out of the application, not any external providers used.

**Comment by mderriey** [comment]
I don't think the intent of having external identity providers is to be able to log out of them when you log out of the application.
IdSrv is only concerned about the login status of a user against IdSrv.

It actually makes a lot of sense. Just because I used my Google account to sign in on a website doesn't mean I want to be logged out of my Google when I log out of that website.
External identity providers allow users to log in to IdSrv without having a local account, that's all.

**Comment by leastprivilege** [comment]
That's not quite true - it is actually a concern to logout users upstream when they logout from idsrv.

Some protocols and middleware (e.g. ws-fed and SAML) support federated logout and idsrv coordinates those interactions. IIRC the google middleware does not implement that.

**Comment by mderriey** [comment]
Whoops, sorry, I didn't know that.

**Comment by Steve887** [comment]
Even if you believe it's not the job of IdSrv to log out of upstream providers, you have to agree that it's still a UX requirement to at least inform the user of that.

I'd be interested in how other applications handle this, if at all.

**Comment by brockallen** [comment]
> Even if you believe it's not the job of IdSrv to log out of upstream providers

Agreed, and thus it's the host developer's code in any external authentication middleware to make this call.
