### ISSUE TITLE
Support RedirectUri on SignOut for external providers

### ISSUE THREAD

**Issue by brockallen** [IdentityServer/IdentityServer3#2613]
Set AuthProps w/ RedirectUri so consumers don't manually need to do the callback when we're logging out of external MW.

**Comment by brockallen** [comment]
Done.

**Comment by parkinsona** [comment]
Hi Brock,

I have been using Kentor Authservices and the post logout redirect url is not appearing on the logout page for me when the user was logged in from a SAML provider. It is working for identityserver logins and for the google provider.

@AndersAbel , recommended discussing it on the idsvr site because I'm using the single logout feature of AuthServices. He thinks it should just work by adding the new EnableAutoCallbackForFederatedSignout  option.

I think I'm missing something still though.

**Comment by torbadshaug** [comment]
did you solve this @parkinsona? We are experiencing something similar. The signout message-id is lost by the time we hit /logout.
Before upgrading to 2.5 we had it working "manually" (using the setup from https://identityserver.github.io/Documentation/docsv2/advanced/federated-post-logout-redirect.html).
We are using the WsFederation middleware against our upstream provider.

**Comment by parkinsona** [comment]
Hi,

We haven’t been able to solve this yet.
