### ISSUE TITLE
Permissioning multiple applications

### ISSUE THREAD

**Issue by JSpate** [IdentityServer/IdentityServer3#2679]
I am new to the Identity Server World, but so far my implementation is going OK, I have implemented the client credential flow for inter app communication without any issues and have the hybrid flow for user login working. I have also implemented an IUserService to return claims based on the user and calling application so that I can have individual roles per application.

The issue I am having is when I have two or more apps, when the user logs into the first application using the hybrid flow and then navigates to the second the permissions in the second application are not the ones specific to that application. As far as I can see the permissions are set in a cookie by the first app and then used by the second???

So the question is, is there a way around this or should I create a role provider service to deal specifically with permissions?

**Comment by brockallen** [comment]
It sounds as if you're asking how to get different claims in different clients?

**Comment by JSpate** [comment]
Yes, I am creating different claims but all clients are getting the same ones

**Comment by thabart** [comment]
There's something strange in your proposed architecture, i don't think it's up to identity server to do this kind of thing. Instead of doing the mapping between roles & clients inside your IUserService implemention, why do-you not create a 'security' API ?
We can imagine an operation protected by Client-Credentials flow (for example) which returns a list of roles based on the application id passed in the query. The issue you're explaining there is very specific to your requirements, try to separate the concerns.

**Comment by JSpate** [comment]
Okay, my misunderstanding, I assumed roles were roles within a single client, not roles across all clients. I will go down the security API route, thanks :)
