### ISSUE TITLE
Should IClientStore.FindClientByIdAsync(clientId) return disabled clients

### ISSUE THREAD

**Issue by TimMurphy** [IdentityServer/IdentityServer3#2858]
- [x] I read and understood how to enable [logging](https://identityserver.github.io/Documentation/docsv2/configuration/logging.html)

### Question / Issue

Should IClientStore.FindClientByIdAsync(clientId) return disabled clients? I haven't found any documentation supporting an answer so I'm using [InMemoryStore](https://github.com/IdentityServer/IdentityServer3/blob/master/source/Core/Services/InMemory/InMemoryClientStore.cs) & [EntityFramework](https://github.com/IdentityServer/IdentityServer3.EntityFramework/blob/master/Source/Core.EntityFramework/Stores/ClientStore.cs) as a guide. InMemoryClientStory explicitly returns enabled clients only. EntityFramework appears to return enabled & disabled clients.

### Relevant parts of the log file

N/A

**Comment by lukos** [comment]
Personally, I think it should, since it has an Enabled property in Client, it wouldn't make much sense if they weren't returned. In the AuthorizeRequestValidator, it explicitly checks for Enabled before allowing login but there are other places where it is not checked (such as logout), which might be intentional - allowing someone to logout from a client who has recently been disabled?

**Comment by brockallen** [comment]
It shouldn't matter. I don't recall why we filtered in the in-mem implementation.

**Comment by TimMurphy** [comment]
Should this fact be added to [IClientStore](https://github.com/IdentityServer/IdentityServer3/blob/master/source/Core/Services/IClientStore.cs) documentation? Do you want a PR?

**Comment by brockallen** [comment]
If you think it'll help the docs, sure.
