### ISSUE TITLE
Approach to Restrict User to an Application, Obtain application user Role.

### ISSUE THREAD

**Issue by Sivalingaamorthy** [IdentityServer/IdentityServer3#2956]
This approach am planning after doing concise research on the blog posts & question answers of ids3 implementation, I just want to get it opinions on this.

Since am using Ids3, same user can access two application ( App 1 & App 2 ) - SSO implemented.

For few users, want to restrict access to App 2.

As a best practice am isolating the Role management and Application authorization to the limit of the application. 

To cater this isolation, planning that each application ( app 1 & app 2) will expose two endpoints to the ids3, one to getUserRoles & the other to check if user has access to the application.

To get the user role, after successful authentication, the CustomUserService implementation (IUserService), the GetProfileDataAsync method will call the applications getUserRoles endpoint and obtain the user specific roles to the application and add it to the user claims. (so now the claim will have the user role details)

To restrict user to an application, am planning to use - ICustomRequestValidator, so after the user got authenticated, the  CustomRequestValidator, will make a call to the client endpoint to check if the user has access to the application or not. (this approach will restrict the user to the application)

So I am expecting the need to restrict User to an Application & obtain application user role can be done. Is there any better way?

**Comment by dealproc** [comment]
Authorization is application specific, and is best kept within each respective application.  When I first got into SSO with IdSrv, I had a similar mental view of how I saw IdSrv fitting into the networked ecosystem.

Why not utilize the basic OpenID/OAuth credential to app1 and app2 respectively, then once there, use a claims transformation to adjust the claimsprincipal to provide the access details you need in each application (within an Owin pipeline, for instance).  This will keep your app1 and app2 further isolated from the central idsrv, and you are just using idsrv as a centralized authentication tool, rather than a full user manager.

What we did to setup provisioning to make it somewhat easy was we built a custom provisioning portal that can talk to an internal api for each application.  we manage the group/role/permission/user assignments for each application from this centralized portal.

**Comment by Sivalingaamorthy** [comment]
Hi Dealproc, Thanks for acknowledging the approach.

I am curious, can you shed some light on the below statement, with some reference or example solution.

> Why not utilize the basic OpenID/OAuth credential to app1 and app2 respectively, then once there, use a claims transformation to adjust the claimsprincipal to provide the access details you need in each application (within an Owin pipeline, for instance).

**Comment by brockallen** [comment]
To improve discoverability of frequently asked and/or more general questions, we decided to move those questions to StackOverflow:

https://stackoverflow.com/questions/tagged/?tagnames=identityserver3&sort=newest

We actively monitor SO as well but hope to create a community there so questions can get answered faster when we are not available.
