### ISSUE TITLE
GetIdentityServerIssuerUri - returns address wth trailing '/'

### ISSUE THREAD

**Issue by pawepaw** [IdentityServer/IdentityServer3#2994]
Hello,

I was fighting for a wile with some problem. I started using owin extension ```IssueClientToken(client,scope,expiration)``` which replaced previously http call with token client. 

Token generated with IssueClientToken extension was failing validation with message "invalid_token". After short ivnestigation i've found that if issuer uri is defined in application ```GetIdentityServerIssuerUri``` will not remove trailing slash https://github.com/IdentityServer/IdentityServer3/blob/ea62f859ccc4a2554e73fcec544d7a34e8d31682/source/Core/Extensions/OwinEnvironmentExtensions.cs#L678
and ```IssueClientToken``` will generate token with audience containing double slash like: ```http://localhost:55005//resources ``` and it will fail token validation.
https://github.com/IdentityServer/IdentityServer3/blob/ea62f859ccc4a2554e73fcec544d7a34e8d31682/source/Core/Extensions/OwinEnvironmentExtensions.cs#L712

I think you should always remove trailing slash in GetIdentityServerIssuerUri extension not only for automatically generated one.

**Comment by leastprivilege** [comment]
@brockallen could you look into that please?

**Comment by ArturDorochowicz** [comment]
I'm experiencing the same issue.

The problem is that `OwinEnvironmentExtensions.IssueClientToken` uses a different template to create the audience string.

In `IssueClientToken` we have [1]:
```
var issuerUri = env.GetIdentityServerIssuerUri();
/* ... */
Audience = issuerUri + "/resources",
```
In other parts of the code we have [2] [3]:
```
string.Format(Constants.AccessTokenAudience, IssuerUri.EnsureTrailingSlash()),
```
which uses `AccessTokenAudience` format string:
```
 public const string AccessTokenAudience = "{0}resources";
```

So, the solution to the issue should be to use the same approach and pattern in `IssueClientToken` as in other places.


[1] https://github.com/IdentityServer/IdentityServer3/blob/ea62f859ccc4a2554e73fcec544d7a34e8d31682/source/Core/Extensions/OwinEnvironmentExtensions.cs#L717
[2] https://github.com/IdentityServer/IdentityServer3/blob/ea62f859ccc4a2554e73fcec544d7a34e8d31682/source/Core/Services/Default/DefaultTokenService.cs#L215
[3] https://github.com/IdentityServer/IdentityServer3/blob/ea62f859ccc4a2554e73fcec544d7a34e8d31682/source/Core/Validation/TokenValidator.cs#L175
