### ISSUE TITLE
Implement Dynamic Registration

### ISSUE THREAD

**Issue by leastprivilege** [IdentityServer/IdentityServer3#308]
http://openid.net/specs/openid-connect-registration-1_0.html

**Comment by subsci** [comment]
As to **users self-registering**  [with email verification and password reset] (http://www.asp.net/mvc/overview/security/create-an-aspnet-mvc-5-web-app-with-email-confirmation-and-password-reset), the out of the box AspNetIdentity VS2013 MVC Individual User Accounts persists registrations to a DB.  

Availing of the template MVC code for user management, I, by design, retooled that MVC client to offer only  `UseOpenIdConnectAuthentication(..)`. A separate `IdentityServer3` with `AspNetIdentity` references the same user DB. 

While tweaking the out of box MVC client user-self-management, e.g. change or forgot password,
I saw the `Controller.User` (Current HTTP Request context) is missing claims that exist in the `Request.GetOwinContext().Authentication.User`.

Is it a good idea to make the two `ClaimsPrincipal` match? 

If so where is this done? I don’t know? What about
`OpenIdConnectAuthenticationNotifications.SecurityTokenValidated` or 
`Application_PostAuthenticateRequest`

**Comment by tugberkugurlu** [comment]
:+1:

**Comment by rdzidziguri** [comment]
@leastprivilege Any update or news about this topic? We all think this is really cool if we could have self service for client registration with identity server 3

**Comment by leastprivilege** [comment]
Sure - but why as part of identity server core? This is IMO a client to identityserver that happens to have write access to the client store. Feel free to contribute that.

**Comment by tugberkugurlu** [comment]
@leastprivilege but isn't this a defined OpenId Connect standard? http://openid.net/specs/openid-connect-registration-1_0.html 

So, it should be available as endpoints as well or am I understanding your last comment wrong (which is highly likely :smile:)?

**Comment by johnkors** [comment]
@tugberkugurlu Pretty much says client all over that spec. :) See section 3.  "Client registration" .

**Comment by tugberkugurlu** [comment]
@johnkors yes, isn't this issue about dynamic client registration? see: https://github.com/IdentityServer/IdentityServer3/issues/308#issuecomment-60876193

**Comment by johnkors** [comment]
ah, sorry - i mistook (is that even a word..) you for another dev asking about user registration in this issue. My bad :S

**Comment by leastprivilege** [comment]
yeah - i am reluctant to add that as part of core. For 98% of the time core has only read access to the underlying data structures - and I like that for keeping the attack surface small.

I could rather see the dynamic client reg endpoint as part of an admin lib/api/UI. Anyone wants to build that? ;)

**Comment by tugberkugurlu** [comment]
@leastprivilege hmm, so it would end up here, correct? https://github.com/IdentityServer/IdentityServer3.Admin/tree/dev

**Comment by leastprivilege** [comment]
Not sure we will go forward with that. But from a separation of concerns point of view I see that rather in an admin "piece".

**Comment by leastprivilege** [comment]
no dynamic reg in core.

**Comment by AndrewSav** [comment]
> Not sure we will go forward with that. But from a separation of concerns point of view I see that rather in an admin "piece".

Understood this is not going to be in Core. However in the [admin discussion](https://github.com/IdentityServer/IdentityServer3.Admin/issues/15) they point out (and this is fair enough IMO) that they are are separate application from Identity Server, they call Identity Server endpoints, and registration *is* a protocol endpoint.

So to me it looks like it's definitely a contrib type of functionality, rather than clear cut "admin".

I was wondering, if someone decided to implement it, would it be a reasonable approach to create another interface IWritableClientStore : IClientStore that would be wired up to the "register" endpoint similar way as all other endpoints in IdentityServer are implemented. It's than up to the interface implementer to provide that actual store for this information. 

Does this sound a reasonable approach?

**Comment by brockallen** [comment]
Just make it another interface in another repo for another context. No need for forced reuse.

**Comment by AndrewSav** [comment]
So the goal of the suggestion was integration not reuse. I was looking for a ways to implement the new functionality "the Identity Server way" so that the code base and usage is easy to understand to those familiar with code base and usage of the Identity Server. 

To me it looks like it should be relatively easy to keep the same interface style and the same components layout. From your comment above it seems that you disagree, Would it be possible for you to expand a little bit on that, and explain why.

I outlined the similarities - DCR is also an endpoint somewhat similar to other endpoints in Identity Server, and to address the concern about read-only api, I mentioned that it can be done as a contrib, and the non-read-only part can be abstracted away via a store interface like everything else in Identity Server.

Thus I'm a bit perplexed about the comment renegading forced re-use. It seems that you suggest, that there is no similarities, and no reason to keep consistency.  I would appreciate it if you could explain that. to me Many thanks.
