### ISSUE TITLE
Where should custom claims "live"

### ISSUE THREAD

**Issue by scottlance** [IdentityServer/IdentityServer3#3174]
This is more of a academic question.  I've read the OIDC Spec and some of the issues and guidance on the questions on this project but I really haven't found an authoritative answer to this question:

Where should custom claims live?  In the Identity Token, the Access Token or the User Profile?

I want to rule out the Access Token for the custom claims since access tokens should be used for well... access.

The OIDC Spec says that the email and address claims are part of the standard claims and are returned from the UserInfo endpoint if they are specified as part of the scope for the OIDC request.  Should other custom claims for business purposes be returned from the UserInfo endpoint and be accessed by custom scopes, or should they be put in the Identity Token?

The Section 2 of the OIDC spec says:

_"ID Tokens MAY contain other Claims. Any Claims used that are not understood MUST be ignored. See Sections 3.1.3.6, 3.3.2.11, 5.1, and 7.4 for additional Claims defined by this specification."_

So ID Tokens can have contain other claims, but _should_ they?

Section 5.1.2 says:

"_5.1.2.  Additional Claims_

_While this specification defines only a small set of Claims as standard Claims, other Claims MAY be used in conjunction with the standard Claims. When using such Claims, it is RECOMMENDED that collision-resistant names be used for the Claim Names, as described in the JSON Web Token (JWT) [JWT] specification. Alternatively, Private Claim Names can be safely used when naming conflicts are unlikely to arise, as described in the JWT specification. Or, if specific additional Claims will have broad and general applicability, they can be registered with Registered Claim Names, per the JWT specification._"

This section sets out that other claims can be added, but it really doesn't describe where they should be emitted from (id_token, UseIinfo endpoint)

Both of these sections (2 and 5.1.2) vaguely say that additional claims can be added to either the ID Token or as additional claims in the UserInfo endpoint, but nether statement is authoritative in its guidance. 

My best thoughts for this at the moment are that authoritative claims like roles should live in the ID Token and that informational claims like say favorite color should be returned as part of a UserInfo request.

Thoughts?

**Comment by brockallen** [comment]
Hey Scott --

id_tokens are meant for the client app. access tokens are meant for apis. 

For the client app claims can come in the id_token, or the user info endpoint. The real difference is performance. If all the claims go in the id_token, then it can get big. If it's sent as a form post, then size is not a concern. If your app will not handle a large id_token (via hash fragment for example) so that's why the user info endpoint is an alternative (at the expense of another round trip).

We support a mix of these configurations and it all boils down to the nature of the client app, and which claims do you want where (id_token or user info endpoint). 

HTH

**Comment by scottlance** [comment]
Thanks for the explanation.
