### ISSUE TITLE
Reverse proxy and Google authentication

### ISSUE THREAD

**Issue by AlbertoCe** [IdentityServer/IdentityServer3#3198]
Hello,

I have the identity server behind a reverse proxy. When I set the PublicOrigin all seems to work fine but the authentication with Google idp does not work: when I click on "Google" button the browser is not redirected to "https://accounts.google.com/o/oauth2/" but try to open the "https://IDENTITYSERVER_SITE/o/oauth2/" page.

Do you know what could be causing it ?

**Comment by brockallen** [comment]
No idea. Seems like something in the Google middleware...?

**Comment by seinti** [comment]
I had the same issue when using IIS ARR Proxy. I was able to get to the next step by unchecking "Reverse rewrite host in response headers" in the ARR Proxy settings page.

Now I still have the issue of the redirect URI sent to google using the IP address instead of the public origin address. The katana Google middleware should perhaps allow to explicitly set the redirect_uri.

**Comment by brockallen** [comment]
Any update?

**Comment by AlbertoCe** [comment]
No, I tried in may way to configure the IIS ARR but with no luck.
I tried to unthick the Reverse rewrite host in response headers but when I request the url without a trailing slash,  the courtesy redirect of IIS try to redirect me to the internal website and not the public one.
Moreover, when I click the Google button, Google tell me that "Invalid parameter value for redirect_uri: Non-public domains not allowed: "

**Comment by brockallen** [comment]
Why not just set the host on the incoming HTTP request in a middleware in front of IdentityServer and the google MW?
