### ISSUE TITLE
IdentityServer3 - Client assertion (client_secret_jwt) support?

### ISSUE THREAD

**Issue by myaesubi** [IdentityServer/IdentityServer3#3317]
Hello,

I'm not sure whether this is a repetitive question or not, I couldn't find references to it though.

As OpenId Connect spec: 

> token_endpoint_auth_methods_supported
OPTIONAL. JSON array containing a list of Client Authentication methods supported by this Token Endpoint. The options are client_secret_post, client_secret_basic, client_secret_jwt, and private_key_jwt, as described in Section 9 of OpenID Connect Core 1.0 [OpenID.Core]. Other authentication methods MAY be defined by extensions. If omitted, the default is client_secret_basic -- the HTTP Basic Authentication Scheme specified in Section 2.3.1 of OAuth 2.0 [RFC6749].

> 

and as I read some of the code for discovery metadata in IdentityServer3, out-of-the-box there is support for "client_secret_post", "client_secret_basic" auth methods.

I wonder there is implementation to support _**"client_secret_jwt"**_ in the IdentityServer3. I have a client which only supports **client_secret_jwt** auth method to connect to the Identity Provider and I have implemented my IdentityProvider based on IdentityServer3 framework

Thanks in advance,
Mohammad

**Comment by leastprivilege** [comment]
Yes - there is. You need to add the validator and parser manually though 

@uncleyo can help.

**Comment by uncleyo** [comment]
Actually there isn't :)

I didn't dare adding support for "client_secret_jwt" since that requires storing all client secrets in plaintext server-side.
There is support for "private_key_jwt", which is similar, but using asymmetric crypto signature for tokens, like RS256 (just like the tokens IdentityServer3 issues).

You can still add support yourself if you really want, since IdentityServer3 has really great abstractions for plugging in new authentication types. Check [parser](https://github.com/IdentityServer/IdentityServer3/blob/master/source/Core/Validation/ClientAssertionSecretParser.cs) and [validator](https://github.com/IdentityServer/IdentityServer3/blob/master/source/Core/Validation/PrivateKeyJwtSecretValidator.cs) for inspiration.

**Comment by leastprivilege** [comment]
Right - I missed that little detail - @uncleyo is right.

**Comment by myaesubi** [comment]
Thanks @damianh @uncleyo .
I pursue that path then. One last question:

The client only supports Implicit flow and the client secret is just another layer of validation.
Does this look odd to you that given with support of Implicit flow only, just "**_client_secret_jwt_**" is supported by client app?

Thanks again,
Mohammad

**Comment by leastprivilege** [comment]
This does look odd, because implicit flow clients have no secret at all.

**Comment by myaesubi** [comment]
Thank you.
Mohammad
