### ISSUE TITLE
Cancel option on logout custom view

### ISSUE THREAD

**Issue by arias-estrada** [IdentityServer/IdentityServer3#3325]
I am using the CustomViewService sample, and I realized that the logout view doesn't have the "No" or "Cancel" option.
Wouldn't be great to have this option in case of I change my mind or have clicked SignOut by accident?
What ULR should I pass to return to in case I want to build a custom button?

**Comment by brockallen** [comment]
> Wouldn't be great to have this option

Perhaps, but the result of clicking this button is probably not what you want to happen back in the client. The outcome would be an access_denied result to the client.

> What ULR should I pass to return to in case I want to build a custom button?

That's the problem -- the protocol only knows about the callback URI, and since clicking "no" or "cancel" in the login would mean an error back to the client.

**Comment by arias-estrada** [comment]
Don't we know all this information from the login request?
Why can't it be used here?

**Comment by brockallen** [comment]
There's an old thread somewhere in the history where we discussed this in some length. See if you can find it.
