### ISSUE TITLE
How can I create the cache management for the reference token?

### ISSUE THREAD

**Issue by Jenan** [IdentityServer/IdentityServer3#3388]
Hello,

I've read the documentation before `deploy` to the production server and I've found the part about solving the cache for reference token (this type of token I want to use primary):
https://identityserver.github.io/Documentation/docsv2/consuming/options.html

Here is recommendation to use own implementation of cache for optimalization.
Is it some starting example where is this implemented?
Thank you for some tips.

**Comment by leastprivilege** [comment]
The default cache is in-memory. If that's good enough - that's all you need.

Otherwise have a look at the caching interface and implement it using your caching system:
https://github.com/IdentityServer/IdentityServer3.AccessTokenValidation/blob/master/source/AccessTokenValidation/Plumbing/ICache.cs

**Comment by Jenan** [comment]
Yes, we have a web farm, therefore I want to find the caching for this scenario.
I have no experiences with caching in .NET. 
Is there any example of implementation with the identityserver and caching for the web farm solution?

**Comment by leastprivilege** [comment]
You first need a distributed caching product like Redis. Then you use their API to implement the caching interface.

I don't have a sample.
