### ISSUE TITLE
Home Realm Discovery and ADFS 

### ISSUE THREAD

**Issue by jheckathorn** [IdentityServer/IdentityServer3#3393]
I really need an answer for this one, please.

When connecting to an ADFS IdP, on the first login request you get a list of relying parties. Once you have selected one for login your choice is stored in a cookie and on future logins you will not be asked again to select a relying party.

Using the CustomHrd sample, on the first login request you are asked for your email and the correct relying party is determined from the user's email. Once the reply party has been determined it is still stored in a cookie, however, when you attempt to login again in the future you will again be asked for your email.
 
I would like to know how I can detect that the relying part has already been stored in a cookie so that I can skip asking the user for their email again.

Thank you in advance for your assistance.

Update:
I find this deeply frustrating as this is the third inquiry that has gone unanswered.

**Comment by brockallen** [comment]
Sorry for the delay. This would normally be a question for SO, but since I'm here: I've not tried to do what you're asking for, but I'd try by doing something in your custom user service in the AuthenticateExternal and PreAuthenticate methods. In short, you can issue cookies in AuthExternal, and then read it in PreAuth and set IdP on the signin message to skip the login UI.
