### ISSUE TITLE
Support application/json requests

### ISSUE THREAD

**Issue by pboling** [IdentityServer/IdentityServer3#3468]
- [x ] I read and understood how to enable [logging](https://identityserver.github.io/Documentation/docsv2/configuration/logging.html)

### Question / Issue

IdentityServer3 does not support requests for tokens in JSON format, despite that appearing to be the intent.  Is there a reason?  Can it be enabled?

Looks good in `PreventUnsupportedRequestMediaTypesAttribute`
https://github.com/IdentityServer/IdentityServer3/blob/master/source/Core/Configuration/Hosting/PreventUnsupportedRequestMediaTypesAttribute.cs

But then it falls apart in the `TokenEndpointController`
https://github.com/IdentityServer/IdentityServer3/blob/master/source/Core/Endpoints/Connect/TokenEndpointController.cs#L37
https://github.com/IdentityServer/IdentityServer3/blob/master/source/Core/Endpoints/Connect/TokenEndpointController.cs#L70

**Comment by brockallen** [comment]
The spec requires form-urlencoded.

**Comment by pboling** [comment]
The spec "requires" that it support form-urlencoded.  Does the spec explicitly say that *also* supporting JSON would invalidate spec compliance?  Not sure why support for one implies non-support of the other, unless it explicitly says something to that effect.

**Comment by leastprivilege** [comment]
Let me read the spec for you ...

> The client makes a request to the token endpoint by sending the
   following parameters using the "application/x-www-form-urlencoded"
   format per Appendix B with a character encoding of UTF-8 in the HTTP
   request entity-body:

**Comment by pboling** [comment]
And I have USB stick that is Mac and Windows compatible.  What is your point?

**Comment by brockallen** [comment]
Perhaps you're right, but where do you stop and what's the benefit? Clients should also be following the spec, since that's what this is -- a spec compliant OIDC implementation. If they're not also following the spec, then you're in the world of your own custom security plumbing. This is FOSS, so feel free to fork.

**Comment by pboling** [comment]
> what's the benefit (of having an API that is JSON front to back)?

> I would like my JSON API to be all JSON, so I can use global request handlers in my javascript, C#, and Ruby, that wrap / validate / debug / log / enhance all requests the same way without if isJson? switches everywhere.

For now my request handlers will have to handle non-JSON requests when every single other request they make will be JSON.

Forking for this change, if the change would not be accepted upstream, is a commitment to understanding and maintaining this code base which I cannot make.  We'll deal with bifurcated request handlers until we replace our IdentityServer3 with a JSON OAuth provider.

**Comment by megamindbrian** [comment]
@brockallen @leastprivilege  Change the spec then.  Why should a compliant JSON web token generating service be incompatible with accepting JSON?

The issue I have seen is the web browser's implementation of URLSearchParams is different across different browsers.  Some encode spaces to a space and some encode spaces to a plus symbol.  When using an email address with a plus in it for testing Identity server "falls apart".  Can't process requests because of encoding isn't a problem with the specification, it's a problem with the design and usability.

http://caniuse.com/#feat=urlsearchparams
