### ISSUE TITLE
Question: How to authenticate against different user stores based on requesting client

### ISSUE THREAD

**Issue by garymacpherson** [IdentityServer/IdentityServer3#3569]
I have a basic implementation of IDSV3 and am trying to extend it so that if a login request is coming from webapp1 my code will attempt to authenticate the details against authapi1, while webapp2 goes to authapi2 etc.

My current approach from the readings I have done is to define my IdentityServerServiceFactory with a custom user service

    factory.UserService = new Registration<IUserService, MyCustomUserService>();

And then inside the custom user service I need to get the client id for that request and then start splitting my logic depending on the result?

    public class MyCustomUserService : UserServiceBase
    {
        public MyCustomUserService(IClientStore clientStore)
        {
            
        }

        public override Task AuthenticateLocalAsync(LocalAuthenticationContext context)
        {
            return base.AuthenticateLocalAsync(context);
        }
    }

Am I correct so far? I am getting stuck on trying to get the Client ID within the custom user service.

**Comment by leastprivilege** [comment]
the authentication context has a SignInMessage which has a ClIentId.

**Comment by brianwagg** [comment]
Is this the recommended approach for doing this (have a single custom user store that has the logic for sending requests where they need to go)? 
We are looking at doing the same thing and were looking at using the ACR_VALUES provide which IDP we wanted to use (i.e. Windows, Facebook, etc). That all seemed to work out of the box, but when trying to use the Resource Owner Password Flow it hits the AuthenticateLocal of the backing UserService and doesn't get handed off to the provider supplied. 
I'm guessing we have to make that work on our own? There is nothing out of the box that supports this?

**Comment by brockallen** [comment]
>  Resource Owner Password Flow it hits the AuthenticateLocal of the backing UserService and doesn't get handed off to the provider supplied

External authentication must go thru the authorization endpoint. Resource owner only works if you own the passwords.

**Comment by brianwagg** [comment]
So effectively you are saying I can't do what I wanted to.

Details if you have the time/desire to read them:
What I had hoped to achieve was a root IDP based on IdSvr3 that federates with an A.D. and Windows Auth instance (and maybe others). My client app would know about the root one and through ACR Values would request whichever version it wanted (this works out of the box as I mentioned).
The key of what I wanted to solve was the situation where some of our API's are being called by other products that are not integrated with our root IDP. Therefore, we have to authenticate them differently currently, because they don't know how to get a token.
I had hoped, that I could construct an API they could call that would generate them a token from our system (by using the resource owner password flow) so that our internal system wouldn't need to know how to authenticate certain API calls one way vs. another - they would all be the same token structure.

So they would call "GenerateToken()" with some parameters/auth information.
We'd generate an access token based off that information and pass it back.
They then would use that token for their subsequent API calls.

Is there a pattern out there somewhere that does this?
NOTE: I wanted to use the flow in question because I wanted the user to be in the access token as a claim, just like we have in our main system. I could use the client credentials flow, but have no way of knowing who the end user was that was executing the call chain.

Thanks

**Comment by brockallen** [comment]
If the backing password store provides you an API to validate the credentials, then you can get it to work. Google and Facebook won't let you do that, but if you own the AD then that's possible.

Having said that, the recommendation is to pop a browser from a native client (which is my guess as to your scenario). Resource owner password flow is only in the spec as a migration fro legacy apps, or as a "last resort". 

There are lots of threads about this topic in the archive here.

**Comment by brianwagg** [comment]
I appreciate the response. Seems like I'm trying to do something that shouldn't be done, but the use case seems very valid to me.

It's not a native client but another application that calls our services and subsequently would need a token for us to validate the request. We were trying to make it easier for that system to get a token by calling an API within our stuff - and we would house the configuration/logic for how to get a token (more like server to server communication). 

I'll dig through some more of the archives and also check out the various authorization endpoint capabilities.

**Comment by brockallen** [comment]
> more like server to server communication

This sounds like client credentials flow to me, not resource owner password flow.

**Comment by brianwagg** [comment]
Which it is - except I want to have the user as a claim so I know who initiated it.
The client credentials flow doesn't allow for this.
So I had hoped by having the username/pwd to pass in, I could authenticate it and get that in the claim.

**Comment by brockallen** [comment]
Well, as I said, that only works if you can contact the password database to validate the user's password. To authenticate to external providers (such as Facebook), you need to redirect the user in the browser.

**Comment by brianwagg** [comment]
And I can - for our A.D. scenario. Except I don't see how that actually will work and I'd be able to get a token from the root IDP instance. 
It seems I would either need logic in that root IDP User Service to submit a request to A.D. and validate OR I need to contact the A.D. level stuff directly which isn't going to generate the appropriate token.

So the validation can be done, but I am not sure the appropriate way to generate the token correctly.

**Comment by brianwagg** [comment]
Given that the other providers wouldn't work this way anyways - it seems like I should just adjust somehow and work around it another way. 

I appreciate your time!
