### ISSUE TITLE
Using Identity Server to do Windows + Forms Authentication in MVC app

### ISSUE THREAD

**Issue by arc95** [IdentityServer/IdentityServer3#3572]
Hi all. We have an ASP.NET MVC 5 app that has Windows authentication enabled. Currently, it seamlessly lets the users on a few AD groups enter and run the app. Here's the pertinent section of Web.config:

	<system.web>
		<authentication mode="Windows" />
		<authorization>
		  <deny users="?" />
		</authorization>
	</system.web>

And here's the Global.asax.cs, which provides access to the app based on AD groups; we plan to move the authorization to each controller/action:

	protected void Application_Start()
	{
		AreaRegistration.RegisterAllAreas();
		GlobalConfiguration.Configure(WebApiConfig.Register);
		FilterConfig.RegisterGlobalFilters(GlobalFilters.Filters);
		RouteConfig.RegisterRoutes(RouteTable.Routes);
		BundleConfig.RegisterBundles(BundleTable.Bundles);

		GlobalFilters.Filters.Add(new System.Web.Mvc.AuthorizeAttribute() 
                       { Roles = "AD-Group, Other-AD-Group" });
	}

We'd like to use Identity Server to authenticate the user against Windows first; if that fails, then we know they are external users with no AD account. We'd send them to a login page. There, we'd like to authenticate them against user tables on SQL Server (Forms Authentication). 

Regardless of how the user is authenticated, we'd like to fetch the person's roles from a SQL Server `UserRoles` table and maintain that information for the duration of the session. We could have AD groups for the roles, but that can become unwieldy with a dozen roles. 

Is such a thing possible with Identity Server? From what I've read, it's not, but wanted to get your input as to best practices and a good approach/alternative to what we're trying to do.

Thank you.

**Comment by thegreatpl** [comment]
Been a while since I've done anything with Identity Server, and never really done any AD integration or with MVC. I'd suggest taking a look at the example code, as it is pretty well fleshed out and should give you the basics.  From what I recall doing however, you can implement the check in the IUserService implementation, which is unique to your server. This is what actually handles the authentication. 

The function "public Task AuthenticateLocalAsync(LocalAuthenticationContext context)" is what is used for sign in (when not using someone like Google or Microsoft). You can easily do the AD connect in here, and if that fails, then check the SQL server.

**Comment by theythinkimmexican** [comment]
have a look at https://github.com/IdentityServer/WindowsAuthentication
