### ISSUE TITLE
UserService.IsActive not affecting response

### ISSUE THREAD

**Issue by tbrettallen** [IdentityServer/IdentityServer3#3617]
- [ x ] I read and understood how to enable [logging](https://identityserver.github.io/Documentation/docsv2/configuration/logging.html)

### Question / Issue

QA team reported that inactivated users were not prevented from accessing APIs so I changed IsActiveAsync to the following:

```
        public override Task IsActiveAsync(IsActiveContext context)
        {
            if (context.Subject == null)
                throw new ArgumentNullException(nameof(context.Subject));

            return Task.FromResult(false);
            // return Task.FromResult(UserManager.GetUser(context.Subject)?.Enabled ?? false);
        }
```
I set a breakpoint in IsActiveAsync, and when I call the `/connect/accesstokenvalidation?token={{access_token}}` it correctly goes through the IsActiveAsync method. However even though it always returns false, the accesstokenvalidation response returns as if it's a valid token:

```
{
  "aud": "https://localhost:44333/resources",
  "iss": "https://localhost:44333",
  "nbf": 1491240066,
  "exp": 1491243666,
  "client_id": "F1.Mobile", 
  // <snip>
}
```

instead of the expected

```
{
  "Message": "invalid_token"
}
```

When and how should I use IsActive if it still treats the tokens as valid?

### Relevant parts of the log file

```
03 Apr 2017 12:23:10.904
 HTTP POST /connect/accesstokenvalidation responded 200 in 5339ms
03 Apr 2017 12:23:10.898
 3000: Endpoint success / Endpoints (Success), Context: EventContext {"ActivityId":"80001e6e-0002-f300-b63f-84710c7967bb","TimeStamp":"2017-04-03T17:23:10.8982…, Details: EndpointDetail {"EndpointName":"accesstokenvalidation"}
03 Apr 2017 12:23:10.897
 End access token validation request
03 Apr 2017 12:23:10.895
 Token validation success { "ValidateLifetime": true, "AccessTokenType": "Reference", "TokenHandle": "59144a46dd9393c1ff139c78f7d2bead", "Claims": { "aud": "https://localhost:44333/resources", "iss": "https://localhost:44333", "nbf": 1491240066, "exp": 1491243666, "client_id": "F1.Mobile", "scope": "openid", "sub": "5126", "auth_time": 1491240066, "idp": "ChurchStaff", "amr": "external", "tenant": "15", "church_code": "DC" } }
03 Apr 2017 12:23:05.567
 Start access token validation
03 Apr 2017 12:23:05.566
 Start access token validation request
```

**Comment by HenrikWM** [comment]
I think I see your problem. Just to verify, there is a unit test designed to protect against this exact scenario: https://github.com/IdentityServer/IdentityServer3/blob/93bc6bc9b536146b9e3fa0bed21d77283d07f788/source/Tests/UnitTests/Validation/Token%20Validation/AccessTokenValidation.cs#L250 (**Valid_AccessToken_but_User_not_active**).

You are having this issue because you are returning a `bool` from `IsActiveAsync` instead of setting the `IsActive` property. To mark a user as inactive you have to set the property `IsActive` to `false` on the method parameter `context` in `IsActiveAsync`, and **not** return `true` or `false` from `IsActiveAsync` itself. The method just returns a `Task` and the framework further down the pipeline picks up the properties you set on `IsActiveContext`. 

The `UserService` design allows us to customize behavior for authentication/authorization of users by setting properties on the context-parameters in our own `UserService` implementation, and passing the contexts along to the framework.

See this `InMemoryUserService` as a reference: https://github.com/IdentityServer/IdentityServer3/blob/93bc6bc9b536146b9e3fa0bed21d77283d07f788/source/Core/Services/InMemory/InMemoryUserService.cs#L157

Hope this helps :)

**Comment by brockallen** [comment]
Excellent -- thanks @HenrikWM!
