### ISSUE TITLE
Remember Me always remebers

### ISSUE THREAD

**Issue by stuartbloom** [IdentityServer/IdentityServer3#3692]
When I login, and then close the browser, and then restart the browser I am logged in automatically whether I have the "Remember Me" checkbox checked or not.

The UI is using the oidc-client library.

It seems to me that the userManager.getUser call always returns a user, when the checkbox is checked or not.  The only way to stop that is logging out.

Am I doing anything wrong?

**Comment by brockallen** [comment]
Unclear what's going on. You need to track down exactly where the "remembered user" is coming from.

**Comment by stuartbloom** [comment]
Did some more investigation, and can't figure it out :(  getting quite close to release date so PO has decided to remove that functionality.

Thanks for your help

**Comment by huysentruitw** [comment]
Let me add my experience here:
When you uncheck remember me, the authentication cookie should be set to 'session' (expires with browser session).
When you check remember me, the authentication cookie should get a fixed expiration time.

Verify if this is the case by inspecting the cookie, then you know the functionality is working.

Now the problem is, with most browsers, if you configure them to remember your open tabs on close/restart, they will also store the session cookie and it will seem like you're not getting logged off. AFAIK there is no work-around for this from the servers perspective. In this case, as a user, you must close your tab before closing the browser.

**Comment by stuartbloom** [comment]
@huysentruitw that makes sense, and does infact ring a bell from a previous project, thanks, I will investigate when the pressure is less ;)
